/** This file was generated by the plant-compiler.
 *
 *  Copyright and License:
 *    Code generated by the beth-plant compiler inherits the copyright and license
 *    of the beth-plant source code, which is contained in following files:
 *    badapt_dev_problem.h
 *    badapt_dev_ern.h
 *    badapt_dev_lstm.h
 *    bsym.h
 *    bhgp.h
 *
 */

#ifndef BADAPT_DEV_PLANTED_H
#define BADAPT_DEV_PLANTED_H

#include "bcore_control.h"


/**********************************************************************************************************************/
// source: badapt_dev_problem

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_dev_problem_objects

#define TYPEOF_badapt_dev_problem_objects 483428364
#define TYPEOF_badapt_dev_problem_objects_s 3324364078
#define TYPEOF_badapt_problem_recurrent_abc_s 3613882751
#define BETH_EXPAND_ITEM_badapt_problem_recurrent_abc_s \
  BCORE_DECLARE_OBJECT( badapt_problem_recurrent_abc_s ) \
    {aware_t _;sz_t index;u2_t rval;f3_t pos_tgt;f3_t neg_tgt;badapt_loss* preferred_loss;}; \
  static inline const badapt_loss* badapt_problem_recurrent_abc_s_preferred_loss( const badapt_problem_recurrent_abc_s* o ){ return o->preferred_loss; } \
  sz_t badapt_problem_recurrent_abc_s_get_in_size( const badapt_problem_recurrent_abc_s* o ); \
  sz_t badapt_problem_recurrent_abc_s_get_out_size( const badapt_problem_recurrent_abc_s* o ); \
  void badapt_problem_recurrent_abc_s_fetch_sample_tio( badapt_problem_recurrent_abc_s* o, bmath_vf3_s* in, bmath_vf3_s* out ); \
  void badapt_problem_recurrent_abc_s_fetch_sample_vio( badapt_problem_recurrent_abc_s* o, bmath_vf3_s* in, bmath_vf3_s* out );
#define TYPEOF_badapt_problem_recurrent_kjv_s 1636314442
#define BETH_EXPAND_ITEM_badapt_problem_recurrent_kjv_s \
  BCORE_DECLARE_OBJECT( badapt_problem_recurrent_kjv_s ) \
    {aware_t _;bcore_source* source;bcore_arr_sz_s* charmap;st_s* charset;u0_t t_last_char;u0_t v_last_char;u2_t rval;f3_t pos_tgt;f3_t neg_tgt;badapt_loss* preferred_loss;}; \
  static inline const badapt_loss* badapt_problem_recurrent_kjv_s_preferred_loss( const badapt_problem_recurrent_kjv_s* o ){ return o->preferred_loss; } \
  sz_t badapt_problem_recurrent_kjv_s_get_in_size( const badapt_problem_recurrent_kjv_s* o ); \
  sz_t badapt_problem_recurrent_kjv_s_get_out_size( const badapt_problem_recurrent_kjv_s* o ); \
  void badapt_problem_recurrent_kjv_s_fetch_sample_tio( badapt_problem_recurrent_kjv_s* o, bmath_vf3_s* in, bmath_vf3_s* out ); \
  void badapt_problem_recurrent_kjv_s_fetch_sample_vio( badapt_problem_recurrent_kjv_s* o, bmath_vf3_s* in, bmath_vf3_s* out );
#define TYPEOF_badapt_problem_recurrent_text_s 1449347910
#define BETH_EXPAND_ITEM_badapt_problem_recurrent_text_s \
  BCORE_DECLARE_OBJECT( badapt_problem_recurrent_text_s ) \
    {aware_t _;st_s text_file;st_s ignore_line_char;bcore_source* source;bcore_arr_sz_s* charmap;st_s* charset;u0_t t_last_char;u0_t v_last_char;u2_t rval;f3_t pos_tgt;f3_t neg_tgt;badapt_loss* preferred_loss;}; \
  static inline const badapt_loss* badapt_problem_recurrent_text_s_preferred_loss( const badapt_problem_recurrent_text_s* o ){ return o->preferred_loss; } \
  sz_t badapt_problem_recurrent_text_s_get_in_size( const badapt_problem_recurrent_text_s* o ); \
  sz_t badapt_problem_recurrent_text_s_get_out_size( const badapt_problem_recurrent_text_s* o ); \
  void badapt_problem_recurrent_text_s_fetch_sample_tio( badapt_problem_recurrent_text_s* o, bmath_vf3_s* in, bmath_vf3_s* out ); \
  void badapt_problem_recurrent_text_s_fetch_sample_vio( badapt_problem_recurrent_text_s* o, bmath_vf3_s* in, bmath_vf3_s* out );
#define TYPEOF_badapt_guide_char_encode_s 2263969302
#define BETH_EXPAND_ITEM_badapt_guide_char_encode_s \
  BCORE_DECLARE_OBJECT( badapt_guide_char_encode_s ) \
    {aware_t _;badapt_guide* guide_default;bcore_arr_sz_s* charmap;st_s* charset;f3_t pos_tgt;f3_t neg_tgt;st_s txt_trigger;sz_t txt_size;f3_t heat;}; \
  bl_t badapt_guide_char_encode_s_callback( const badapt_guide_char_encode_s* o, badapt_training_state* state );
#define BETH_EXPAND_GROUP_badapt_dev_problem_objects \
  BCORE_FORWARD_OBJECT( badapt_dev_problem_objects ); \
  BCORE_FORWARD_OBJECT( badapt_problem_recurrent_abc_s ); \
  BCORE_FORWARD_OBJECT( badapt_problem_recurrent_kjv_s ); \
  BCORE_FORWARD_OBJECT( badapt_problem_recurrent_text_s ); \
  BCORE_FORWARD_OBJECT( badapt_guide_char_encode_s ); \
  BETH_EXPAND_ITEM_badapt_problem_recurrent_abc_s \
  BETH_EXPAND_ITEM_badapt_problem_recurrent_kjv_s \
  BETH_EXPAND_ITEM_badapt_problem_recurrent_text_s \
  BETH_EXPAND_ITEM_badapt_guide_char_encode_s

/**********************************************************************************************************************/
// source: badapt_dev_ern

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_dev_ern

#define TYPEOF_badapt_dev_ern 3818246179
#define TYPEOF_badapt_dev_ern_s 3653613765
#define BETH_EXPAND_GROUP_badapt_dev_ern \
  BCORE_FORWARD_OBJECT( badapt_dev_ern );

/**********************************************************************************************************************/
// source: badapt_dev_lstm

/**********************************************************************************************************************/
// source: bsym

//----------------------------------------------------------------------------------------------------------------------
// group: bsym

#define TYPEOF_bsym 3737279812
#define TYPEOF_bsym_s 726515702
#define TYPEOF_link 232457833
#define TYPEOF_holor 1528389681
#define TYPEOF_graph 3111650887
#define TYPEOF_bsym_source_info_s 1283233195
#define BETH_EXPAND_ITEM_bsym_source_info_s \
  BCORE_DECLARE_OBJECT( bsym_source_info_s ) \
    {aware_t _;bcore_source* source;sz_t index;};
#define BETH_EXPAND_GROUP_bsym \
  BCORE_FORWARD_OBJECT( bsym ); \
  BCORE_FORWARD_OBJECT( bsym_source_info_s ); \
  BCORE_FORWARD_OBJECT( bsym_op ); \
  BCORE_FORWARD_OBJECT( bsym_net ); \
  BCORE_FORWARD_OBJECT( bsym_sem ); \
  BCORE_FORWARD_OBJECT( bsym_vm ); \
  BETH_EXPAND_ITEM_bsym_source_info_s \
  BETH_EXPAND_GROUP_bsym_op \
  BETH_EXPAND_GROUP_bsym_net \
  BETH_EXPAND_GROUP_bsym_sem \
  BETH_EXPAND_GROUP_bsym_vm

//----------------------------------------------------------------------------------------------------------------------
// group: bsym_op

#define TYPEOF_bsym_op 3109786158
#define TYPEOF_bsym_op_s 1111123888
#define BETH_EXPAND_GROUP_bsym_op \
  BCORE_FORWARD_OBJECT( bsym_op ); \
  BCORE_FORWARD_OBJECT( bsym_op_ar0 ); \
  BCORE_FORWARD_OBJECT( bsym_op_ar1 ); \
  BCORE_FORWARD_OBJECT( bsym_op_ar2 ); \
  typedef void (*bsym_op_trace_to_sink)( const bsym_op* o, sz_t indent, bcore_sink* sink ); \
  typedef sz_t (*bsym_op_get_arity)( const bsym_op* o ); \
  typedef sz_t (*bsym_op_get_priority)( const bsym_op* o ); \
  BCORE_DECLARE_SPECT( bsym_op ) \
  { \
      bcore_spect_header_s header; \
      bsym_op_trace_to_sink trace_to_sink; \
      bsym_op_get_arity get_arity; \
      bsym_op_get_priority get_priority; \
  }; \
  static inline bsym_op* bsym_op_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bsym_op, t ); return ( bsym_op* )bcore_inst_t_create( t ); } \
  static inline bl_t bsym_op_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bsym_op ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bsym_op ) \
  static inline bl_t bsym_op_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bsym_op ); } \
  static inline void bsym_op_a_trace_to_sink( const bsym_op* o, sz_t indent, bcore_sink* sink ) { bsym_op_s_get_aware( o )->trace_to_sink( o, indent, sink ); } \
  static inline bl_t bsym_op_a_defines_trace_to_sink( const bsym_op* o ) { return true; } \
  static inline void bsym_op_trace_to_sink__( const bsym_op* o, sz_t indent, bcore_sink* sink ) {} \
  static inline sz_t bsym_op_a_get_arity( const bsym_op* o ) { return bsym_op_s_get_aware( o )->get_arity( o ); } \
  static inline bl_t bsym_op_a_defines_get_arity( const bsym_op* o ) { return true; } \
  static inline sz_t bsym_op_a_get_priority( const bsym_op* o ) { return bsym_op_s_get_aware( o )->get_priority( o ); } \
  static inline bl_t bsym_op_a_defines_get_priority( const bsym_op* o ) { return true; } \
  static inline sz_t bsym_op_get_priority__( const bsym_op* o ) { return -1; } \
  BETH_EXPAND_GROUP_bsym_op_ar0 \
  BETH_EXPAND_GROUP_bsym_op_ar1 \
  BETH_EXPAND_GROUP_bsym_op_ar2

//----------------------------------------------------------------------------------------------------------------------
// group: bsym_op_ar0

#define TYPEOF_bsym_op_ar0 580013156
#define TYPEOF_bsym_op_ar0_s 4056606166
#define TYPEOF_adaptive 857148571
#define TYPEOF_buffer 2170494075
#define TYPEOF_literal 3971602660
#define TYPEOF_bsym_op_ar0_holor_s 1027345839
#define BETH_EXPAND_ITEM_bsym_op_ar0_holor_s \
  BCORE_DECLARE_OBJECT( bsym_op_ar0_holor_s ) \
    {aware_t _;tp_t type;bmath_hf3_s hf3;}; \
  static inline sz_t bsym_op_ar0_holor_s_get_arity( const bsym_op_ar0_holor_s* o ){ return 0; } \
  void bsym_op_ar0_holor_s_trace_to_sink( const bsym_op_ar0_holor_s* o, sz_t indent, bcore_sink* sink ); \
  bl_t bsym_op_ar0_holor_s_compute_hf3( const bsym_op_ar0_holor_s* o, bmath_hf3_s* r ); \
  tp_t bsym_op_ar0_holor_s_get_hf3_type( const bsym_op_ar0_holor_s* o );
#define BETH_EXPAND_GROUP_bsym_op_ar0 \
  BCORE_FORWARD_OBJECT( bsym_op_ar0 ); \
  BCORE_FORWARD_OBJECT( bsym_op_ar0_holor_s ); \
  typedef bl_t (*bsym_op_ar0_compute_hf3)( const bsym_op_ar0* o, bmath_hf3_s* r ); \
  typedef bmath_hf3_vm_op* (*bsym_op_ar0_create_vm_operator)( const bsym_op_ar0* o, const bmath_hf3_s* r ); \
  typedef tp_t (*bsym_op_ar0_get_hf3_type)( const bsym_op_ar0* o ); \
  BCORE_DECLARE_SPECT( bsym_op_ar0 ) \
  { \
      bcore_spect_header_s header; \
      bsym_op_ar0_compute_hf3 compute_hf3; \
      bsym_op_ar0_create_vm_operator create_vm_operator; \
      bsym_op_ar0_get_hf3_type get_hf3_type; \
  }; \
  static inline bsym_op_ar0* bsym_op_ar0_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bsym_op_ar0, t ); return ( bsym_op_ar0* )bcore_inst_t_create( t ); } \
  static inline bl_t bsym_op_ar0_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bsym_op_ar0 ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bsym_op_ar0 ) \
  static inline bl_t bsym_op_ar0_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bsym_op_ar0 ); } \
  static inline bl_t bsym_op_ar0_a_compute_hf3( const bsym_op_ar0* o, bmath_hf3_s* r ) { return bsym_op_ar0_s_get_aware( o )->compute_hf3( o, r ); } \
  static inline bl_t bsym_op_ar0_a_defines_compute_hf3( const bsym_op_ar0* o ) { return true; } \
  static inline bmath_hf3_vm_op* bsym_op_ar0_a_create_vm_operator( const bsym_op_ar0* o, const bmath_hf3_s* r ) { return bsym_op_ar0_s_get_aware( o )->create_vm_operator( o, r ); } \
  static inline bl_t bsym_op_ar0_a_defines_create_vm_operator( const bsym_op_ar0* o ) { return true; } \
  static inline bmath_hf3_vm_op* bsym_op_ar0_create_vm_operator__( const bsym_op_ar0* o, const bmath_hf3_s* r ) { return NULL; } \
  static inline tp_t bsym_op_ar0_a_get_hf3_type( const bsym_op_ar0* o ) { return bsym_op_ar0_s_get_aware( o )->get_hf3_type( o ); } \
  static inline bl_t bsym_op_ar0_a_defines_get_hf3_type( const bsym_op_ar0* o ) { return bsym_op_ar0_s_get_aware( o )->get_hf3_type != NULL; } \
  BETH_EXPAND_ITEM_bsym_op_ar0_holor_s

//----------------------------------------------------------------------------------------------------------------------
// group: bsym_op_ar1

#define TYPEOF_bsym_op_ar1 596790775
#define TYPEOF_bsym_op_ar1_s 1850949201
#define TYPEOF_bsym_op_ar1_linear_s 2596841019
#define BETH_EXPAND_ITEM_bsym_op_ar1_linear_s \
  BCORE_DECLARE_OBJECT( bsym_op_ar1_linear_s ) \
    {aware_t _;}; \
  static inline sz_t bsym_op_ar1_linear_s_get_arity( const bsym_op_ar1_linear_s* o ){ return 1; } \
  static inline sc_t bsym_op_ar1_linear_s_get_symbol( const bsym_op_ar1_linear_s* o ){ return "linear"; } \
  static inline bl_t bsym_op_ar1_linear_s_compute_hf3( const bsym_op_ar1_linear_s* o, const bmath_hf3_s* a, bmath_hf3_s* r ){ bmath_hf3_s_copy( r, a ); return true; }
#define TYPEOF_bsym_op_ar1_tanh_s 444204091
#define BETH_EXPAND_ITEM_bsym_op_ar1_tanh_s \
  BCORE_DECLARE_OBJECT( bsym_op_ar1_tanh_s ) \
    {aware_t _;}; \
  static inline sz_t bsym_op_ar1_tanh_s_get_arity( const bsym_op_ar1_tanh_s* o ){ return 1; } \
  static inline sc_t bsym_op_ar1_tanh_s_get_symbol( const bsym_op_ar1_tanh_s* o ){ return "tanh"  ; } \
  bl_t bsym_op_ar1_tanh_s_compute_hf3( const bsym_op_ar1_tanh_s* o, const bmath_hf3_s* a, bmath_hf3_s* r ); \
  static inline bmath_hf3_vm_op* bsym_op_ar1_tanh_s_create_vm_operator( const bsym_op_ar1_tanh_s* o, const bmath_hf3_s* a, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_tanh_s_create(); }
#define TYPEOF_bsym_op_ar1_dimof_s 1118792073
#define BETH_EXPAND_ITEM_bsym_op_ar1_dimof_s \
  BCORE_DECLARE_OBJECT( bsym_op_ar1_dimof_s ) \
    {aware_t _;}; \
  static inline sz_t bsym_op_ar1_dimof_s_get_arity( const bsym_op_ar1_dimof_s* o ){ return 1; } \
  static inline sc_t bsym_op_ar1_dimof_s_get_symbol( const bsym_op_ar1_dimof_s* o ){ return "dimof" ; } \
  bl_t bsym_op_ar1_dimof_s_compute_hf3( const bsym_op_ar1_dimof_s* o, const bmath_hf3_s* a, bmath_hf3_s* r );
#define BETH_EXPAND_GROUP_bsym_op_ar1 \
  BCORE_FORWARD_OBJECT( bsym_op_ar1 ); \
  BCORE_FORWARD_OBJECT( bsym_op_ar1_linear_s ); \
  BCORE_FORWARD_OBJECT( bsym_op_ar1_tanh_s ); \
  BCORE_FORWARD_OBJECT( bsym_op_ar1_dimof_s ); \
  typedef sc_t (*bsym_op_ar1_get_symbol)( const bsym_op_ar1* o ); \
  typedef bl_t (*bsym_op_ar1_compute_hf3)( const bsym_op_ar1* o, const bmath_hf3_s* a, bmath_hf3_s* r ); \
  typedef bmath_hf3_vm_op* (*bsym_op_ar1_create_vm_operator)( const bsym_op_ar1* o, const bmath_hf3_s* a, const bmath_hf3_s* r ); \
  BCORE_DECLARE_SPECT( bsym_op_ar1 ) \
  { \
      bcore_spect_header_s header; \
      bsym_op_ar1_get_symbol get_symbol; \
      bsym_op_ar1_compute_hf3 compute_hf3; \
      bsym_op_ar1_create_vm_operator create_vm_operator; \
  }; \
  static inline bsym_op_ar1* bsym_op_ar1_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bsym_op_ar1, t ); return ( bsym_op_ar1* )bcore_inst_t_create( t ); } \
  static inline bl_t bsym_op_ar1_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bsym_op_ar1 ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bsym_op_ar1 ) \
  static inline bl_t bsym_op_ar1_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bsym_op_ar1 ); } \
  static inline sc_t bsym_op_ar1_a_get_symbol( const bsym_op_ar1* o ) { return bsym_op_ar1_s_get_aware( o )->get_symbol( o ); } \
  static inline bl_t bsym_op_ar1_a_defines_get_symbol( const bsym_op_ar1* o ) { return true; } \
  static inline bl_t bsym_op_ar1_a_compute_hf3( const bsym_op_ar1* o, const bmath_hf3_s* a, bmath_hf3_s* r ) { return bsym_op_ar1_s_get_aware( o )->compute_hf3( o, a, r ); } \
  static inline bl_t bsym_op_ar1_a_defines_compute_hf3( const bsym_op_ar1* o ) { return bsym_op_ar1_s_get_aware( o )->compute_hf3 != NULL; } \
  static inline bmath_hf3_vm_op* bsym_op_ar1_a_create_vm_operator( const bsym_op_ar1* o, const bmath_hf3_s* a, const bmath_hf3_s* r ) { return bsym_op_ar1_s_get_aware( o )->create_vm_operator( o, a, r ); } \
  static inline bl_t bsym_op_ar1_a_defines_create_vm_operator( const bsym_op_ar1* o ) { return true; } \
  static inline bmath_hf3_vm_op* bsym_op_ar1_create_vm_operator__( const bsym_op_ar1* o, const bmath_hf3_s* a, const bmath_hf3_s* r ) { return NULL; } \
  BETH_EXPAND_ITEM_bsym_op_ar1_linear_s \
  BETH_EXPAND_ITEM_bsym_op_ar1_tanh_s \
  BETH_EXPAND_ITEM_bsym_op_ar1_dimof_s

//----------------------------------------------------------------------------------------------------------------------
// group: bsym_op_ar2

#define TYPEOF_bsym_op_ar2 613568394
#define TYPEOF_bsym_op_ar2_s 3837272692
#define TYPEOF_bsym_op_ar2_bmul_s 4072656081
#define BETH_EXPAND_ITEM_bsym_op_ar2_bmul_s \
  BCORE_DECLARE_OBJECT( bsym_op_ar2_bmul_s ) \
    {aware_t _;}; \
  static inline sz_t bsym_op_ar2_bmul_s_get_arity( const bsym_op_ar2_bmul_s* o ){ return 2; } \
  static inline sz_t bsym_op_ar2_bmul_s_get_priority( const bsym_op_ar2_bmul_s* o ){ return 9; } \
  static inline sc_t bsym_op_ar2_bmul_s_get_symbol( const bsym_op_ar2_bmul_s* o ){ return "<*>"; } \
  bl_t bsym_op_ar2_bmul_s_compute_hf3( const bsym_op_ar2_bmul_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ); \
  static inline bmath_hf3_vm_op* bsym_op_ar2_bmul_s_create_vm_operator( const bsym_op_ar2_bmul_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_bmul_s_create(); }
#define TYPEOF_bsym_op_ar2_bmul_htp_s 3141495718
#define BETH_EXPAND_ITEM_bsym_op_ar2_bmul_htp_s \
  BCORE_DECLARE_OBJECT( bsym_op_ar2_bmul_htp_s ) \
    {aware_t _;}; \
  static inline sz_t bsym_op_ar2_bmul_htp_s_get_arity( const bsym_op_ar2_bmul_htp_s* o ){ return 2; } \
  static inline sz_t bsym_op_ar2_bmul_htp_s_get_priority( const bsym_op_ar2_bmul_htp_s* o ){ return 9; } \
  static inline sc_t bsym_op_ar2_bmul_htp_s_get_symbol( const bsym_op_ar2_bmul_htp_s* o ){ return "<*t>"; } \
  bl_t bsym_op_ar2_bmul_htp_s_compute_hf3( const bsym_op_ar2_bmul_htp_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ); \
  static inline bmath_hf3_vm_op* bsym_op_ar2_bmul_htp_s_create_vm_operator( const bsym_op_ar2_bmul_htp_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_bmul_htp_s_create(); }
#define TYPEOF_bsym_op_ar2_htp_bmul_s 836633248
#define BETH_EXPAND_ITEM_bsym_op_ar2_htp_bmul_s \
  BCORE_DECLARE_OBJECT( bsym_op_ar2_htp_bmul_s ) \
    {aware_t _;}; \
  static inline sz_t bsym_op_ar2_htp_bmul_s_get_arity( const bsym_op_ar2_htp_bmul_s* o ){ return 2; } \
  static inline sz_t bsym_op_ar2_htp_bmul_s_get_priority( const bsym_op_ar2_htp_bmul_s* o ){ return 9; } \
  static inline sc_t bsym_op_ar2_htp_bmul_s_get_symbol( const bsym_op_ar2_htp_bmul_s* o ){ return "<t*>"; } \
  bl_t bsym_op_ar2_htp_bmul_s_compute_hf3( const bsym_op_ar2_htp_bmul_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ); \
  static inline bmath_hf3_vm_op* bsym_op_ar2_htp_bmul_s_create_vm_operator( const bsym_op_ar2_htp_bmul_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_htp_bmul_s_create(); }
#define TYPEOF_bsym_op_ar2_htp_bmul_htp_s 29623647
#define BETH_EXPAND_ITEM_bsym_op_ar2_htp_bmul_htp_s \
  BCORE_DECLARE_OBJECT( bsym_op_ar2_htp_bmul_htp_s ) \
    {aware_t _;}; \
  static inline sz_t bsym_op_ar2_htp_bmul_htp_s_get_arity( const bsym_op_ar2_htp_bmul_htp_s* o ){ return 2; } \
  static inline sz_t bsym_op_ar2_htp_bmul_htp_s_get_priority( const bsym_op_ar2_htp_bmul_htp_s* o ){ return 9; } \
  static inline sc_t bsym_op_ar2_htp_bmul_htp_s_get_symbol( const bsym_op_ar2_htp_bmul_htp_s* o ){ return "<t*t>"; } \
  bl_t bsym_op_ar2_htp_bmul_htp_s_compute_hf3( const bsym_op_ar2_htp_bmul_htp_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ); \
  static inline bmath_hf3_vm_op* bsym_op_ar2_htp_bmul_htp_s_create_vm_operator( const bsym_op_ar2_htp_bmul_htp_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_htp_bmul_htp_s_create(); }
#define TYPEOF_bsym_op_ar2_mul_s 3581603561
#define BETH_EXPAND_ITEM_bsym_op_ar2_mul_s \
  BCORE_DECLARE_OBJECT( bsym_op_ar2_mul_s ) \
    {aware_t _;}; \
  static inline sz_t bsym_op_ar2_mul_s_get_arity( const bsym_op_ar2_mul_s* o ){ return 2; } \
  static inline sz_t bsym_op_ar2_mul_s_get_priority( const bsym_op_ar2_mul_s* o ){ return 9; } \
  static inline sc_t bsym_op_ar2_mul_s_get_symbol( const bsym_op_ar2_mul_s* o ){ return "*"; } \
  bl_t bsym_op_ar2_mul_s_compute_hf3( const bsym_op_ar2_mul_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ); \
  bmath_hf3_vm_op* bsym_op_ar2_mul_s_create_vm_operator( const bsym_op_ar2_mul_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r );
#define TYPEOF_bsym_op_ar2_plus_s 1005616789
#define BETH_EXPAND_ITEM_bsym_op_ar2_plus_s \
  BCORE_DECLARE_OBJECT( bsym_op_ar2_plus_s ) \
    {aware_t _;}; \
  static inline sz_t bsym_op_ar2_plus_s_get_arity( const bsym_op_ar2_plus_s* o ){ return 2; } \
  static inline sz_t bsym_op_ar2_plus_s_get_priority( const bsym_op_ar2_plus_s* o ){ return 8; } \
  static inline sc_t bsym_op_ar2_plus_s_get_symbol( const bsym_op_ar2_plus_s* o ){ return "+"; } \
  bl_t bsym_op_ar2_plus_s_compute_hf3( const bsym_op_ar2_plus_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ); \
  static inline bmath_hf3_vm_op* bsym_op_ar2_plus_s_create_vm_operator( const bsym_op_ar2_plus_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_add_s_create(); }
#define TYPEOF_bsym_op_ar2_minus_s 2024488711
#define BETH_EXPAND_ITEM_bsym_op_ar2_minus_s \
  BCORE_DECLARE_OBJECT( bsym_op_ar2_minus_s ) \
    {aware_t _;}; \
  static inline sz_t bsym_op_ar2_minus_s_get_arity( const bsym_op_ar2_minus_s* o ){ return 2; } \
  static inline sz_t bsym_op_ar2_minus_s_get_priority( const bsym_op_ar2_minus_s* o ){ return 8; } \
  static inline sc_t bsym_op_ar2_minus_s_get_symbol( const bsym_op_ar2_minus_s* o ){ return "-"; } \
  bl_t bsym_op_ar2_minus_s_compute_hf3( const bsym_op_ar2_minus_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ); \
  static inline bmath_hf3_vm_op* bsym_op_ar2_minus_s_create_vm_operator( const bsym_op_ar2_minus_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_sub_s_create(); }
#define BETH_EXPAND_GROUP_bsym_op_ar2 \
  BCORE_FORWARD_OBJECT( bsym_op_ar2 ); \
  BCORE_FORWARD_OBJECT( bsym_op_ar2_bmul_s ); \
  BCORE_FORWARD_OBJECT( bsym_op_ar2_bmul_htp_s ); \
  BCORE_FORWARD_OBJECT( bsym_op_ar2_htp_bmul_s ); \
  BCORE_FORWARD_OBJECT( bsym_op_ar2_htp_bmul_htp_s ); \
  BCORE_FORWARD_OBJECT( bsym_op_ar2_mul_s ); \
  BCORE_FORWARD_OBJECT( bsym_op_ar2_plus_s ); \
  BCORE_FORWARD_OBJECT( bsym_op_ar2_minus_s ); \
  typedef sc_t (*bsym_op_ar2_get_symbol)( const bsym_op_ar2* o ); \
  typedef bl_t (*bsym_op_ar2_compute_hf3)( const bsym_op_ar2* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ); \
  typedef bmath_hf3_vm_op* (*bsym_op_ar2_create_vm_operator)( const bsym_op_ar2* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ); \
  BCORE_DECLARE_SPECT( bsym_op_ar2 ) \
  { \
      bcore_spect_header_s header; \
      bsym_op_ar2_get_symbol get_symbol; \
      bsym_op_ar2_compute_hf3 compute_hf3; \
      bsym_op_ar2_create_vm_operator create_vm_operator; \
  }; \
  static inline bsym_op_ar2* bsym_op_ar2_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bsym_op_ar2, t ); return ( bsym_op_ar2* )bcore_inst_t_create( t ); } \
  static inline bl_t bsym_op_ar2_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bsym_op_ar2 ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bsym_op_ar2 ) \
  static inline bl_t bsym_op_ar2_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bsym_op_ar2 ); } \
  static inline sc_t bsym_op_ar2_a_get_symbol( const bsym_op_ar2* o ) { return bsym_op_ar2_s_get_aware( o )->get_symbol( o ); } \
  static inline bl_t bsym_op_ar2_a_defines_get_symbol( const bsym_op_ar2* o ) { return true; } \
  static inline bl_t bsym_op_ar2_a_compute_hf3( const bsym_op_ar2* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ) { return bsym_op_ar2_s_get_aware( o )->compute_hf3( o, a, b, r ); } \
  static inline bl_t bsym_op_ar2_a_defines_compute_hf3( const bsym_op_ar2* o ) { return bsym_op_ar2_s_get_aware( o )->compute_hf3 != NULL; } \
  static inline bmath_hf3_vm_op* bsym_op_ar2_a_create_vm_operator( const bsym_op_ar2* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ) { return bsym_op_ar2_s_get_aware( o )->create_vm_operator( o, a, b, r ); } \
  static inline bl_t bsym_op_ar2_a_defines_create_vm_operator( const bsym_op_ar2* o ) { return true; } \
  static inline bmath_hf3_vm_op* bsym_op_ar2_create_vm_operator__( const bsym_op_ar2* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ) { return NULL; } \
  BETH_EXPAND_ITEM_bsym_op_ar2_bmul_s \
  BETH_EXPAND_ITEM_bsym_op_ar2_bmul_htp_s \
  BETH_EXPAND_ITEM_bsym_op_ar2_htp_bmul_s \
  BETH_EXPAND_ITEM_bsym_op_ar2_htp_bmul_htp_s \
  BETH_EXPAND_ITEM_bsym_op_ar2_mul_s \
  BETH_EXPAND_ITEM_bsym_op_ar2_plus_s \
  BETH_EXPAND_ITEM_bsym_op_ar2_minus_s

//----------------------------------------------------------------------------------------------------------------------
// group: bsym_net

#define TYPEOF_bsym_net 2379906484
#define TYPEOF_bsym_net_s 3178558630
#define TYPEOF_bsym_net_hresult_s 3418307564
#define BETH_EXPAND_ITEM_bsym_net_hresult_s \
  BCORE_DECLARE_OBJECT( bsym_net_hresult_s ) \
    {aware_t _;bmath_hf3_s* hf3;tp_t name;tp_t type;sz_t vm_index;};
#define TYPEOF_bsym_net_body_s 962574443
#define BETH_EXPAND_ITEM_bsym_net_body_s \
  BCORE_DECLARE_OBJECT( bsym_net_body_s ) \
    {aware_t _;BCORE_ARRAY_DYN_LINK_STATIC_S( bsym_net, );}; \
  void bsym_net_body_s_copy_x( bsym_net_body_s* o ); \
  static inline void bsym_net_body_s_set_space( bsym_net_body_s* o, sz_t size ) { bcore_array_t_set_space( TYPEOF_bsym_net_body_s, ( bcore_array* )o, size ); } \
  static inline void bsym_net_body_s_set_size( bsym_net_body_s* o, sz_t size ) { bcore_array_t_set_size( TYPEOF_bsym_net_body_s, ( bcore_array* )o, size ); } \
  static inline void bsym_net_body_s_clear( bsym_net_body_s* o ) { bcore_array_t_set_space( TYPEOF_bsym_net_body_s, ( bcore_array* )o, 0 ); } \
  static inline bsym_net* bsym_net_body_s_push_c( bsym_net_body_s* o, const bsym_net* v ) { bcore_array_t_push( TYPEOF_bsym_net_body_s, ( bcore_array* )o, sr_awc( v ) ); return o->data[ o->size - 1 ]; } \
  static inline bsym_net* bsym_net_body_s_push_d( bsym_net_body_s* o,       bsym_net* v ) { bcore_array_t_push( TYPEOF_bsym_net_body_s, ( bcore_array* )o, sr_asd( v ) ); return o->data[ o->size - 1 ]; } \
  static inline bsym_net* bsym_net_body_s_push_t( bsym_net_body_s* o, tp_t t ) \
  { \
      bcore_trait_assert_satisfied_type( TYPEOF_bsym_net, t ); \
      bcore_array_t_push( TYPEOF_bsym_net_body_s, ( bcore_array* )o, sr_t_create( t ) ); \
      return o->data[ o->size - 1 ]; \
  }
#define TYPEOF_bsym_net_address_s 190991353
#define BETH_EXPAND_ITEM_bsym_net_address_s \
  BCORE_DECLARE_OBJECT( bsym_net_address_s ) \
    {aware_t _;sz_t index;vd_t body;}; \
  bsym_net_node_s* bsym_net_address_s_trace_get_node( bsym_net_address_s* o ); \
  void bsym_net_address_s_trace_to_sink( const bsym_net_address_s* o, sz_t indent, bcore_sink* sink ); \
  bsym_net_hresult_s* bsym_net_address_s_trace_compute_hresult( bsym_net_address_s* o, bl_t force ); \
  void bsym_net_address_s_trace_clear_hresult( bsym_net_address_s* o ); \
  void bsym_net_address_s_trace_build_vm_proc( bsym_net_address_s* o, bmath_hf3_vm_frame_s* vmf, tp_t proc_name ); \
  bsym_net* bsym_net_address_s_get_net( const bsym_net_address_s* o );
#define TYPEOF_bsym_net_link_s 622852007
#define BETH_EXPAND_ITEM_bsym_net_link_s \
  BCORE_DECLARE_OBJECT( bsym_net_link_s ) \
    {aware_t _;tp_t name;bsym_net_address_s target;bsym_net_address_s root;bl_t flag;}; \
  static inline tp_t bsym_net_link_s_get_name( const bsym_net_link_s* o ){ return o->name; } \
  void bsym_net_link_s_set_body( bsym_net_link_s* o, bsym_net_body_s* body ); \
  static inline bsym_net_node_s* bsym_net_link_s_trace_get_node( bsym_net_link_s* o ){ return bsym_net_address_s_trace_get_node( &o->target ); } \
  void bsym_net_link_s_trace_to_sink( const bsym_net_link_s* o, sz_t indent, bcore_sink* sink ); \
  static inline bsym_net_hresult_s* bsym_net_link_s_trace_compute_hresult( bsym_net_link_s* o, bl_t force ){ return bsym_net_address_s_trace_compute_hresult( &o->target, force ); } \
  static inline void bsym_net_link_s_trace_clear_hresult( bsym_net_link_s* o ){        bsym_net_address_s_trace_clear_hresult(   &o->target ); } \
  static inline void bsym_net_link_s_trace_build_vm_proc( bsym_net_link_s* o, bmath_hf3_vm_frame_s* vmf, tp_t proc_name ){        bsym_net_address_s_trace_build_vm_proc(   &o->target, vmf, proc_name ); }
#define TYPEOF_infer 796211167
#define TYPEOF_bsym_net_node_s 1739206867
#define BETH_EXPAND_ITEM_bsym_net_node_s \
  BCORE_DECLARE_OBJECT( bsym_net_node_s ) \
    {aware_t _;tp_t name;BCORE_ARRAY_DYN_SOLID_STATIC_S( bsym_net_address_s, targets_ );bsym_net_address_s root;bsym_op* op;bsym_source_info_s source_info;bsym_net_hresult_s* hresult;bsym_net_address_s* new_root;}; \
  static inline tp_t bsym_net_node_s_get_name( const bsym_net_node_s* o ){ return o->name; } \
  void bsym_net_node_s_set_body( bsym_net_node_s* o, bsym_net_body_s* body ); \
  static inline bsym_net_node_s* bsym_net_node_s_trace_get_node( bsym_net_node_s* o ){ return o; } \
  void bsym_net_node_s_trace_to_sink( const bsym_net_node_s* o, sz_t indent, bcore_sink* sink ); \
  bsym_net_hresult_s* bsym_net_node_s_trace_compute_hresult( bsym_net_node_s* o, bl_t force ); \
  void bsym_net_node_s_trace_clear_hresult( bsym_net_node_s* o ); \
  void bsym_net_node_s_trace_build_vm_proc( bsym_net_node_s* o, bmath_hf3_vm_frame_s* vmf, tp_t proc_name ); \
  static inline void bsym_net_node_s_set_space( bsym_net_node_s* o, sz_t size ) { bcore_array_t_set_space( TYPEOF_bsym_net_node_s, ( bcore_array* )o, size ); } \
  static inline void bsym_net_node_s_set_size( bsym_net_node_s* o, sz_t size ) { bcore_array_t_set_size( TYPEOF_bsym_net_node_s, ( bcore_array* )o, size ); } \
  static inline void bsym_net_node_s_clear( bsym_net_node_s* o ) { bcore_array_t_set_space( TYPEOF_bsym_net_node_s, ( bcore_array* )o, 0 ); } \
  static inline bsym_net_address_s* bsym_net_node_s_push_c( bsym_net_node_s* o, const bsym_net_address_s* v ) { bcore_array_t_push( TYPEOF_bsym_net_node_s, ( bcore_array* )o, sr_twc( TYPEOF_bsym_net_address_s, v ) ); return &o->targets_data[ o->targets_size - 1 ]; } \
  static inline bsym_net_address_s* bsym_net_node_s_push_d( bsym_net_node_s* o,       bsym_net_address_s* v ) { bcore_array_t_push( TYPEOF_bsym_net_node_s, ( bcore_array* )o, sr_tsd( TYPEOF_bsym_net_address_s, v ) ); return &o->targets_data[ o->targets_size - 1 ]; } \
  static inline bsym_net_address_s* bsym_net_node_s_push( bsym_net_node_s* o ) \
  { \
      bcore_array_t_push( TYPEOF_bsym_net_node_s, ( bcore_array* )o, sr_null() ); \
      return &o->targets_data[ o->targets_size - 1 ]; \
  }
#define BETH_EXPAND_GROUP_bsym_net \
  BCORE_FORWARD_OBJECT( bsym_net ); \
  BCORE_FORWARD_OBJECT( bsym_net_hresult_s ); \
  BCORE_FORWARD_OBJECT( bsym_net_body_s ); \
  BCORE_FORWARD_OBJECT( bsym_net_address_s ); \
  BCORE_FORWARD_OBJECT( bsym_net_link_s ); \
  BCORE_FORWARD_OBJECT( bsym_net_node_s ); \
  typedef void (*bsym_net_trace_to_sink)( const bsym_net* o, sz_t indent, bcore_sink* sink ); \
  typedef tp_t (*bsym_net_get_name)( const bsym_net* o ); \
  typedef void (*bsym_net_set_body)( bsym_net* o, bsym_net_body_s* body ); \
  typedef bsym_net_node_s* (*bsym_net_trace_get_node)( bsym_net* o ); \
  typedef bsym_net_hresult_s* (*bsym_net_trace_compute_hresult)( bsym_net* o, bl_t force ); \
  typedef void (*bsym_net_trace_clear_hresult)( bsym_net* o ); \
  typedef void (*bsym_net_trace_build_vm_proc)( bsym_net* o, bmath_hf3_vm_frame_s* vmf, tp_t proc_name ); \
  BCORE_DECLARE_SPECT( bsym_net ) \
  { \
      bcore_spect_header_s header; \
      bsym_net_trace_to_sink trace_to_sink; \
      bsym_net_get_name get_name; \
      bsym_net_set_body set_body; \
      bsym_net_trace_get_node trace_get_node; \
      bsym_net_trace_compute_hresult trace_compute_hresult; \
      bsym_net_trace_clear_hresult trace_clear_hresult; \
      bsym_net_trace_build_vm_proc trace_build_vm_proc; \
  }; \
  static inline bsym_net* bsym_net_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bsym_net, t ); return ( bsym_net* )bcore_inst_t_create( t ); } \
  static inline bl_t bsym_net_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bsym_net ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bsym_net ) \
  static inline bl_t bsym_net_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bsym_net ); } \
  BETH_EXPAND_ITEM_bsym_net_hresult_s \
  static inline void bsym_net_a_trace_to_sink( const bsym_net* o, sz_t indent, bcore_sink* sink ) { bsym_net_s_get_aware( o )->trace_to_sink( o, indent, sink ); } \
  static inline bl_t bsym_net_a_defines_trace_to_sink( const bsym_net* o ) { return true; } \
  static inline void bsym_net_trace_to_sink__( const bsym_net* o, sz_t indent, bcore_sink* sink ) {} \
  static inline tp_t bsym_net_a_get_name( const bsym_net* o ) { return bsym_net_s_get_aware( o )->get_name( o ); } \
  static inline bl_t bsym_net_a_defines_get_name( const bsym_net* o ) { return true; } \
  static inline tp_t bsym_net_get_name__( const bsym_net* o ) { return 0; } \
  static inline void bsym_net_a_set_body( bsym_net* o, bsym_net_body_s* body ) { bsym_net_s_get_aware( o )->set_body( o, body ); } \
  static inline bl_t bsym_net_a_defines_set_body( const bsym_net* o ) { return true; } \
  static inline void bsym_net_set_body__( bsym_net* o, bsym_net_body_s* body ) {} \
  static inline bsym_net_node_s* bsym_net_a_trace_get_node( bsym_net* o ) { return bsym_net_s_get_aware( o )->trace_get_node( o ); } \
  static inline bl_t bsym_net_a_defines_trace_get_node( const bsym_net* o ) { return true; } \
  static inline bsym_net_node_s* bsym_net_trace_get_node__( bsym_net* o ) { return NULL; } \
  static inline bsym_net_hresult_s* bsym_net_a_trace_compute_hresult( bsym_net* o, bl_t force ) { return bsym_net_s_get_aware( o )->trace_compute_hresult( o, force ); } \
  static inline bl_t bsym_net_a_defines_trace_compute_hresult( const bsym_net* o ) { return true; } \
  static inline bsym_net_hresult_s* bsym_net_trace_compute_hresult__( bsym_net* o, bl_t force ) { return NULL; } \
  static inline void bsym_net_a_trace_clear_hresult( bsym_net* o ) { bsym_net_s_get_aware( o )->trace_clear_hresult( o ); } \
  static inline bl_t bsym_net_a_defines_trace_clear_hresult( const bsym_net* o ) { return true; } \
  static inline void bsym_net_trace_clear_hresult__( bsym_net* o ) {} \
  static inline void bsym_net_a_trace_build_vm_proc( bsym_net* o, bmath_hf3_vm_frame_s* vmf, tp_t proc_name ) { bsym_net_s_get_aware( o )->trace_build_vm_proc( o, vmf, proc_name ); } \
  static inline bl_t bsym_net_a_defines_trace_build_vm_proc( const bsym_net* o ) { return true; } \
  static inline void bsym_net_trace_build_vm_proc__( bsym_net* o, bmath_hf3_vm_frame_s* vmf, tp_t proc_name ) {} \
  BETH_EXPAND_ITEM_bsym_net_body_s \
  BETH_EXPAND_ITEM_bsym_net_address_s \
  BETH_EXPAND_ITEM_bsym_net_link_s \
  BETH_EXPAND_ITEM_bsym_net_node_s

//----------------------------------------------------------------------------------------------------------------------
// group: bsym_sem

#define TYPEOF_bsym_sem 3159687756
#define TYPEOF_bsym_sem_s 1224764270
#define TYPEOF_bsym_sem_graph_s 701643229
#define BETH_EXPAND_ITEM_bsym_sem_graph_s \
  BCORE_DECLARE_OBJECT( bsym_sem_graph_s ) \
    {aware_t _;tp_t name;sz_t args_in;sz_t args_out;bsym_net_body_s body;bsym_sem_graph_base_s* graph_base;bcore_arr_st_s* arr_symbol_op2;bsym_source_info_s source_info;sz_t priority;};
#define TYPEOF_bsym_sem_graph_base_s 3559002339
#define BETH_EXPAND_ITEM_bsym_sem_graph_base_s \
  BCORE_DECLARE_OBJECT( bsym_sem_graph_base_s ) \
    {aware_t _;bsym_sem_graph_base_s* parent;BCORE_ARRAY_DYN_LINK_STATIC_S( bsym_sem, );}; \
  static inline void bsym_sem_graph_base_s_set_space( bsym_sem_graph_base_s* o, sz_t size ) { bcore_array_t_set_space( TYPEOF_bsym_sem_graph_base_s, ( bcore_array* )o, size ); } \
  static inline void bsym_sem_graph_base_s_set_size( bsym_sem_graph_base_s* o, sz_t size ) { bcore_array_t_set_size( TYPEOF_bsym_sem_graph_base_s, ( bcore_array* )o, size ); } \
  static inline void bsym_sem_graph_base_s_clear( bsym_sem_graph_base_s* o ) { bcore_array_t_set_space( TYPEOF_bsym_sem_graph_base_s, ( bcore_array* )o, 0 ); } \
  static inline bsym_sem* bsym_sem_graph_base_s_push_c( bsym_sem_graph_base_s* o, const bsym_sem* v ) { bcore_array_t_push( TYPEOF_bsym_sem_graph_base_s, ( bcore_array* )o, sr_awc( v ) ); return o->data[ o->size - 1 ]; } \
  static inline bsym_sem* bsym_sem_graph_base_s_push_d( bsym_sem_graph_base_s* o,       bsym_sem* v ) { bcore_array_t_push( TYPEOF_bsym_sem_graph_base_s, ( bcore_array* )o, sr_asd( v ) ); return o->data[ o->size - 1 ]; } \
  static inline bsym_sem* bsym_sem_graph_base_s_push_t( bsym_sem_graph_base_s* o, tp_t t ) \
  { \
      bcore_trait_assert_satisfied_type( TYPEOF_bsym_sem, t ); \
      bcore_array_t_push( TYPEOF_bsym_sem_graph_base_s, ( bcore_array* )o, sr_t_create( t ) ); \
      return o->data[ o->size - 1 ]; \
  }
#define TYPEOF_bsym_sem_stack_flag_s 1899517360
#define BETH_EXPAND_ITEM_bsym_sem_stack_flag_s \
  BCORE_DECLARE_OBJECT( bsym_sem_stack_flag_s ) \
    {aware_t _;};
#define BETH_EXPAND_GROUP_bsym_sem \
  BCORE_FORWARD_OBJECT( bsym_sem ); \
  BCORE_FORWARD_OBJECT( bsym_sem_graph_s ); \
  BCORE_FORWARD_OBJECT( bsym_sem_graph_base_s ); \
  BCORE_FORWARD_OBJECT( bsym_sem_stack_flag_s ); \
  BETH_EXPAND_ITEM_bsym_sem_graph_s \
  BETH_EXPAND_ITEM_bsym_sem_graph_base_s \
  BETH_EXPAND_ITEM_bsym_sem_stack_flag_s

//----------------------------------------------------------------------------------------------------------------------
// group: bsym_vm

#define TYPEOF_bsym_vm 3262211752
#define TYPEOF_bsym_vm_s 344106834
#define TYPEOF_bsym_vm_adaptive_s 2214738333
#define BETH_EXPAND_ITEM_bsym_vm_adaptive_s \
  BCORE_DECLARE_OBJECT( bsym_vm_adaptive_s ) \
    {aware_t _;st_s holograph_file;bmath_hf3_vm_frame_s vm;badapt_dynamics_std_s dynamics;sz_t in_size;sz_t out_size;sz_t in_index;sz_t out_index;}; \
  static inline sz_t bsym_vm_adaptive_s_get_in_size( const bsym_vm_adaptive_s* o ){ return o->in_size;  } \
  static inline sz_t bsym_vm_adaptive_s_get_out_size( const bsym_vm_adaptive_s* o ){ return o->out_size; } \
  static inline void bsym_vm_adaptive_s_get_dynamics_std( const bsym_vm_adaptive_s* o, badapt_dynamics_std_s* dynamics ){ badapt_dynamics_std_s_copy( dynamics, &o->dynamics ); } \
  static inline void bsym_vm_adaptive_s_set_dynamics_std( bsym_vm_adaptive_s* o, const badapt_dynamics_std_s* dynamics ){ badapt_dynamics_std_s_copy( &o->dynamics, dynamics ); } \
  void bsym_vm_adaptive_s_minfer( bsym_vm_adaptive_s* o, const bmath_vf3_s* in, bmath_vf3_s* out ); \
  static inline void bsym_vm_adaptive_s_bgrad_adapt( bsym_vm_adaptive_s* o, bmath_vf3_s* grad_in, const bmath_vf3_s* grad_out ){}
#define TYPEOF_bsym_vm_builder_s 1381296970
#define BETH_EXPAND_ITEM_bsym_vm_builder_s \
  BCORE_DECLARE_OBJECT( bsym_vm_builder_s ) \
    {aware_t _;st_s holograph_file;st_s name_out_holor;st_s name_out_size;st_s name_in_holor;sz_t in_size;sz_t out_size;u2_t rseed;badapt_dynamics_std_s dynamics;}; \
  static inline sz_t bsym_vm_builder_s_get_in_size( const bsym_vm_builder_s* o ){ return o->in_size; } \
  static inline void bsym_vm_builder_s_set_in_size( bsym_vm_builder_s* o, sz_t size ){ o->in_size = size; } \
  static inline sz_t bsym_vm_builder_s_get_out_size( const bsym_vm_builder_s* o ){ return o->out_size; } \
  static inline void bsym_vm_builder_s_set_out_size( bsym_vm_builder_s* o, sz_t size ){ o->out_size = size; } \
  badapt_adaptive* bsym_vm_builder_s_build( const bsym_vm_builder_s* o );
#define BETH_EXPAND_GROUP_bsym_vm \
  BCORE_FORWARD_OBJECT( bsym_vm ); \
  BCORE_FORWARD_OBJECT( bsym_vm_adaptive_s ); \
  BCORE_FORWARD_OBJECT( bsym_vm_builder_s ); \
  BETH_EXPAND_ITEM_bsym_vm_adaptive_s \
  BETH_EXPAND_ITEM_bsym_vm_builder_s

/**********************************************************************************************************************/
// source: bhgp

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp

#define TYPEOF_bhgp 203016256
#define TYPEOF_bhgp_s 1529856794
#define TYPEOF_cell 1759288501
#define TYPEOF_if 959999494
#define TYPEOF_then 3844270454
#define TYPEOF_else 3183434736
#define TYPEOF_bhgp_context_s 4138516086
#define BETH_EXPAND_ITEM_bhgp_context_s \
  BCORE_DECLARE_OBJECT( bhgp_context_s ) \
    {aware_t _;bcore_hmap_name_s hmap_name;bcore_arr_st_s arr_symbol_op2;bhgp_sem_cell_s cell;bcore_arr_tp_s control_types;};
#define BETH_EXPAND_GROUP_bhgp \
  BCORE_FORWARD_OBJECT( bhgp ); \
  BCORE_FORWARD_OBJECT( bhgp_op ); \
  BCORE_FORWARD_OBJECT( bhgp_sem ); \
  BCORE_FORWARD_OBJECT( bhgp_ctr ); \
  BCORE_FORWARD_OBJECT( bhgp_net ); \
  BCORE_FORWARD_OBJECT( bhgp_vm ); \
  BCORE_FORWARD_OBJECT( bhgp_context_s ); \
  BETH_EXPAND_GROUP_bhgp_op \
  BETH_EXPAND_GROUP_bhgp_sem \
  BETH_EXPAND_GROUP_bhgp_ctr \
  BETH_EXPAND_GROUP_bhgp_net \
  BETH_EXPAND_GROUP_bhgp_vm \
  BETH_EXPAND_ITEM_bhgp_context_s

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_op

#define TYPEOF_bhgp_op 3991629506
#define TYPEOF_bhgp_op_s 545355580
#define BETH_EXPAND_GROUP_bhgp_op \
  BCORE_FORWARD_OBJECT( bhgp_op ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar0 ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar1 ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2 ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar3 ); \
  typedef sz_t (*bhgp_op_get_arity)( const bhgp_op* o ); \
  typedef sz_t (*bhgp_op_get_priority)( const bhgp_op* o ); \
  typedef sc_t (*bhgp_op_get_symbol)( const bhgp_op* o ); \
  typedef s2_t (*bhgp_op_solve)( const bhgp_op* o, bmath_hf3_s** r, bmath_hf3_s** a ); \
  typedef bhgp_op* (*bhgp_op_create_final)( const bhgp_op* o, bmath_hf3_s* h ); \
  BCORE_DECLARE_SPECT( bhgp_op ) \
  { \
      bcore_spect_header_s header; \
      bhgp_op_get_arity get_arity; \
      bhgp_op_get_priority get_priority; \
      bhgp_op_get_symbol get_symbol; \
      bhgp_op_solve solve; \
      bhgp_op_create_final create_final; \
  }; \
  static inline bhgp_op* bhgp_op_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bhgp_op, t ); return ( bhgp_op* )bcore_inst_t_create( t ); } \
  static inline bl_t bhgp_op_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bhgp_op ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bhgp_op ) \
  static inline bl_t bhgp_op_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bhgp_op ); } \
  static inline sz_t bhgp_op_a_get_arity( const bhgp_op* o ) { return bhgp_op_s_get_aware( o )->get_arity( o ); } \
  static inline bl_t bhgp_op_a_defines_get_arity( const bhgp_op* o ) { return true; } \
  static inline sz_t bhgp_op_a_get_priority( const bhgp_op* o ) { return bhgp_op_s_get_aware( o )->get_priority( o ); } \
  static inline bl_t bhgp_op_a_defines_get_priority( const bhgp_op* o ) { return true; } \
  static inline sz_t bhgp_op_get_priority__( const bhgp_op* o ) { return 10; } \
  static inline sc_t bhgp_op_a_get_symbol( const bhgp_op* o ) { return bhgp_op_s_get_aware( o )->get_symbol( o ); } \
  static inline bl_t bhgp_op_a_defines_get_symbol( const bhgp_op* o ) { return true; } \
  static inline sc_t bhgp_op_get_symbol__( const bhgp_op* o ) { return NULL; } \
  static inline s2_t bhgp_op_a_solve( const bhgp_op* o, bmath_hf3_s** r, bmath_hf3_s** a ) { return bhgp_op_s_get_aware( o )->solve( o, r, a ); } \
  static inline bl_t bhgp_op_a_defines_solve( const bhgp_op* o ) { return bhgp_op_s_get_aware( o )->solve != NULL; } \
  static inline bhgp_op* bhgp_op_a_create_final( const bhgp_op* o, bmath_hf3_s* h ) { return bhgp_op_s_get_aware( o )->create_final( o, h ); } \
  static inline bl_t bhgp_op_a_defines_create_final( const bhgp_op* o ) { return true; } \
  bhgp_op* bhgp_op_create_final__( const bhgp_op* o, bmath_hf3_s* h ); \
  BETH_EXPAND_GROUP_bhgp_op_ar0 \
  BETH_EXPAND_GROUP_bhgp_op_ar1 \
  BETH_EXPAND_GROUP_bhgp_op_ar2 \
  BETH_EXPAND_GROUP_bhgp_op_ar3

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_op_ar0

#define TYPEOF_bhgp_op_ar0 2984881872
#define TYPEOF_bhgp_op_ar0_s 1042759210
#define TYPEOF_bhgp_op_ar0_holor_s 204069235
#define BETH_EXPAND_ITEM_bhgp_op_ar0_holor_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar0_holor_s ) \
    {aware_t _;bmath_hf3_s* h;}; \
  static inline sz_t bhgp_op_ar0_holor_s_get_arity( const bhgp_op_ar0_holor_s* o ){ return 0; } \
  s2_t bhgp_op_ar0_holor_s_solve( const bhgp_op_ar0_holor_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define TYPEOF_bhgp_op_ar0_input_s 842926341
#define BETH_EXPAND_ITEM_bhgp_op_ar0_input_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar0_input_s ) \
    {aware_t _;bmath_hf3_s* h;}; \
  static inline sz_t bhgp_op_ar0_input_s_get_arity( const bhgp_op_ar0_input_s* o ){ return 0; } \
  s2_t bhgp_op_ar0_input_s_solve( const bhgp_op_ar0_input_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define TYPEOF_bhgp_op_ar0_adapt_s 256616481
#define BETH_EXPAND_ITEM_bhgp_op_ar0_adapt_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar0_adapt_s ) \
    {aware_t _;bmath_hf3_s* h;}; \
  static inline sz_t bhgp_op_ar0_adapt_s_get_arity( const bhgp_op_ar0_adapt_s* o ){ return 0; } \
  s2_t bhgp_op_ar0_adapt_s_solve( const bhgp_op_ar0_adapt_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define BETH_EXPAND_GROUP_bhgp_op_ar0 \
  BCORE_FORWARD_OBJECT( bhgp_op_ar0 ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar0_holor_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar0_input_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar0_adapt_s ); \
  BETH_EXPAND_ITEM_bhgp_op_ar0_holor_s \
  BETH_EXPAND_ITEM_bhgp_op_ar0_input_s \
  BETH_EXPAND_ITEM_bhgp_op_ar0_adapt_s

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_op_ar1

#define TYPEOF_bhgp_op_ar1 3001659491
#define TYPEOF_bhgp_op_ar1_s 2605528325
#define TYPEOF_bhgp_op_ar1_linear_s 3124354487
#define BETH_EXPAND_ITEM_bhgp_op_ar1_linear_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar1_linear_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar1_linear_s_get_symbol( const bhgp_op_ar1_linear_s* o ){ return "linear"; } \
  static inline sz_t bhgp_op_ar1_linear_s_get_arity( const bhgp_op_ar1_linear_s* o ){ return 1; } \
  static inline sz_t bhgp_op_ar1_linear_s_get_priority( const bhgp_op_ar1_linear_s* o ){ return 8; } \
  s2_t bhgp_op_ar1_linear_s_solve( const bhgp_op_ar1_linear_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define TYPEOF_bhgp_op_ar1_floor_s 70512908
#define BETH_EXPAND_ITEM_bhgp_op_ar1_floor_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar1_floor_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar1_floor_s_get_symbol( const bhgp_op_ar1_floor_s* o ){ return "floor"; } \
  static inline sz_t bhgp_op_ar1_floor_s_get_arity( const bhgp_op_ar1_floor_s* o ){ return 1; } \
  static inline sz_t bhgp_op_ar1_floor_s_get_priority( const bhgp_op_ar1_floor_s* o ){ return 8; } \
  static inline bmath_hf3_vm_op* bhgp_op_ar1_floor_s_create_vm_op( const bhgp_op_ar1_floor_s* o, const bmath_hf3_s* a, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_unary_s_create_unary( floor ); } \
  static inline s2_t bhgp_op_ar1_floor_s_solve( const bhgp_op_ar1_floor_s* o, bmath_hf3_s** r, bmath_hf3_s** a ){ return bhgp_op_ar1_solve_unary( r, a, floor ); }
#define TYPEOF_bhgp_op_ar1_ceil_s 953341815
#define BETH_EXPAND_ITEM_bhgp_op_ar1_ceil_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar1_ceil_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar1_ceil_s_get_symbol( const bhgp_op_ar1_ceil_s* o ){ return "ceil"; } \
  static inline sz_t bhgp_op_ar1_ceil_s_get_arity( const bhgp_op_ar1_ceil_s* o ){ return 1; } \
  static inline sz_t bhgp_op_ar1_ceil_s_get_priority( const bhgp_op_ar1_ceil_s* o ){ return 8; } \
  static inline bmath_hf3_vm_op* bhgp_op_ar1_ceil_s_create_vm_op( const bhgp_op_ar1_ceil_s* o, const bmath_hf3_s* a, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_unary_s_create_unary( ceil ); } \
  static inline s2_t bhgp_op_ar1_ceil_s_solve( const bhgp_op_ar1_ceil_s* o, bmath_hf3_s** r, bmath_hf3_s** a ){ return bhgp_op_ar1_solve_unary( r, a, ceil ); }
#define TYPEOF_bhgp_op_ar1_tanh_s 1042225039
#define BETH_EXPAND_ITEM_bhgp_op_ar1_tanh_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar1_tanh_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar1_tanh_s_get_symbol( const bhgp_op_ar1_tanh_s* o ){ return "tanh"; } \
  static inline sz_t bhgp_op_ar1_tanh_s_get_arity( const bhgp_op_ar1_tanh_s* o ){ return 1; } \
  static inline sz_t bhgp_op_ar1_tanh_s_get_priority( const bhgp_op_ar1_tanh_s* o ){ return 8; } \
  static inline bmath_hf3_vm_op* bhgp_op_ar1_tanh_s_create_vm_op( const bhgp_op_ar1_tanh_s* o, const bmath_hf3_s* a, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_unary_s_create_unary( tanh ); } \
  static inline s2_t bhgp_op_ar1_tanh_s_solve( const bhgp_op_ar1_tanh_s* o, bmath_hf3_s** r, bmath_hf3_s** a ){ return bhgp_op_ar1_solve_unary( r, a, tanh ); }
#define TYPEOF_bhgp_op_ar1_exp_s 515336869
#define BETH_EXPAND_ITEM_bhgp_op_ar1_exp_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar1_exp_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar1_exp_s_get_symbol( const bhgp_op_ar1_exp_s* o ){ return "exp"; } \
  static inline sz_t bhgp_op_ar1_exp_s_get_arity( const bhgp_op_ar1_exp_s* o ){ return 1; } \
  static inline sz_t bhgp_op_ar1_exp_s_get_priority( const bhgp_op_ar1_exp_s* o ){ return 8; } \
  static inline bmath_hf3_vm_op* bhgp_op_ar1_exp_s_create_vm_op( const bhgp_op_ar1_exp_s* o, const bmath_hf3_s* a, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_unary_s_create_unary( exp ); } \
  static inline s2_t bhgp_op_ar1_exp_s_solve( const bhgp_op_ar1_exp_s* o, bmath_hf3_s** r, bmath_hf3_s** a ){ return bhgp_op_ar1_solve_unary( r, a, exp ); }
#define TYPEOF_bhgp_op_ar1_relu_s 2327408340
#define BETH_EXPAND_ITEM_bhgp_op_ar1_relu_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar1_relu_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar1_relu_s_get_symbol( const bhgp_op_ar1_relu_s* o ){ return "relu"  ; } \
  static inline sz_t bhgp_op_ar1_relu_s_get_arity( const bhgp_op_ar1_relu_s* o ){ return 1; } \
  static inline sz_t bhgp_op_ar1_relu_s_get_priority( const bhgp_op_ar1_relu_s* o ){ return 8; } \
  s2_t bhgp_op_ar1_relu_s_solve( const bhgp_op_ar1_relu_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define TYPEOF_bhgp_op_ar1_lrelu_s 3125081736
#define BETH_EXPAND_ITEM_bhgp_op_ar1_lrelu_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar1_lrelu_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar1_lrelu_s_get_symbol( const bhgp_op_ar1_lrelu_s* o ){ return "lrelu"  ; } \
  static inline sz_t bhgp_op_ar1_lrelu_s_get_arity( const bhgp_op_ar1_lrelu_s* o ){ return 1; } \
  static inline sz_t bhgp_op_ar1_lrelu_s_get_priority( const bhgp_op_ar1_lrelu_s* o ){ return 8; } \
  s2_t bhgp_op_ar1_lrelu_s_solve( const bhgp_op_ar1_lrelu_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define TYPEOF_bhgp_op_ar1_adapt_s 3274603774
#define BETH_EXPAND_ITEM_bhgp_op_ar1_adapt_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar1_adapt_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar1_adapt_s_get_symbol( const bhgp_op_ar1_adapt_s* o ){ return "adapt"; } \
  static inline sz_t bhgp_op_ar1_adapt_s_get_arity( const bhgp_op_ar1_adapt_s* o ){ return 1; } \
  static inline sz_t bhgp_op_ar1_adapt_s_get_priority( const bhgp_op_ar1_adapt_s* o ){ return 8; } \
  s2_t bhgp_op_ar1_adapt_s_solve( const bhgp_op_ar1_adapt_s* o, bmath_hf3_s** r, bmath_hf3_s** a ); \
  bhgp_op* bhgp_op_ar1_adapt_s_create_final( const bhgp_op_ar1_adapt_s* o, bmath_hf3_s* h );
#define TYPEOF_bhgp_op_ar1_identity_s 1990426320
#define BETH_EXPAND_ITEM_bhgp_op_ar1_identity_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar1_identity_s ) \
    {aware_t _;}; \
  static inline sz_t bhgp_op_ar1_identity_s_get_arity( const bhgp_op_ar1_identity_s* o ){ return 1; } \
  s2_t bhgp_op_ar1_identity_s_solve( const bhgp_op_ar1_identity_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define TYPEOF_bhgp_op_ar1_output_s 1132244563
#define BETH_EXPAND_ITEM_bhgp_op_ar1_output_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar1_output_s ) \
    {aware_t _;}; \
  static inline sz_t bhgp_op_ar1_output_s_get_arity( const bhgp_op_ar1_output_s* o ){ return 1; } \
  s2_t bhgp_op_ar1_output_s_solve( const bhgp_op_ar1_output_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define TYPEOF_bhgp_op_ar1_dimof_s 3508651461
#define BETH_EXPAND_ITEM_bhgp_op_ar1_dimof_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar1_dimof_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar1_dimof_s_get_symbol( const bhgp_op_ar1_dimof_s* o ){ return "dimof" ; } \
  static inline sz_t bhgp_op_ar1_dimof_s_get_arity( const bhgp_op_ar1_dimof_s* o ){ return 1; } \
  static inline sz_t bhgp_op_ar1_dimof_s_get_priority( const bhgp_op_ar1_dimof_s* o ){ return 8; } \
  s2_t bhgp_op_ar1_dimof_s_solve( const bhgp_op_ar1_dimof_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define TYPEOF_bhgp_op_ar1_rand_s 1222864213
#define BETH_EXPAND_ITEM_bhgp_op_ar1_rand_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar1_rand_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar1_rand_s_get_symbol( const bhgp_op_ar1_rand_s* o ){ return "rand" ; } \
  static inline sz_t bhgp_op_ar1_rand_s_get_arity( const bhgp_op_ar1_rand_s* o ){ return 1; } \
  static inline sz_t bhgp_op_ar1_rand_s_get_priority( const bhgp_op_ar1_rand_s* o ){ return 8; } \
  s2_t bhgp_op_ar1_rand_s_solve( const bhgp_op_ar1_rand_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define BETH_EXPAND_GROUP_bhgp_op_ar1 \
  BCORE_FORWARD_OBJECT( bhgp_op_ar1 ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar1_linear_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar1_floor_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar1_ceil_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar1_tanh_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar1_exp_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar1_relu_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar1_lrelu_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar1_adapt_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar1_identity_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar1_output_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar1_dimof_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar1_rand_s ); \
  typedef bmath_hf3_vm_op* (*bhgp_op_ar1_create_vm_op)( const bhgp_op_ar1* o, const bmath_hf3_s* a, const bmath_hf3_s* r ); \
  BCORE_DECLARE_SPECT( bhgp_op_ar1 ) \
  { \
      bcore_spect_header_s header; \
      bhgp_op_ar1_create_vm_op create_vm_op; \
  }; \
  static inline bhgp_op_ar1* bhgp_op_ar1_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bhgp_op_ar1, t ); return ( bhgp_op_ar1* )bcore_inst_t_create( t ); } \
  static inline bl_t bhgp_op_ar1_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bhgp_op_ar1 ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bhgp_op_ar1 ) \
  static inline bl_t bhgp_op_ar1_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bhgp_op_ar1 ); } \
  static inline bmath_hf3_vm_op* bhgp_op_ar1_a_create_vm_op( const bhgp_op_ar1* o, const bmath_hf3_s* a, const bmath_hf3_s* r ) { return bhgp_op_ar1_s_get_aware( o )->create_vm_op( o, a, r ); } \
  static inline bl_t bhgp_op_ar1_a_defines_create_vm_op( const bhgp_op_ar1* o ) { return true; } \
  static inline bmath_hf3_vm_op* bhgp_op_ar1_create_vm_op__( const bhgp_op_ar1* o, const bmath_hf3_s* a, const bmath_hf3_s* r ) { return NULL; } \
  BETH_EXPAND_ITEM_bhgp_op_ar1_linear_s \
  BETH_EXPAND_ITEM_bhgp_op_ar1_floor_s \
  BETH_EXPAND_ITEM_bhgp_op_ar1_ceil_s \
  BETH_EXPAND_ITEM_bhgp_op_ar1_tanh_s \
  BETH_EXPAND_ITEM_bhgp_op_ar1_exp_s \
  BETH_EXPAND_ITEM_bhgp_op_ar1_relu_s \
  BETH_EXPAND_ITEM_bhgp_op_ar1_lrelu_s \
  BETH_EXPAND_ITEM_bhgp_op_ar1_adapt_s \
  BETH_EXPAND_ITEM_bhgp_op_ar1_identity_s \
  BETH_EXPAND_ITEM_bhgp_op_ar1_output_s \
  BETH_EXPAND_ITEM_bhgp_op_ar1_dimof_s \
  BETH_EXPAND_ITEM_bhgp_op_ar1_rand_s

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_op_ar2

#define TYPEOF_bhgp_op_ar2 3018437110
#define TYPEOF_bhgp_op_ar2_s 265753576
#define TYPEOF_bhgp_op_ar2_bmul_s 1004076733
#define BETH_EXPAND_ITEM_bhgp_op_ar2_bmul_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar2_bmul_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar2_bmul_s_get_symbol( const bhgp_op_ar2_bmul_s* o ){ return "**"; } \
  static inline sz_t bhgp_op_ar2_bmul_s_get_arity( const bhgp_op_ar2_bmul_s* o ){ return 2; } \
  static inline sz_t bhgp_op_ar2_bmul_s_get_priority( const bhgp_op_ar2_bmul_s* o ){ return 9; } \
  s2_t bhgp_op_ar2_bmul_s_solve( const bhgp_op_ar2_bmul_s* o, bmath_hf3_s** r, bmath_hf3_s** a ); \
  static inline bmath_hf3_vm_op* bhgp_op_ar2_bmul_s_create_vm_op( const bhgp_op_ar2_bmul_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_bmul_s_create(); }
#define TYPEOF_bhgp_op_ar2_bmul_htp_s 3214915778
#define BETH_EXPAND_ITEM_bhgp_op_ar2_bmul_htp_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar2_bmul_htp_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar2_bmul_htp_s_get_symbol( const bhgp_op_ar2_bmul_htp_s* o ){ return "*^"; } \
  static inline sz_t bhgp_op_ar2_bmul_htp_s_get_arity( const bhgp_op_ar2_bmul_htp_s* o ){ return 2; } \
  static inline sz_t bhgp_op_ar2_bmul_htp_s_get_priority( const bhgp_op_ar2_bmul_htp_s* o ){ return 9; } \
  s2_t bhgp_op_ar2_bmul_htp_s_solve( const bhgp_op_ar2_bmul_htp_s* o, bmath_hf3_s** r, bmath_hf3_s** a ); \
  static inline bmath_hf3_vm_op* bhgp_op_ar2_bmul_htp_s_create_vm_op( const bhgp_op_ar2_bmul_htp_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_bmul_htp_s_create(); }
#define TYPEOF_bhgp_op_ar2_htp_bmul_s 4116333564
#define BETH_EXPAND_ITEM_bhgp_op_ar2_htp_bmul_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar2_htp_bmul_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar2_htp_bmul_s_get_symbol( const bhgp_op_ar2_htp_bmul_s* o ){ return "^*"; } \
  static inline sz_t bhgp_op_ar2_htp_bmul_s_get_arity( const bhgp_op_ar2_htp_bmul_s* o ){ return 2; } \
  static inline sz_t bhgp_op_ar2_htp_bmul_s_get_priority( const bhgp_op_ar2_htp_bmul_s* o ){ return 9; } \
  s2_t bhgp_op_ar2_htp_bmul_s_solve( const bhgp_op_ar2_htp_bmul_s* o, bmath_hf3_s** r, bmath_hf3_s** a ); \
  static inline bmath_hf3_vm_op* bhgp_op_ar2_htp_bmul_s_create_vm_op( const bhgp_op_ar2_htp_bmul_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_htp_bmul_s_create(); }
#define TYPEOF_bhgp_op_ar2_htp_bmul_htp_s 2334549323
#define BETH_EXPAND_ITEM_bhgp_op_ar2_htp_bmul_htp_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar2_htp_bmul_htp_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar2_htp_bmul_htp_s_get_symbol( const bhgp_op_ar2_htp_bmul_htp_s* o ){ return "^*^"; } \
  static inline sz_t bhgp_op_ar2_htp_bmul_htp_s_get_arity( const bhgp_op_ar2_htp_bmul_htp_s* o ){ return 2; } \
  static inline sz_t bhgp_op_ar2_htp_bmul_htp_s_get_priority( const bhgp_op_ar2_htp_bmul_htp_s* o ){ return 9; } \
  s2_t bhgp_op_ar2_htp_bmul_htp_s_solve( const bhgp_op_ar2_htp_bmul_htp_s* o, bmath_hf3_s** r, bmath_hf3_s** a ); \
  static inline bmath_hf3_vm_op* bhgp_op_ar2_htp_bmul_htp_s_create_vm_op( const bhgp_op_ar2_htp_bmul_htp_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_htp_bmul_htp_s_create(); }
#define TYPEOF_bhgp_op_ar2_mul_s 249885309
#define BETH_EXPAND_ITEM_bhgp_op_ar2_mul_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar2_mul_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar2_mul_s_get_symbol( const bhgp_op_ar2_mul_s* o ){ return "*"; } \
  static inline sz_t bhgp_op_ar2_mul_s_get_arity( const bhgp_op_ar2_mul_s* o ){ return 2; } \
  static inline sz_t bhgp_op_ar2_mul_s_get_priority( const bhgp_op_ar2_mul_s* o ){ return 9; } \
  s2_t bhgp_op_ar2_mul_s_solve( const bhgp_op_ar2_mul_s* o, bmath_hf3_s** r, bmath_hf3_s** a ); \
  bmath_hf3_vm_op* bhgp_op_ar2_mul_s_create_vm_op( const bhgp_op_ar2_mul_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r );
#define TYPEOF_bhgp_op_ar2_plus_s 33301305
#define BETH_EXPAND_ITEM_bhgp_op_ar2_plus_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar2_plus_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar2_plus_s_get_symbol( const bhgp_op_ar2_plus_s* o ){ return "+"; } \
  static inline sz_t bhgp_op_ar2_plus_s_get_arity( const bhgp_op_ar2_plus_s* o ){ return 2; } \
  static inline sz_t bhgp_op_ar2_plus_s_get_priority( const bhgp_op_ar2_plus_s* o ){ return 8; } \
  s2_t bhgp_op_ar2_plus_s_solve( const bhgp_op_ar2_plus_s* o, bmath_hf3_s** r, bmath_hf3_s** a ); \
  static inline bmath_hf3_vm_op* bhgp_op_ar2_plus_s_create_vm_op( const bhgp_op_ar2_plus_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_add_s_create(); }
#define TYPEOF_bhgp_op_ar2_minus_s 2260174075
#define BETH_EXPAND_ITEM_bhgp_op_ar2_minus_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar2_minus_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar2_minus_s_get_symbol( const bhgp_op_ar2_minus_s* o ){ return "-"; } \
  static inline sz_t bhgp_op_ar2_minus_s_get_arity( const bhgp_op_ar2_minus_s* o ){ return 2; } \
  static inline sz_t bhgp_op_ar2_minus_s_get_priority( const bhgp_op_ar2_minus_s* o ){ return 8; } \
  s2_t bhgp_op_ar2_minus_s_solve( const bhgp_op_ar2_minus_s* o, bmath_hf3_s** r, bmath_hf3_s** a ); \
  static inline bmath_hf3_vm_op* bhgp_op_ar2_minus_s_create_vm_op( const bhgp_op_ar2_minus_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ){ return ( bmath_hf3_vm_op* )bmath_hf3_vm_op_sub_s_create(); }
#define TYPEOF_bhgp_op_ar2_equal_s 741032411
#define BETH_EXPAND_ITEM_bhgp_op_ar2_equal_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar2_equal_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar2_equal_s_get_symbol( const bhgp_op_ar2_equal_s* o ){ return "=="; } \
  static inline sz_t bhgp_op_ar2_equal_s_get_arity( const bhgp_op_ar2_equal_s* o ){ return 2; } \
  static inline sz_t bhgp_op_ar2_equal_s_get_priority( const bhgp_op_ar2_equal_s* o ){ return 6; } \
  s2_t bhgp_op_ar2_equal_s_solve( const bhgp_op_ar2_equal_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define TYPEOF_bhgp_op_ar2_larger_s 4243160446
#define BETH_EXPAND_ITEM_bhgp_op_ar2_larger_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar2_larger_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar2_larger_s_get_symbol( const bhgp_op_ar2_larger_s* o ){ return ">"; } \
  static inline sz_t bhgp_op_ar2_larger_s_get_arity( const bhgp_op_ar2_larger_s* o ){ return 2; } \
  static inline sz_t bhgp_op_ar2_larger_s_get_priority( const bhgp_op_ar2_larger_s* o ){ return 6; } \
  s2_t bhgp_op_ar2_larger_s_solve( const bhgp_op_ar2_larger_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define TYPEOF_bhgp_op_ar2_smaller_s 263585391
#define BETH_EXPAND_ITEM_bhgp_op_ar2_smaller_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar2_smaller_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar2_smaller_s_get_symbol( const bhgp_op_ar2_smaller_s* o ){ return "<"; } \
  static inline sz_t bhgp_op_ar2_smaller_s_get_arity( const bhgp_op_ar2_smaller_s* o ){ return 2; } \
  static inline sz_t bhgp_op_ar2_smaller_s_get_priority( const bhgp_op_ar2_smaller_s* o ){ return 6; } \
  s2_t bhgp_op_ar2_smaller_s_solve( const bhgp_op_ar2_smaller_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define TYPEOF_bhgp_op_ar2_larger_equal_s 900430357
#define BETH_EXPAND_ITEM_bhgp_op_ar2_larger_equal_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar2_larger_equal_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar2_larger_equal_s_get_symbol( const bhgp_op_ar2_larger_equal_s* o ){ return ">="; } \
  static inline sz_t bhgp_op_ar2_larger_equal_s_get_arity( const bhgp_op_ar2_larger_equal_s* o ){ return 2; } \
  static inline sz_t bhgp_op_ar2_larger_equal_s_get_priority( const bhgp_op_ar2_larger_equal_s* o ){ return 6; } \
  s2_t bhgp_op_ar2_larger_equal_s_solve( const bhgp_op_ar2_larger_equal_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define TYPEOF_bhgp_op_ar2_smaller_equal_s 3170828148
#define BETH_EXPAND_ITEM_bhgp_op_ar2_smaller_equal_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar2_smaller_equal_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar2_smaller_equal_s_get_symbol( const bhgp_op_ar2_smaller_equal_s* o ){ return "<="; } \
  static inline sz_t bhgp_op_ar2_smaller_equal_s_get_arity( const bhgp_op_ar2_smaller_equal_s* o ){ return 2; } \
  static inline sz_t bhgp_op_ar2_smaller_equal_s_get_priority( const bhgp_op_ar2_smaller_equal_s* o ){ return 6; } \
  s2_t bhgp_op_ar2_smaller_equal_s_solve( const bhgp_op_ar2_smaller_equal_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define TYPEOF_bhgp_op_ar2_logic_and_s 25252547
#define BETH_EXPAND_ITEM_bhgp_op_ar2_logic_and_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar2_logic_and_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar2_logic_and_s_get_symbol( const bhgp_op_ar2_logic_and_s* o ){ return "&"; } \
  static inline sz_t bhgp_op_ar2_logic_and_s_get_arity( const bhgp_op_ar2_logic_and_s* o ){ return 2; } \
  static inline sz_t bhgp_op_ar2_logic_and_s_get_priority( const bhgp_op_ar2_logic_and_s* o ){ return 6; } \
  s2_t bhgp_op_ar2_logic_and_s_solve( const bhgp_op_ar2_logic_and_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define TYPEOF_bhgp_op_ar2_logic_or_s 3242680351
#define BETH_EXPAND_ITEM_bhgp_op_ar2_logic_or_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar2_logic_or_s ) \
    {aware_t _;}; \
  static inline sc_t bhgp_op_ar2_logic_or_s_get_symbol( const bhgp_op_ar2_logic_or_s* o ){ return "|"; } \
  static inline sz_t bhgp_op_ar2_logic_or_s_get_arity( const bhgp_op_ar2_logic_or_s* o ){ return 2; } \
  static inline sz_t bhgp_op_ar2_logic_or_s_get_priority( const bhgp_op_ar2_logic_or_s* o ){ return 6; } \
  s2_t bhgp_op_ar2_logic_or_s_solve( const bhgp_op_ar2_logic_or_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define TYPEOF_bhgp_op_ar2_index_s 1073651755
#define BETH_EXPAND_ITEM_bhgp_op_ar2_index_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar2_index_s ) \
    {aware_t _;}; \
  static inline sz_t bhgp_op_ar2_index_s_get_arity( const bhgp_op_ar2_index_s* o ){ return  2; } \
  static inline sz_t bhgp_op_ar2_index_s_get_priority( const bhgp_op_ar2_index_s* o ){ return 20; } \
  s2_t bhgp_op_ar2_index_s_solve( const bhgp_op_ar2_index_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define TYPEOF_bhgp_op_ar2_inc_order_s 1353755116
#define BETH_EXPAND_ITEM_bhgp_op_ar2_inc_order_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar2_inc_order_s ) \
    {aware_t _;}; \
  static inline sz_t bhgp_op_ar2_inc_order_s_get_arity( const bhgp_op_ar2_inc_order_s* o ){ return  2; } \
  static inline sz_t bhgp_op_ar2_inc_order_s_get_priority( const bhgp_op_ar2_inc_order_s* o ){ return 20; } \
  s2_t bhgp_op_ar2_inc_order_s_solve( const bhgp_op_ar2_inc_order_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define BETH_EXPAND_GROUP_bhgp_op_ar2 \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2 ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2_bmul_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2_bmul_htp_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2_htp_bmul_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2_htp_bmul_htp_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2_mul_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2_plus_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2_minus_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2_equal_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2_larger_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2_smaller_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2_larger_equal_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2_smaller_equal_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2_logic_and_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2_logic_or_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2_index_s ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar2_inc_order_s ); \
  typedef bmath_hf3_vm_op* (*bhgp_op_ar2_create_vm_op)( const bhgp_op_ar2* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ); \
  BCORE_DECLARE_SPECT( bhgp_op_ar2 ) \
  { \
      bcore_spect_header_s header; \
      bhgp_op_ar2_create_vm_op create_vm_op; \
  }; \
  static inline bhgp_op_ar2* bhgp_op_ar2_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bhgp_op_ar2, t ); return ( bhgp_op_ar2* )bcore_inst_t_create( t ); } \
  static inline bl_t bhgp_op_ar2_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bhgp_op_ar2 ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bhgp_op_ar2 ) \
  static inline bl_t bhgp_op_ar2_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bhgp_op_ar2 ); } \
  static inline bmath_hf3_vm_op* bhgp_op_ar2_a_create_vm_op( const bhgp_op_ar2* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ) { return bhgp_op_ar2_s_get_aware( o )->create_vm_op( o, a, b, r ); } \
  static inline bl_t bhgp_op_ar2_a_defines_create_vm_op( const bhgp_op_ar2* o ) { return true; } \
  static inline bmath_hf3_vm_op* bhgp_op_ar2_create_vm_op__( const bhgp_op_ar2* o, const bmath_hf3_s* a, const bmath_hf3_s* b, const bmath_hf3_s* r ) { return NULL; } \
  BETH_EXPAND_ITEM_bhgp_op_ar2_bmul_s \
  BETH_EXPAND_ITEM_bhgp_op_ar2_bmul_htp_s \
  BETH_EXPAND_ITEM_bhgp_op_ar2_htp_bmul_s \
  BETH_EXPAND_ITEM_bhgp_op_ar2_htp_bmul_htp_s \
  BETH_EXPAND_ITEM_bhgp_op_ar2_mul_s \
  BETH_EXPAND_ITEM_bhgp_op_ar2_plus_s \
  BETH_EXPAND_ITEM_bhgp_op_ar2_minus_s \
  BETH_EXPAND_ITEM_bhgp_op_ar2_equal_s \
  BETH_EXPAND_ITEM_bhgp_op_ar2_larger_s \
  BETH_EXPAND_ITEM_bhgp_op_ar2_smaller_s \
  BETH_EXPAND_ITEM_bhgp_op_ar2_larger_equal_s \
  BETH_EXPAND_ITEM_bhgp_op_ar2_smaller_equal_s \
  BETH_EXPAND_ITEM_bhgp_op_ar2_logic_and_s \
  BETH_EXPAND_ITEM_bhgp_op_ar2_logic_or_s \
  BETH_EXPAND_ITEM_bhgp_op_ar2_index_s \
  BETH_EXPAND_ITEM_bhgp_op_ar2_inc_order_s

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_op_ar3

#define TYPEOF_bhgp_op_ar3 3035214729
#define TYPEOF_bhgp_op_ar3_s 1849311043
#define TYPEOF_bhgp_op_ar3_branch_s 3131582932
#define BETH_EXPAND_ITEM_bhgp_op_ar3_branch_s \
  BCORE_DECLARE_OBJECT( bhgp_op_ar3_branch_s ) \
    {aware_t _;}; \
  static inline sz_t bhgp_op_ar3_branch_s_get_arity( const bhgp_op_ar3_branch_s* o ){ return  3; } \
  static inline sz_t bhgp_op_ar3_branch_s_get_priority( const bhgp_op_ar3_branch_s* o ){ return  5; } \
  s2_t bhgp_op_ar3_branch_s_solve( const bhgp_op_ar3_branch_s* o, bmath_hf3_s** r, bmath_hf3_s** a );
#define BETH_EXPAND_GROUP_bhgp_op_ar3 \
  BCORE_FORWARD_OBJECT( bhgp_op_ar3 ); \
  BCORE_FORWARD_OBJECT( bhgp_op_ar3_branch_s ); \
  BETH_EXPAND_ITEM_bhgp_op_ar3_branch_s

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_sem

#define TYPEOF_bhgp_sem 499059072
#define TYPEOF_bhgp_sem_s 3704489050
#define TYPEOF_bhgp_sem_link_s 2891861275
#define BETH_EXPAND_ITEM_bhgp_sem_link_s \
  BCORE_DECLARE_OBJECT( bhgp_sem_link_s ) \
    {aware_t _;tp_t name;bhgp_sem_link_s* up;bhgp_sem_link_s* dn;vd_t cell;bl_t exit;}; \
  tp_t bhgp_sem_link_s_get_name( const bhgp_sem_link_s* o );
#define TYPEOF_bhgp_sem_links_s 132687704
#define BETH_EXPAND_ITEM_bhgp_sem_links_s \
  BCORE_DECLARE_OBJECT( bhgp_sem_links_s ) \
    {aware_t _;BCORE_ARRAY_DYN_LINK_STATIC_S( bhgp_sem_link_s, );}; \
  bhgp_sem_link_s* bhgp_sem_links_s_get_link_by_name( bhgp_sem_links_s* o, tp_t name ); \
  bl_t bhgp_sem_links_s_name_exists( const bhgp_sem_links_s* o, tp_t name ); \
  bhgp_sem_link_s* bhgp_sem_links_s_get_link_by_up( bhgp_sem_links_s* o, bhgp_sem_link_s* up ); \
  bhgp_sem_link_s* bhgp_sem_links_s_get_link_by_dn( bhgp_sem_links_s* o, bhgp_sem_link_s* dn ); \
  sz_t bhgp_sem_links_s_get_index_by_link( bhgp_sem_links_s* o, bhgp_sem_link_s* link ); \
  sz_t bhgp_sem_links_s_count_open( const bhgp_sem_links_s* o ); \
  static inline void bhgp_sem_links_s_set_space( bhgp_sem_links_s* o, sz_t size ) { bcore_array_t_set_space( TYPEOF_bhgp_sem_links_s, ( bcore_array* )o, size ); } \
  static inline void bhgp_sem_links_s_set_size( bhgp_sem_links_s* o, sz_t size ) { bcore_array_t_set_size( TYPEOF_bhgp_sem_links_s, ( bcore_array* )o, size ); } \
  static inline void bhgp_sem_links_s_clear( bhgp_sem_links_s* o ) { bcore_array_t_set_space( TYPEOF_bhgp_sem_links_s, ( bcore_array* )o, 0 ); } \
  static inline bhgp_sem_link_s* bhgp_sem_links_s_push_c( bhgp_sem_links_s* o, const bhgp_sem_link_s* v ) { bcore_array_t_push( TYPEOF_bhgp_sem_links_s, ( bcore_array* )o, sr_twc( TYPEOF_bhgp_sem_link_s, v ) ); return o->data[ o->size - 1 ]; } \
  static inline bhgp_sem_link_s* bhgp_sem_links_s_push_d( bhgp_sem_links_s* o,       bhgp_sem_link_s* v ) { bcore_array_t_push( TYPEOF_bhgp_sem_links_s, ( bcore_array* )o, sr_tsd( TYPEOF_bhgp_sem_link_s, v ) ); return o->data[ o->size - 1 ]; } \
  static inline bhgp_sem_link_s* bhgp_sem_links_s_push( bhgp_sem_links_s* o ) \
  { \
      bcore_array_t_push( TYPEOF_bhgp_sem_links_s, ( bcore_array* )o, sr_t_create( TYPEOF_bhgp_sem_link_s ) ); \
      return o->data[ o->size - 1 ]; \
  }
#define TYPEOF_bhgp_sem_body_s 2012699279
#define BETH_EXPAND_ITEM_bhgp_sem_body_s \
  BCORE_DECLARE_OBJECT( bhgp_sem_body_s ) \
    {aware_t _;BCORE_ARRAY_DYN_LINK_STATIC_S( bhgp_sem, );}; \
  bl_t bhgp_sem_body_s_name_exists( const bhgp_sem_body_s* o, tp_t name ); \
  bhgp_sem* bhgp_sem_body_s_get_sem_by_name( bhgp_sem_body_s* o, tp_t name ); \
  static inline void bhgp_sem_body_s_set_space( bhgp_sem_body_s* o, sz_t size ) { bcore_array_t_set_space( TYPEOF_bhgp_sem_body_s, ( bcore_array* )o, size ); } \
  static inline void bhgp_sem_body_s_set_size( bhgp_sem_body_s* o, sz_t size ) { bcore_array_t_set_size( TYPEOF_bhgp_sem_body_s, ( bcore_array* )o, size ); } \
  static inline void bhgp_sem_body_s_clear( bhgp_sem_body_s* o ) { bcore_array_t_set_space( TYPEOF_bhgp_sem_body_s, ( bcore_array* )o, 0 ); } \
  static inline bhgp_sem* bhgp_sem_body_s_push_c( bhgp_sem_body_s* o, const bhgp_sem* v ) { bcore_array_t_push( TYPEOF_bhgp_sem_body_s, ( bcore_array* )o, sr_awc( v ) ); return o->data[ o->size - 1 ]; } \
  static inline bhgp_sem* bhgp_sem_body_s_push_d( bhgp_sem_body_s* o,       bhgp_sem* v ) { bcore_array_t_push( TYPEOF_bhgp_sem_body_s, ( bcore_array* )o, sr_asd( v ) ); return o->data[ o->size - 1 ]; } \
  static inline bhgp_sem* bhgp_sem_body_s_push_t( bhgp_sem_body_s* o, tp_t t ) \
  { \
      bcore_trait_assert_satisfied_type( TYPEOF_bhgp_sem, t ); \
      bcore_array_t_push( TYPEOF_bhgp_sem_body_s, ( bcore_array* )o, sr_t_create( t ) ); \
      return o->data[ o->size - 1 ]; \
  }
#define TYPEOF_bhgp_sem_cell_s 3956336335
#define BETH_EXPAND_ITEM_bhgp_sem_cell_s \
  BCORE_DECLARE_OBJECT( bhgp_sem_cell_s ) \
    {aware_t _;tp_t name;bhgp_sem_links_s encs;bhgp_sem_links_s excs;bhgp_sem_body_s* body;bhgp_op* op;sz_t priority;bhgp_sem_cell_s* parent;bcore_source_point_s source_point;}; \
  tp_t bhgp_sem_cell_s_get_name( const bhgp_sem_cell_s* o ); \
  static inline sz_t bhgp_sem_cell_s_get_arity( const bhgp_sem_cell_s* o ){ return bhgp_sem_links_s_count_open(       &o->encs       ); } \
  static inline bhgp_sem_link_s* bhgp_sem_cell_s_get_enc_by_name( bhgp_sem_cell_s* o, tp_t name ){ return bhgp_sem_links_s_get_link_by_name( &o->encs, name ); } \
  static inline bhgp_sem_link_s* bhgp_sem_cell_s_get_exc_by_name( bhgp_sem_cell_s* o, tp_t name ){ return bhgp_sem_links_s_get_link_by_name( &o->excs, name ); } \
  static inline bhgp_sem_link_s* bhgp_sem_cell_s_get_enc_by_open( bhgp_sem_cell_s* o ){ return bhgp_sem_links_s_get_link_by_up(   &o->encs, NULL ); } \
  static inline bhgp_sem_link_s* bhgp_sem_cell_s_get_enc_by_dn( bhgp_sem_cell_s* o, bhgp_sem_link_s* dn ){ return bhgp_sem_links_s_get_link_by_dn(   &o->encs, dn   ); } \
  static inline sz_t bhgp_sem_cell_s_get_priority( const bhgp_sem_cell_s* o ){ return o->priority; } \
  bhgp_sem_cell_s* bhgp_sem_cell_s_get_cell_by_name( bhgp_sem_cell_s* o, tp_t name );
#define TYPEOF_bhgp_sem_stack_flag_s 1529791380
#define BETH_EXPAND_ITEM_bhgp_sem_stack_flag_s \
  BCORE_DECLARE_OBJECT( bhgp_sem_stack_flag_s ) \
    {aware_t _;};
#define BETH_EXPAND_GROUP_bhgp_sem \
  BCORE_FORWARD_OBJECT( bhgp_sem ); \
  BCORE_FORWARD_OBJECT( bhgp_sem_link_s ); \
  BCORE_FORWARD_OBJECT( bhgp_sem_links_s ); \
  BCORE_FORWARD_OBJECT( bhgp_sem_body_s ); \
  BCORE_FORWARD_OBJECT( bhgp_sem_cell_s ); \
  BCORE_FORWARD_OBJECT( bhgp_sem_stack_flag_s ); \
  typedef tp_t (*bhgp_sem_get_name)( const bhgp_sem* o ); \
  BCORE_DECLARE_SPECT( bhgp_sem ) \
  { \
      bcore_spect_header_s header; \
      bhgp_sem_get_name get_name; \
  }; \
  static inline bhgp_sem* bhgp_sem_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bhgp_sem, t ); return ( bhgp_sem* )bcore_inst_t_create( t ); } \
  static inline bl_t bhgp_sem_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bhgp_sem ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bhgp_sem ) \
  static inline bl_t bhgp_sem_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bhgp_sem ); } \
  static inline tp_t bhgp_sem_a_get_name( const bhgp_sem* o ) { return bhgp_sem_s_get_aware( o )->get_name( o ); } \
  static inline bl_t bhgp_sem_a_defines_get_name( const bhgp_sem* o ) { return true; } \
  static inline tp_t bhgp_sem_get_name__( const bhgp_sem* o ) { return 0; } \
  BETH_EXPAND_ITEM_bhgp_sem_link_s \
  BETH_EXPAND_ITEM_bhgp_sem_links_s \
  BETH_EXPAND_ITEM_bhgp_sem_body_s \
  BETH_EXPAND_ITEM_bhgp_sem_cell_s \
  BETH_EXPAND_ITEM_bhgp_sem_stack_flag_s

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_ctr

#define TYPEOF_bhgp_ctr 1654518744
#define TYPEOF_bhgp_ctr_s 451275330
#define TYPEOF_bhgp_ctr_node_s 1423864255
#define BETH_EXPAND_ITEM_bhgp_ctr_node_s \
  BCORE_DECLARE_OBJECT( bhgp_ctr_node_s ) \
    {aware_t _;sz_t id;bhgp_sem_cell_s* cell;bhgp_ctr_node_s* parent;BCORE_ARRAY_DYN_LINK_STATIC_S( bhgp_ctr_node_s, );}; \
  static inline void bhgp_ctr_node_s_set_space( bhgp_ctr_node_s* o, sz_t size ) { bcore_array_t_set_space( TYPEOF_bhgp_ctr_node_s, ( bcore_array* )o, size ); } \
  static inline void bhgp_ctr_node_s_set_size( bhgp_ctr_node_s* o, sz_t size ) { bcore_array_t_set_size( TYPEOF_bhgp_ctr_node_s, ( bcore_array* )o, size ); } \
  static inline void bhgp_ctr_node_s_clear( bhgp_ctr_node_s* o ) { bcore_array_t_set_space( TYPEOF_bhgp_ctr_node_s, ( bcore_array* )o, 0 ); } \
  static inline bhgp_ctr_node_s* bhgp_ctr_node_s_push_c( bhgp_ctr_node_s* o, const bhgp_ctr_node_s* v ) { bcore_array_t_push( TYPEOF_bhgp_ctr_node_s, ( bcore_array* )o, sr_twc( TYPEOF_bhgp_ctr_node_s, v ) ); return o->data[ o->size - 1 ]; } \
  static inline bhgp_ctr_node_s* bhgp_ctr_node_s_push_d( bhgp_ctr_node_s* o,       bhgp_ctr_node_s* v ) { bcore_array_t_push( TYPEOF_bhgp_ctr_node_s, ( bcore_array* )o, sr_tsd( TYPEOF_bhgp_ctr_node_s, v ) ); return o->data[ o->size - 1 ]; } \
  static inline bhgp_ctr_node_s* bhgp_ctr_node_s_push( bhgp_ctr_node_s* o ) \
  { \
      bcore_array_t_push( TYPEOF_bhgp_ctr_node_s, ( bcore_array* )o, sr_t_create( TYPEOF_bhgp_ctr_node_s ) ); \
      return o->data[ o->size - 1 ]; \
  }
#define TYPEOF_bhgp_ctr_tree_s 1158644215
#define BETH_EXPAND_ITEM_bhgp_ctr_tree_s \
  BCORE_DECLARE_OBJECT( bhgp_ctr_tree_s ) \
    {aware_t _;sz_t id_base;bhgp_ctr_node_s* root;};
#define BETH_EXPAND_GROUP_bhgp_ctr \
  BCORE_FORWARD_OBJECT( bhgp_ctr ); \
  BCORE_FORWARD_OBJECT( bhgp_ctr_node_s ); \
  BCORE_FORWARD_OBJECT( bhgp_ctr_tree_s ); \
  BETH_EXPAND_ITEM_bhgp_ctr_node_s \
  BETH_EXPAND_ITEM_bhgp_ctr_tree_s

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_net

#define TYPEOF_bhgp_net 2825251392
#define TYPEOF_bhgp_net_s 43889946
#define TYPEOF_bhgp_net_link_s 1764715739
#define BETH_EXPAND_ITEM_bhgp_net_link_s \
  BCORE_DECLARE_OBJECT( bhgp_net_link_s ) \
    {aware_t _;vd_t node;};
#define TYPEOF_bhgp_net_links_s 2274837016
#define BETH_EXPAND_ITEM_bhgp_net_links_s \
  BCORE_DECLARE_OBJECT( bhgp_net_links_s ) \
    {aware_t _;BCORE_ARRAY_DYN_LINK_STATIC_S( bhgp_net_link_s, );}; \
  static inline void bhgp_net_links_s_set_space( bhgp_net_links_s* o, sz_t size ) { bcore_array_t_set_space( TYPEOF_bhgp_net_links_s, ( bcore_array* )o, size ); } \
  static inline void bhgp_net_links_s_set_size( bhgp_net_links_s* o, sz_t size ) { bcore_array_t_set_size( TYPEOF_bhgp_net_links_s, ( bcore_array* )o, size ); } \
  static inline void bhgp_net_links_s_clear( bhgp_net_links_s* o ) { bcore_array_t_set_space( TYPEOF_bhgp_net_links_s, ( bcore_array* )o, 0 ); } \
  static inline bhgp_net_link_s* bhgp_net_links_s_push_c( bhgp_net_links_s* o, const bhgp_net_link_s* v ) { bcore_array_t_push( TYPEOF_bhgp_net_links_s, ( bcore_array* )o, sr_twc( TYPEOF_bhgp_net_link_s, v ) ); return o->data[ o->size - 1 ]; } \
  static inline bhgp_net_link_s* bhgp_net_links_s_push_d( bhgp_net_links_s* o,       bhgp_net_link_s* v ) { bcore_array_t_push( TYPEOF_bhgp_net_links_s, ( bcore_array* )o, sr_tsd( TYPEOF_bhgp_net_link_s, v ) ); return o->data[ o->size - 1 ]; } \
  static inline bhgp_net_link_s* bhgp_net_links_s_push( bhgp_net_links_s* o ) \
  { \
      bcore_array_t_push( TYPEOF_bhgp_net_links_s, ( bcore_array* )o, sr_t_create( TYPEOF_bhgp_net_link_s ) ); \
      return o->data[ o->size - 1 ]; \
  }
#define TYPEOF_bhgp_net_node_s 257682039
#define BETH_EXPAND_ITEM_bhgp_net_node_s \
  BCORE_DECLARE_OBJECT( bhgp_net_node_s ) \
    {aware_t _;bhgp_net_links_s upls;bhgp_net_links_s dnls;sz_t id;bl_t flag;tp_t name;bhgp_op* op;bmath_hf3_s* h;bcore_source_point_s* source_point;}; \
  void bhgp_net_node_s_solve( bhgp_net_node_s* o );
#define TYPEOF_bhgp_net_nodes_s 479725708
#define BETH_EXPAND_ITEM_bhgp_net_nodes_s \
  BCORE_DECLARE_OBJECT( bhgp_net_nodes_s ) \
    {aware_t _;BCORE_ARRAY_DYN_LINK_STATIC_S( bhgp_net_node_s, );}; \
  bhgp_net_node_s* bhgp_net_nodes_s_get_by_id( bhgp_net_nodes_s* o, sz_t id ); \
  static inline void bhgp_net_nodes_s_set_space( bhgp_net_nodes_s* o, sz_t size ) { bcore_array_t_set_space( TYPEOF_bhgp_net_nodes_s, ( bcore_array* )o, size ); } \
  static inline void bhgp_net_nodes_s_set_size( bhgp_net_nodes_s* o, sz_t size ) { bcore_array_t_set_size( TYPEOF_bhgp_net_nodes_s, ( bcore_array* )o, size ); } \
  static inline void bhgp_net_nodes_s_clear( bhgp_net_nodes_s* o ) { bcore_array_t_set_space( TYPEOF_bhgp_net_nodes_s, ( bcore_array* )o, 0 ); } \
  static inline bhgp_net_node_s* bhgp_net_nodes_s_push_c( bhgp_net_nodes_s* o, const bhgp_net_node_s* v ) { bcore_array_t_push( TYPEOF_bhgp_net_nodes_s, ( bcore_array* )o, sr_twc( TYPEOF_bhgp_net_node_s, v ) ); return o->data[ o->size - 1 ]; } \
  static inline bhgp_net_node_s* bhgp_net_nodes_s_push_d( bhgp_net_nodes_s* o,       bhgp_net_node_s* v ) { bcore_array_t_push( TYPEOF_bhgp_net_nodes_s, ( bcore_array* )o, sr_tsd( TYPEOF_bhgp_net_node_s, v ) ); return o->data[ o->size - 1 ]; } \
  static inline bhgp_net_node_s* bhgp_net_nodes_s_push( bhgp_net_nodes_s* o ) \
  { \
      bcore_array_t_push( TYPEOF_bhgp_net_nodes_s, ( bcore_array* )o, sr_t_create( TYPEOF_bhgp_net_node_s ) ); \
      return o->data[ o->size - 1 ]; \
  }
#define TYPEOF_bhgp_net_cell_s 4037555599
#define BETH_EXPAND_ITEM_bhgp_net_cell_s \
  BCORE_DECLARE_OBJECT( bhgp_net_cell_s ) \
    {aware_t _;sz_t max_depth;bhgp_net_nodes_s body;bhgp_net_nodes_s encs;bhgp_net_nodes_s excs;}; \
  bl_t bhgp_net_cell_s_is_consistent( const bhgp_net_cell_s* o ); \
  void bhgp_net_cell_s_normalize( bhgp_net_cell_s* o ); \
  void bhgp_net_cell_s_clear_flags( bhgp_net_cell_s* o ); \
  void bhgp_net_cell_s_solve( bhgp_net_cell_s* o ); \
  void bhgp_net_cell_s_clear_downlinks( bhgp_net_cell_s* o ); \
  void bhgp_net_cell_s_set_downlinks( bhgp_net_cell_s* o ); \
  void bhgp_net_cell_s_copy_x( bhgp_net_cell_s* o ); \
  static inline void bhgp_net_cell_s_mutated( bhgp_net_cell_s* o ){ ERR_fa( "Cannot reconstitute after via-mutation." ); }
#define BETH_EXPAND_GROUP_bhgp_net \
  BCORE_FORWARD_OBJECT( bhgp_net ); \
  BCORE_FORWARD_OBJECT( bhgp_net_link_s ); \
  BCORE_FORWARD_OBJECT( bhgp_net_links_s ); \
  BCORE_FORWARD_OBJECT( bhgp_net_node_s ); \
  BCORE_FORWARD_OBJECT( bhgp_net_nodes_s ); \
  BCORE_FORWARD_OBJECT( bhgp_net_cell_s ); \
  BETH_EXPAND_ITEM_bhgp_net_link_s \
  BETH_EXPAND_ITEM_bhgp_net_links_s \
  BETH_EXPAND_ITEM_bhgp_net_node_s \
  BETH_EXPAND_ITEM_bhgp_net_nodes_s \
  BETH_EXPAND_ITEM_bhgp_net_cell_s

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_vm

#define TYPEOF_bhgp_vm 3743952100
#define TYPEOF_bhgp_vm_s 2034301526
#define TYPEOF_bhgp_vm_adaptive_s 1783547425
#define BETH_EXPAND_ITEM_bhgp_vm_adaptive_s \
  BCORE_DECLARE_OBJECT( bhgp_vm_adaptive_s ) \
    {aware_t _;st_s frame;st_s src;bmath_hf3_vm_frame_s vm;badapt_dynamics_std_s dynamics;sz_t in_size;sz_t out_size;sz_t in_index;sz_t out_index;}; \
  static inline sz_t bhgp_vm_adaptive_s_get_in_size( const bhgp_vm_adaptive_s* o ){ return o->in_size;  } \
  static inline sz_t bhgp_vm_adaptive_s_get_out_size( const bhgp_vm_adaptive_s* o ){ return o->out_size; } \
  static inline void bhgp_vm_adaptive_s_get_dynamics_std( const bhgp_vm_adaptive_s* o, badapt_dynamics_std_s* dynamics ){ badapt_dynamics_std_s_copy( dynamics, &o->dynamics ); } \
  static inline void bhgp_vm_adaptive_s_set_dynamics_std( bhgp_vm_adaptive_s* o, const badapt_dynamics_std_s* dynamics ){ badapt_dynamics_std_s_copy( &o->dynamics, dynamics ); } \
  void bhgp_vm_adaptive_s_minfer( bhgp_vm_adaptive_s* o, const bmath_vf3_s* in, bmath_vf3_s* out ); \
  static inline void bhgp_vm_adaptive_s_bgrad_adapt( bhgp_vm_adaptive_s* o, bmath_vf3_s* grad_in, const bmath_vf3_s* grad_out ){}
#define TYPEOF_bhgp_vm_builder_s 2981332614
#define BETH_EXPAND_ITEM_bhgp_vm_builder_s \
  BCORE_DECLARE_OBJECT( bhgp_vm_builder_s ) \
    {aware_t _;st_s frame;st_s src;sz_t in_size;sz_t out_size;badapt_dynamics_std_s dynamics;}; \
  static inline sz_t bhgp_vm_builder_s_get_in_size( const bhgp_vm_builder_s* o ){ return o->in_size; } \
  static inline void bhgp_vm_builder_s_set_in_size( bhgp_vm_builder_s* o, sz_t size ){ o->in_size = size; } \
  static inline sz_t bhgp_vm_builder_s_get_out_size( const bhgp_vm_builder_s* o ){ return o->out_size; } \
  static inline void bhgp_vm_builder_s_set_out_size( bhgp_vm_builder_s* o, sz_t size ){ o->out_size = size; } \
  badapt_adaptive* bhgp_vm_builder_s_build( const bhgp_vm_builder_s* o );
#define BETH_EXPAND_GROUP_bhgp_vm \
  BCORE_FORWARD_OBJECT( bhgp_vm ); \
  BCORE_FORWARD_OBJECT( bhgp_vm_adaptive_s ); \
  BCORE_FORWARD_OBJECT( bhgp_vm_builder_s ); \
  BETH_EXPAND_ITEM_bhgp_vm_adaptive_s \
  BETH_EXPAND_ITEM_bhgp_vm_builder_s

/**********************************************************************************************************************/

vd_t badapt_dev_planted_signal_handler( const bcore_signal_s* o );

#endif // BADAPT_DEV_PLANTED_H
