/** This file was generated by the plant-compiler.
 *
 *  Copyright and License:
 *    Code generated by the beth-plant compiler inherits the copyright and license
 *    of the beth-plant source code, which is contained in following files:
 *    badapt_dev_problem.h
 *    badapt_dev_ern.h
 *    badapt_dev_lstm.h
 *    bsym.h
 *    bhgp.h
 *
 */

#include "badapt_dev_planted.h"
#include "bcore_spect.h"
#include "bcore_spect_inst.h"
#include "bcore_sr.h"
#include "bcore_const_manager.h"


/**********************************************************************************************************************/
// source: badapt_dev_problem
#include "badapt_dev_problem.h"

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_dev_problem_objects

BCORE_DEFINE_OBJECT_INST_P( badapt_problem_recurrent_abc_s )
"badapt_supplier"
"{"
    "aware_t _;"
    "sz_t index = 0;"
    "u2_t rval = 1234;"
    "f3_t pos_tgt = 1.0;"
    "f3_t neg_tgt = 0.0;"
    "aware badapt_loss* preferred_loss = badapt_loss_l2_s;"
    "func ^:preferred_loss;"
    "func ^:get_in_size;"
    "func ^:get_out_size;"
    "func ^:fetch_sample_tio;"
    "func ^:fetch_sample_vio;"
"}";

BCORE_DEFINE_OBJECT_INST_P( badapt_problem_recurrent_kjv_s )
"badapt_supplier"
"{"
    "aware_t _;"
    "aware bcore_source => source;"
    "bcore_arr_sz_s => charmap;"
    "st_s => charset;"
    "u0_t t_last_char = 0;"
    "u0_t v_last_char = 0;"
    "u2_t rval = 1234;"
    "f3_t pos_tgt = 1.0;"
    "f3_t neg_tgt = 0.0;"
    "aware badapt_loss* preferred_loss = badapt_loss_l2_s;"
    "func ^:preferred_loss;"
    "func ^:get_in_size;"
    "func ^:get_out_size;"
    "func ^:fetch_sample_tio;"
    "func ^:fetch_sample_vio;"
"}";

BCORE_DEFINE_OBJECT_INST_P( badapt_problem_recurrent_text_s )
"aware badapt_supplier"
"{"
    "st_s text_file;"
    "st_s ignore_line_char;"
    "aware bcore_source => source;"
    "bcore_arr_sz_s => charmap;"
    "st_s => charset;"
    "u0_t t_last_char = 0;"
    "u0_t v_last_char = 0;"
    "u2_t rval = 1234;"
    "f3_t pos_tgt = 1.0;"
    "f3_t neg_tgt = 0.0;"
    "aware badapt_loss* preferred_loss = badapt_loss_l2_s;"
    "func ^:preferred_loss;"
    "func ^:get_in_size;"
    "func ^:get_out_size;"
    "func ^:fetch_sample_tio;"
    "func ^:fetch_sample_vio;"
"}";

BCORE_DEFINE_OBJECT_INST_P( badapt_guide_char_encode_s )
"badapt_guide"
"{"
    "aware_t _;"
    "aware badapt_guide => guide_default = badapt_guide_std_s;"
    "bcore_arr_sz_s -> charmap;"
    "st_s -> charset;"
    "f3_t pos_tgt = 1.0;"
    "f3_t neg_tgt = 0.0;"
    "st_s txt_trigger;"
    "sz_t txt_size = 128;"
    "f3_t heat = 0.3;"
    "func ^:callback;"
"}";

/**********************************************************************************************************************/
// source: badapt_dev_ern
#include "badapt_dev_ern.h"

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_dev_ern

/**********************************************************************************************************************/
// source: badapt_dev_lstm
#include "badapt_dev_lstm.h"

/**********************************************************************************************************************/
// source: bsym
#include "bsym.h"

//----------------------------------------------------------------------------------------------------------------------
// group: bsym

BCORE_DEFINE_OBJECT_INST_P( bsym_source_info_s )
"aware bcore_inst"
"{"
    "aware bcore_source -> source;"
    "sz_t index;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bsym_op

BCORE_DEFINE_SPECT( bsym, bsym_op )
"{"
    "bcore_spect_header_s header;"
    "feature aware bsym_op : trace_to_sink = bsym_op_trace_to_sink__;"
    "feature strict aware bsym_op : get_arity;"
    "feature aware bsym_op : get_priority = bsym_op_get_priority__;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bsym_op_ar0

BCORE_DEFINE_OBJECT_INST_P( bsym_op_ar0_holor_s )
"aware bsym_op_ar0"
"{"
    "tp_t type;"
    "bmath_hf3_s hf3;"
    "func bsym_op:get_arity;"
    "func bsym_op:trace_to_sink;"
    "func ^:compute_hf3;"
    "func ^:get_hf3_type;"
"}";

void bsym_op_ar0_holor_s_trace_to_sink( const bsym_op_ar0_holor_s* o, sz_t indent, bcore_sink* sink )
{
    bcore_sink_a_push_fa( sink, "(#<sc_t>)", ifnameof( o->type ) );
    bmath_hf3_s_to_sink( &o->hf3, sink );
}

bl_t bsym_op_ar0_holor_s_compute_hf3( const bsym_op_ar0_holor_s* o, bmath_hf3_s* r )
{
    bmath_hf3_s_copy( r, &o->hf3 ); return true;
}

tp_t bsym_op_ar0_holor_s_get_hf3_type( const bsym_op_ar0_holor_s* o )
{
    return o->type;
}

BCORE_DEFINE_SPECT( bsym_op, bsym_op_ar0 )
"{"
    "bcore_spect_header_s header;"
    "feature strict aware bsym_op_ar0 : compute_hf3;"
    "feature aware bsym_op_ar0 : create_vm_operator = bsym_op_ar0_create_vm_operator__;"
    "feature aware bsym_op_ar0 : get_hf3_type;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bsym_op_ar1

BCORE_DEFINE_OBJECT_INST_P( bsym_op_ar1_linear_s )
"aware bsym_op_ar1"
"{"
    "func bsym_op:get_arity;"
    "func ^:get_symbol;"
    "func ^:compute_hf3;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bsym_op_ar1_tanh_s )
"aware bsym_op_ar1"
"{"
    "func bsym_op:get_arity;"
    "func ^:get_symbol;"
    "func ^:compute_hf3;"
    "func ^:create_vm_operator;"
"}";

bl_t bsym_op_ar1_tanh_s_compute_hf3( const bsym_op_ar1_tanh_s* o, const bmath_hf3_s* a, bmath_hf3_s* r )
{
    bmath_hf3_s_copy_d_data( r, a );
    if( a->v_size > 0 )
    {
        bmath_hf3_s_fit_v_size( r );
        for( sz_t i = 0; i < a->v_size; i++ ) r->v_data[ i ] = tanh( a->v_data[ i ] );
    }
    return true;
}

BCORE_DEFINE_OBJECT_INST_P( bsym_op_ar1_dimof_s )
"aware bsym_op_ar1"
"{"
    "func bsym_op:get_arity;"
    "func ^:get_symbol;"
    "func ^:compute_hf3;"
"}";

bl_t bsym_op_ar1_dimof_s_compute_hf3( const bsym_op_ar1_dimof_s* o, const bmath_hf3_s* a, bmath_hf3_s* r )
{
    if( bmath_hf3_s_d_product( a ) == 0 ) return false;
    bmath_hf3_s_set_d_size( r, 0 );
    bmath_hf3_s_fit_v_size( r );
    if( a->d_size > 0 )
    {
        r->v_data[ 0 ] = a->d_data[ a->d_size - 1 ];
    }
    else
    {
        r->v_data[ 0 ] = 1;
    }
    return true;
}

BCORE_DEFINE_SPECT( bsym_op, bsym_op_ar1 )
"{"
    "bcore_spect_header_s header;"
    "feature strict aware bsym_op_ar1 : get_symbol;"
    "feature aware bsym_op_ar1 : compute_hf3;"
    "feature aware bsym_op_ar1 : create_vm_operator = bsym_op_ar1_create_vm_operator__;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bsym_op_ar2

BCORE_DEFINE_OBJECT_INST_P( bsym_op_ar2_bmul_s )
"aware bsym_op_ar2"
"{"
    "func bsym_op:get_arity;"
    "func bsym_op:get_priority;"
    "func ^:get_symbol;"
    "func ^:compute_hf3;"
    "func ^:create_vm_operator;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bsym_op_ar2_bmul_htp_s )
"aware bsym_op_ar2"
"{"
    "func bsym_op:get_arity;"
    "func bsym_op:get_priority;"
    "func ^:get_symbol;"
    "func ^:compute_hf3;"
    "func ^:create_vm_operator;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bsym_op_ar2_htp_bmul_s )
"aware bsym_op_ar2"
"{"
    "func bsym_op:get_arity;"
    "func bsym_op:get_priority;"
    "func ^:get_symbol;"
    "func ^:compute_hf3;"
    "func ^:create_vm_operator;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bsym_op_ar2_htp_bmul_htp_s )
"aware bsym_op_ar2"
"{"
    "func bsym_op:get_arity;"
    "func bsym_op:get_priority;"
    "func ^:get_symbol;"
    "func ^:compute_hf3;"
    "func ^:create_vm_operator;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bsym_op_ar2_mul_s )
"aware bsym_op_ar2"
"{"
    "func bsym_op:get_arity;"
    "func bsym_op:get_priority;"
    "func ^:get_symbol;"
    "func ^:compute_hf3;"
    "func ^:create_vm_operator;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bsym_op_ar2_plus_s )
"aware bsym_op_ar2"
"{"
    "func bsym_op:get_arity;"
    "func bsym_op:get_priority;"
    "func ^:get_symbol;"
    "func ^:compute_hf3;"
    "func ^:create_vm_operator;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bsym_op_ar2_minus_s )
"aware bsym_op_ar2"
"{"
    "func bsym_op:get_arity;"
    "func bsym_op:get_priority;"
    "func ^:get_symbol;"
    "func ^:compute_hf3;"
    "func ^:create_vm_operator;"
"}";

BCORE_DEFINE_SPECT( bsym_op, bsym_op_ar2 )
"{"
    "bcore_spect_header_s header;"
    "feature strict aware bsym_op_ar2 : get_symbol;"
    "feature aware bsym_op_ar2 : compute_hf3;"
    "feature aware bsym_op_ar2 : create_vm_operator = bsym_op_ar2_create_vm_operator__;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bsym_net

BCORE_DEFINE_OBJECT_INST_P( bsym_net_hresult_s )
"aware bsym_net"
"{"
    "bmath_hf3_s => hf3;"
    "tp_t name;"
    "tp_t type;"
    "sz_t vm_index = -1;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bsym_net_body_s )
"aware bcore_array"
"{"
    "aware bsym_net=> [];"
    "func bcore_inst_call:copy_x;"
"}";

void bsym_net_body_s_copy_x( bsym_net_body_s* o )
{
    for( sz_t i = 0; i < o->size; i++ ) bsym_net_a_set_body( o->data[ i ], o );
}

BCORE_DEFINE_OBJECT_INST_P( bsym_net_address_s )
"aware bcore_inst"
"{"
    "sz_t index;"
    "hidden vd_t body;"
    "func bsym_net:trace_get_node;"
    "func bsym_net:trace_to_sink;"
    "func bsym_net:trace_compute_hresult;"
    "func bsym_net:trace_clear_hresult;"
    "func bsym_net:trace_build_vm_proc;"
    "func bsym_net:get_net;"
"}";

bsym_net_node_s* bsym_net_address_s_trace_get_node( bsym_net_address_s* o )
{
    bsym_net* net = bsym_net_address_s_get_net( o );
    return net ? bsym_net_a_trace_get_node( net ) : NULL;
}

void bsym_net_address_s_trace_to_sink( const bsym_net_address_s* o, sz_t indent, bcore_sink* sink )
{
    bsym_net_node_s* node = bsym_net_address_s_trace_get_node( ( bsym_net_address_s* )o );
    if( node ) bsym_net_node_s_trace_to_sink( node, indent, sink );
}

bsym_net_hresult_s* bsym_net_address_s_trace_compute_hresult( bsym_net_address_s* o, bl_t force )
{
    bsym_net* net = bsym_net_address_s_get_net( o );
    return net ? bsym_net_a_trace_compute_hresult( net, force ) : NULL;
}

void bsym_net_address_s_trace_clear_hresult( bsym_net_address_s* o )
{
    bsym_net* net = bsym_net_address_s_get_net( o );
    if( net ) bsym_net_a_trace_clear_hresult( net );
}

void bsym_net_address_s_trace_build_vm_proc( bsym_net_address_s* o, bmath_hf3_vm_frame_s* vmf, tp_t proc_name )
{
    bsym_net* net = bsym_net_address_s_get_net( o );
    if( net ) bsym_net_a_trace_build_vm_proc( net, vmf, proc_name );
}

BCORE_DEFINE_OBJECT_INST_P( bsym_net_link_s )
"aware bsym_net"
"{"
    "tp_t name;"
    "bsym_net_address_s target;"
    "bsym_net_address_s root;"
    "bl_t flag;"
    "func ^:get_name;"
    "func ^:set_body;"
    "func ^:trace_get_node;"
    "func ^:trace_to_sink;"
    "func ^:trace_compute_hresult;"
    "func ^:trace_clear_hresult;"
    "func ^:trace_build_vm_proc;"
"}";

void bsym_net_link_s_set_body( bsym_net_link_s* o, bsym_net_body_s* body )
{
    if( o->target.body && o->target.body == o->root.body )
    {
        o->target.body = body;
    }
    o->root.body = body;
}

void bsym_net_link_s_trace_to_sink( const bsym_net_link_s* o, sz_t indent, bcore_sink* sink )
{
    bcore_sink_a_push_fa( sink, "(#<sc_t>) -> ", bsym_ifnameof( o->name ) );
    bsym_net_address_s_trace_to_sink( &o->target, indent, sink );
}

BCORE_DEFINE_OBJECT_INST_P( bsym_net_node_s )
"aware bcore_array"
"{"
    "tp_t name;"
    "bsym_net_address_s [] targets;"
    "bsym_net_address_s root;"
    "aware bsym_op* op;"
    "bsym_source_info_s source_info;"
    "bsym_net_hresult_s => hresult;"
    "private bsym_net_address_s -> new_root;"
    "func bsym_net:get_name;"
    "func bsym_net:set_body;"
    "func bsym_net:trace_get_node;"
    "func bsym_net:trace_to_sink;"
    "func bsym_net:trace_compute_hresult;"
    "func bsym_net:trace_clear_hresult;"
    "func bsym_net:trace_build_vm_proc;"
"}";

void bsym_net_node_s_set_body( bsym_net_node_s* o, bsym_net_body_s* body )
{
    for( sz_t i = 0; i < o->targets_size; i++ )
    {
        bsym_net_address_s* target = &o->targets_data[ i ];
        if( target->body && target->body == o->root.body )
        {
            target->body = body;
        }
    }
    o->root.body = body;
}

void bsym_net_node_s_trace_clear_hresult( bsym_net_node_s* o )
{
    bsym_net_hresult_s_detach( &o->hresult );
    for( sz_t i = 0; i < o->targets_size; i++ ) bsym_net_address_s_trace_clear_hresult( &o->targets_data[ i ] );
}

BCORE_DEFINE_SPECT( bsym, bsym_net )
"{"
    "bcore_spect_header_s header;"
    "feature aware bsym_net : trace_to_sink = bsym_net_trace_to_sink__;"
    "feature aware bsym_net : get_name = bsym_net_get_name__;"
    "feature aware bsym_net : set_body = bsym_net_set_body__;"
    "feature aware bsym_net : trace_get_node = bsym_net_trace_get_node__;"
    "feature aware bsym_net : trace_compute_hresult = bsym_net_trace_compute_hresult__;"
    "feature aware bsym_net : trace_clear_hresult = bsym_net_trace_clear_hresult__;"
    "feature aware bsym_net : trace_build_vm_proc = bsym_net_trace_build_vm_proc__;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bsym_sem

BCORE_DEFINE_OBJECT_INST_P( bsym_sem_graph_s )
"aware bsym_sem"
"{"
    "tp_t name;"
    "sz_t args_in;"
    "sz_t args_out;"
    "bsym_net_body_s body;"
    "bsym_sem_graph_base_s => graph_base;"
    "hidden bcore_arr_st_s -> arr_symbol_op2;"
    "bsym_source_info_s source_info;"
    "sz_t priority = 10;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bsym_sem_graph_base_s )
"aware bcore_array"
"{"
    "private bsym_sem_graph_base_s -> parent;"
    "aware bsym_sem=> [];"
"}";

BCORE_DEFINE_OBJECT_INST_P( bsym_sem_stack_flag_s )
"aware bsym_sem"
"{"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bsym_vm

BCORE_DEFINE_OBJECT_INST_P( bsym_vm_adaptive_s )
"aware badapt_adaptive"
"{"
    "st_s holograph_file;"
    "bmath_hf3_vm_frame_s vm;"
    "badapt_dynamics_std_s dynamics;"
    "sz_t in_size;"
    "sz_t out_size;"
    "sz_t in_index;"
    "sz_t out_index;"
    "func ^:get_in_size;"
    "func ^:get_out_size;"
    "func ^:get_dynamics_std;"
    "func ^:set_dynamics_std;"
    "func ^:minfer;"
    "func ^:bgrad_adapt;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bsym_vm_builder_s )
"aware badapt_builder"
"{"
    "st_s holograph_file;"
    "st_s name_out_holor = \"output\";"
    "st_s name_out_size = \"out_size\";"
    "st_s name_in_holor = \"input\";"
    "sz_t in_size;"
    "sz_t out_size;"
    "u2_t rseed = 1234;"
    "badapt_dynamics_std_s dynamics;"
    "func ^:get_in_size;"
    "func ^:set_in_size;"
    "func ^:get_out_size;"
    "func ^:set_out_size;"
    "func ^:build;"
"}";

/**********************************************************************************************************************/
// source: bhgp
#include "bhgp.h"

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp

BCORE_DEFINE_OBJECT_INST_P( bhgp_context_s )
"aware bhgp"
"{"
    "bcore_hmap_name_s hmap_name;"
    "bcore_arr_st_s arr_symbol_op2;"
    "bhgp_sem_cell_s cell;"
    "bcore_arr_tp_s control_types;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_op

BCORE_DEFINE_SPECT( bhgp, bhgp_op )
"{"
    "bcore_spect_header_s header;"
    "feature strict aware bhgp_op : get_arity;"
    "feature aware bhgp_op : get_priority = bhgp_op_get_priority__;"
    "feature aware bhgp_op : get_symbol = bhgp_op_get_symbol__;"
    "feature aware bhgp_op : solve;"
    "feature aware bhgp_op : create_final = bhgp_op_create_final__;"
"}";


bhgp_op* bhgp_op_create_final__( const bhgp_op* o, bmath_hf3_s* h )
{
    bhgp_op_ar0_holor_s* final = bhgp_op_ar0_holor_s_create();
    final->h = bcore_fork( h );
    return (bhgp_op*)final;
}
//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_op_ar0

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar0_holor_s )
"aware bhgp_op_ar0"
"{"
    "bmath_hf3_s -> h;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar0_holor_s_solve( const bhgp_op_ar0_holor_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, bcore_fork( o->h ) );
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar0_input_s )
"aware bhgp_op_ar0"
"{"
    "bmath_hf3_s -> h;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar0_input_s_solve( const bhgp_op_ar0_input_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, bcore_fork( o->h ) );
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar0_adapt_s )
"aware bhgp_op_ar0"
"{"
    "bmath_hf3_s -> h;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar0_adapt_s_solve( const bhgp_op_ar0_adapt_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, bcore_fork( o->h ) );
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_op_ar1

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar1_linear_s )
"aware bhgp_op_ar1"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar1_linear_s_solve( const bhgp_op_ar1_linear_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, bcore_fork( a[0] ) );
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar1_floor_s )
"aware bhgp_op_ar1"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func ^:create_vm_op;"
    "func bhgp_op:solve;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar1_ceil_s )
"aware bhgp_op_ar1"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func ^:create_vm_op;"
    "func bhgp_op:solve;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar1_tanh_s )
"aware bhgp_op_ar1"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func ^:create_vm_op;"
    "func bhgp_op:solve;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar1_exp_s )
"aware bhgp_op_ar1"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func ^:create_vm_op;"
    "func bhgp_op:solve;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar1_relu_s )
"aware bhgp_op_ar1"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar1_relu_s_solve( const bhgp_op_ar1_relu_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, a[0] ? bmath_hf3_s_create() : NULL );
    if( a[0] )
    {
        bmath_hf3_s_copy_size( *r, a[0] );
        if( a[0]->v_size ) bmath_hf3_s_relu( a[0], *r );
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar1_lrelu_s )
"aware bhgp_op_ar1"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar1_lrelu_s_solve( const bhgp_op_ar1_lrelu_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, a[0] ? bmath_hf3_s_create() : NULL );
    if( a[0] )
    {
        bmath_hf3_s_copy_size( *r, a[0] );
        if( a[0]->v_size ) bmath_hf3_s_lrelu( a[0], *r );
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar1_adapt_s )
"aware bhgp_op_ar1"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
    "func bhgp_op:create_final;"
"}";

s2_t bhgp_op_ar1_adapt_s_solve( const bhgp_op_ar1_adapt_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, bcore_fork( a[0] ) );
    return ( *r ) ? 1 : 0; // (!) settles on vacant
}

bhgp_op* bhgp_op_ar1_adapt_s_create_final( const bhgp_op_ar1_adapt_s* o, bmath_hf3_s* h )
{
    bhgp_op_ar0_adapt_s* final = bhgp_op_ar0_adapt_s_create();
    final->h = bcore_fork( h );
    return (bhgp_op*)final;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar1_identity_s )
"aware bhgp_op_ar1"
"{"
    "func bhgp_op:get_arity;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar1_identity_s_solve( const bhgp_op_ar1_identity_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, bcore_fork( a[0] ) );
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar1_output_s )
"aware bhgp_op_ar1"
"{"
    "func bhgp_op:get_arity;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar1_output_s_solve( const bhgp_op_ar1_output_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, bcore_fork( a[0] ) );
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar1_dimof_s )
"aware bhgp_op_ar1"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar1_dimof_s_solve( const bhgp_op_ar1_dimof_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, a[0] ? bmath_hf3_s_create() : NULL );
    if( a[0] )
    {
        bmath_hf3_s_set_scalar_f3( *r, a[0]->d_size ? a[0]->d_data[ a[0]->d_size - 1 ] : 1 );
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar1_rand_s )
"aware bhgp_op_ar1"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar1_rand_s_solve( const bhgp_op_ar1_rand_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, a[0] ? bmath_hf3_s_create() : NULL );
    if( a[0] )
    {
        bmath_hf3_s_copy( *r, a[0] );
        if( !(*r)->v_size ) bmath_hf3_s_fit_v_size( *r );
        f3_t sum = f3_abs( bmath_hf3_s_f3_sum( *r ) );
        f3_t max = f3_abs( bmath_hf3_s_f3_max( *r ) );
        f3_t rbase = ( max > 0 ) ? ( sum / max ) : 0;
        u2_t rval = rbase * 21036284023;
        rval += (*r)->v_size;
        if( rval == 0 ) rval = 1;
        bmath_hf3_s_set_random( *r, 1.0, -1.0, 1.0, &rval );
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_SPECT( bhgp_op, bhgp_op_ar1 )
"{"
    "bcore_spect_header_s header;"
    "feature aware bhgp_op_ar1 : create_vm_op = bhgp_op_ar1_create_vm_op__;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_op_ar2

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar2_bmul_s )
"aware bhgp_op_ar2"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
    "func ^:create_vm_op;"
"}";

s2_t bhgp_op_ar2_bmul_s_solve( const bhgp_op_ar2_bmul_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, ( a[0] && a[1] ) ? bmath_hf3_s_create() : NULL );
    if( *r )
    {
        if( !bmath_hf3_s_set_d_bmul( a[0], a[1], *r ) ) return -1;
        if( a[0]->v_data && a[1]->v_data )
        {
            bmath_hf3_s_fit_v_size( *r );
            bmath_hf3_s_bmul( a[0], a[1], *r );
        }
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar2_bmul_htp_s )
"aware bhgp_op_ar2"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
    "func ^:create_vm_op;"
"}";

s2_t bhgp_op_ar2_bmul_htp_s_solve( const bhgp_op_ar2_bmul_htp_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, ( a[0] && a[1] ) ? bmath_hf3_s_create() : NULL );
    if( *r )
    {
        if( !bmath_hf3_s_set_d_bmul_htp( a[0], a[1], *r ) ) return -1;
        if( a[0]->v_data && a[1]->v_data )
        {
            bmath_hf3_s_fit_v_size( *r );
            bmath_hf3_s_bmul_htp( a[0], a[1], *r );
        }
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar2_htp_bmul_s )
"aware bhgp_op_ar2"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
    "func ^:create_vm_op;"
"}";

s2_t bhgp_op_ar2_htp_bmul_s_solve( const bhgp_op_ar2_htp_bmul_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, ( a[0] && a[1] ) ? bmath_hf3_s_create() : NULL );
    if( *r )
    {
        if( !bmath_hf3_s_set_d_htp_bmul( a[0], a[1], *r ) ) return -1;
        if( a[0]->v_data && a[1]->v_data )
        {
            bmath_hf3_s_fit_v_size( *r );
            bmath_hf3_s_htp_bmul( a[0], a[1], *r );
        }
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar2_htp_bmul_htp_s )
"aware bhgp_op_ar2"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
    "func ^:create_vm_op;"
"}";

s2_t bhgp_op_ar2_htp_bmul_htp_s_solve( const bhgp_op_ar2_htp_bmul_htp_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, ( a[0] && a[1] ) ? bmath_hf3_s_create() : NULL );
    if( *r )
    {
        if( !bmath_hf3_s_set_d_htp_bmul_htp( a[0], a[1], *r ) ) return -1;
        if( a[0]->v_data && a[1]->v_data )
        {
            bmath_hf3_s_fit_v_size( *r );
            bmath_hf3_s_htp_bmul_htp( a[0], a[1], *r );
        }
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar2_mul_s )
"aware bhgp_op_ar2"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
    "func ^:create_vm_op;"
"}";

s2_t bhgp_op_ar2_mul_s_solve( const bhgp_op_ar2_mul_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, ( a[0] && a[1] ) ? bmath_hf3_s_create() : NULL );
    if( *r )
    {
        if( a[0]->d_size == 0 )
        {
            bmath_hf3_s_copy_d_data( *r, a[1] );
            if( ( a[0]->v_size > 0 ) && ( a[1]->v_size > 0 ) )
            {
                bmath_hf3_s_fit_v_size( *r );
                bmath_hf3_s_mul_scl( a[1], a[0]->v_data, *r );
            }
        }
        else if( a[1]->d_size == 0 )
        {
            bmath_hf3_s_copy_d_data( *r, a[0] );
            if( ( a[0]->v_size > 0 ) && ( a[1]->v_size > 0 ) )
            {
                bmath_hf3_s_fit_v_size( *r );
                bmath_hf3_s_mul_scl( a[0], a[1]->v_data, *r );
            }
        }
        else
        {
            if( a[0]->d_size != a[1]->d_size ) return -1;
            if( bmath_hf3_s_d_product( a[0] ) != bmath_hf3_s_d_product( a[1] ) ) return -1;
            bmath_hf3_s_copy_d_data( *r, a[0] );
            if( ( a[0]->v_size > 0 ) && ( a[1]->v_size > 0 ) )
            {
                bmath_hf3_s_fit_v_size( *r );
                bmath_hf3_s_hmul( a[0], a[1], *r );
            }
        }
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar2_plus_s )
"aware bhgp_op_ar2"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
    "func ^:create_vm_op;"
"}";

s2_t bhgp_op_ar2_plus_s_solve( const bhgp_op_ar2_plus_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, ( a[0] && a[1] ) ? bmath_hf3_s_create() : NULL );
    if( *r )
    {
        if( a[0]->d_size != a[1]->d_size ) return -1;
        if( bmath_hf3_s_d_product( a[0] ) != bmath_hf3_s_d_product( a[1] ) ) return -1;
        bmath_hf3_s_copy_d_data( *r, a[0] );
        if( ( a[0]->v_size > 0 ) && ( a[1]->v_size > 0 ) )
        {
            bmath_hf3_s_fit_v_size( *r );
            bmath_hf3_s_add( a[0], a[1], *r );
        }
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar2_minus_s )
"aware bhgp_op_ar2"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
    "func ^:create_vm_op;"
"}";

s2_t bhgp_op_ar2_minus_s_solve( const bhgp_op_ar2_minus_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, ( a[0] && a[1] ) ? bmath_hf3_s_create() : NULL );
    if( *r )
    {
        if( a[0]->d_size != a[1]->d_size ) return -1;
        if( bmath_hf3_s_d_product( a[0] ) != bmath_hf3_s_d_product( a[1] ) ) return -1;
        bmath_hf3_s_copy_d_data( *r, a[0] );
        if( ( a[0]->v_size > 0 ) && ( a[1]->v_size > 0 ) )
        {
            bmath_hf3_s_fit_v_size( *r );
            bmath_hf3_s_sub( a[0], a[1], *r );
        }
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar2_equal_s )
"aware bhgp_op_ar2"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar2_equal_s_solve( const bhgp_op_ar2_equal_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, ( a[0] && a[1] ) ? bmath_hf3_s_create() : NULL );
    if( *r ) bmath_hf3_s_set_scalar_f3( *r, bmath_hf3_s_is_equal( a[0], a[1] ) ? 1 : 0 );
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar2_larger_s )
"aware bhgp_op_ar2"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar2_larger_s_solve( const bhgp_op_ar2_larger_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, ( a[0] && a[1] ) ? bmath_hf3_s_create() : NULL );
    if( *r )
    {
        if( !bmath_hf3_s_is_scalar( a[0] ) || !a[0]->v_data ) return -1;
        if( !bmath_hf3_s_is_scalar( a[1] ) || !a[1]->v_data ) return -1;
        bmath_hf3_s_set_scalar_f3( *r, a[0]->v_data[0] > a[1]->v_data[0] ? 1 : 0 );
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar2_smaller_s )
"aware bhgp_op_ar2"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar2_smaller_s_solve( const bhgp_op_ar2_smaller_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, ( a[0] && a[1] ) ? bmath_hf3_s_create() : NULL );
    if( *r )
    {
        if( !bmath_hf3_s_is_scalar( a[0] ) || !a[0]->v_data ) return -1;
        if( !bmath_hf3_s_is_scalar( a[1] ) || !a[1]->v_data ) return -1;
        bmath_hf3_s_set_scalar_f3( *r, a[0]->v_data[0] < a[1]->v_data[0] ? 1 : 0 );
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar2_larger_equal_s )
"aware bhgp_op_ar2"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar2_larger_equal_s_solve( const bhgp_op_ar2_larger_equal_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, ( a[0] && a[1] ) ? bmath_hf3_s_create() : NULL );
    if( *r )
    {
        if( !bmath_hf3_s_is_scalar( a[0] ) || !a[0]->v_data ) return -1;
        if( !bmath_hf3_s_is_scalar( a[1] ) || !a[1]->v_data ) return -1;
        bmath_hf3_s_set_scalar_f3( *r, a[0]->v_data[0] >= a[1]->v_data[0] ? 1 : 0 );
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar2_smaller_equal_s )
"aware bhgp_op_ar2"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar2_smaller_equal_s_solve( const bhgp_op_ar2_smaller_equal_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, ( a[0] && a[1] ) ? bmath_hf3_s_create() : NULL );
    if( *r )
    {
        if( !bmath_hf3_s_is_scalar( a[0] ) || !a[0]->v_data ) return -1;
        if( !bmath_hf3_s_is_scalar( a[1] ) || !a[1]->v_data ) return -1;
        bmath_hf3_s_set_scalar_f3( *r, a[0]->v_data[0] <= a[1]->v_data[0] ? 1 : 0 );
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar2_logic_and_s )
"aware bhgp_op_ar2"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar2_logic_and_s_solve( const bhgp_op_ar2_logic_and_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, ( a[0] && a[1] ) ? bmath_hf3_s_create() : NULL );
    if( *r )
    {
        if( !bmath_hf3_s_is_scalar( a[0] ) || !a[0]->v_data ) return -1;
        if( !bmath_hf3_s_is_scalar( a[1] ) || !a[1]->v_data ) return -1;
        bmath_hf3_s_set_scalar_f3( *r, ( a[0]->v_data[0] > 0 ) && ( a[1]->v_data[0] > 0 ) ? 1 : 0 );
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar2_logic_or_s )
"aware bhgp_op_ar2"
"{"
    "func bhgp_op:get_symbol;"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar2_logic_or_s_solve( const bhgp_op_ar2_logic_or_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, ( a[0] && a[1] ) ? bmath_hf3_s_create() : NULL );
    if( *r )
    {
        if( !bmath_hf3_s_is_scalar( a[0] ) || !a[0]->v_data ) return -1;
        if( !bmath_hf3_s_is_scalar( a[1] ) || !a[1]->v_data ) return -1;
        bmath_hf3_s_set_scalar_f3( *r, ( a[0]->v_data[0] > 0 ) || ( a[1]->v_data[0] > 0 ) ? 1 : 0 );
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar2_index_s )
"aware bhgp_op_ar2"
"{"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar2_index_s_solve( const bhgp_op_ar2_index_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, ( a[0] && a[1] ) ? bmath_hf3_s_create() : NULL );
    if( *r )
    {
        if( a[1]->v_size != 1 ) return -1;
        sz_t index = a[1]->v_data[ 0 ];
        if( a[0]->d_size == 0 ) return -1;
        if( index < 0 || index >= a[0]->d_data[ a[0]->d_size - 1 ] ) return -1;
        bmath_hf3_s_clear( *r );
        bmath_hf3_s_set_d_data( *r, a[0]->d_data, a[0]->d_size -1 );
        if( a[0]->v_data )
        {
            (*r)->v_size = bmath_hf3_s_d_product( *r );
            (*r)->v_data = a[0]->v_data + index * (*r)->v_size;
            (*r)->v_space = 0;
        }
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar2_inc_order_s )
"aware bhgp_op_ar2"
"{"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar2_inc_order_s_solve( const bhgp_op_ar2_inc_order_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    bmath_hf3_s_attach( r, ( a[0] && a[1] ) ? bmath_hf3_s_create() : NULL );
    if( *r )
    {
        if( a[0]->v_size != 1 ) return -1;
        sz_t dim = a[0]->v_data[ 0 ];
        if( dim <= 0 ) return -1;
        bmath_hf3_s_copy( *r, a[1] );
        bmath_hf3_s_inc_order( *r, dim );
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

BCORE_DEFINE_SPECT( bhgp_op, bhgp_op_ar2 )
"{"
    "bcore_spect_header_s header;"
    "feature aware bhgp_op_ar2 : create_vm_op = bhgp_op_ar2_create_vm_op__;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_op_ar3

BCORE_DEFINE_OBJECT_INST_P( bhgp_op_ar3_branch_s )
"aware bhgp_op_ar3"
"{"
    "func bhgp_op:get_arity;"
    "func bhgp_op:get_priority;"
    "func bhgp_op:solve;"
"}";

s2_t bhgp_op_ar3_branch_s_solve( const bhgp_op_ar3_branch_s* o, bmath_hf3_s** r, bmath_hf3_s** a )
{
    if( a[0] )
    {
        if( a[0]->v_size != 1 ) return -1;
        f3_t cond = a[0]->v_data[ 0 ];
        if( cond > 0 )
        {
            bmath_hf3_s_attach( r, bcore_fork( a[1] ) );
        }
        else
        {
            bmath_hf3_s_attach( r, bcore_fork( a[2] ) );
        }
    }
    return ( *r && (*r)->v_size ) ? 1 : 0;
}

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_sem

BCORE_DEFINE_OBJECT_INST_P( bhgp_sem_link_s )
"aware bhgp_sem"
"{"
    "tp_t name;"
    "private bhgp_sem_link_s -> up;"
    "private bhgp_sem_link_s -> dn;"
    "private vd_t cell;"
    "bl_t exit;"
    "func ^:get_name;"
"}";

tp_t bhgp_sem_link_s_get_name( const bhgp_sem_link_s* o )
{ return o->name; }

BCORE_DEFINE_OBJECT_INST_P( bhgp_sem_links_s )
"aware bcore_array"
"{"
    "bhgp_sem_link_s => [];"
    "func bhgp_sem:get_link_by_name;"
    "func bhgp_sem:name_exists;"
    "func bhgp_sem:get_link_by_up;"
    "func bhgp_sem:get_link_by_dn;"
    "func bhgp_sem:get_index_by_link;"
    "func bhgp_sem:count_open;"
"}";

bhgp_sem_link_s* bhgp_sem_links_s_get_link_by_name( bhgp_sem_links_s* o, tp_t name )
{
    BFOR_EACH( o, i ) if( o->data[ i ]->name == name ) return o->data[ i ];
    return NULL;
}

bl_t bhgp_sem_links_s_name_exists( const bhgp_sem_links_s* o, tp_t name )
{
    BFOR_EACH( o, i ) if( o->data[ i ]->name == name ) return true;
    return false;
}

bhgp_sem_link_s* bhgp_sem_links_s_get_link_by_up( bhgp_sem_links_s* o, bhgp_sem_link_s* up )
{
    BFOR_EACH( o, i ) if( o->data[ i ]->up == up ) return o->data[ i ];
    return NULL;
}

bhgp_sem_link_s* bhgp_sem_links_s_get_link_by_dn( bhgp_sem_links_s* o, bhgp_sem_link_s* dn )
{
    BFOR_EACH( o, i ) if( o->data[ i ]->dn == dn ) return o->data[ i ];
    return NULL;
}

sz_t bhgp_sem_links_s_get_index_by_link( bhgp_sem_links_s* o, bhgp_sem_link_s* link )
{
    BFOR_EACH( o, i ) if( o->data[ i ] == link ) return i;
    return -1;
}

sz_t bhgp_sem_links_s_count_open( const bhgp_sem_links_s* o )
{
    sz_t count = 0;
    BFOR_EACH( o, i ) count += ( o->data[ i ]->up == NULL );
    return count;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_sem_body_s )
"aware bcore_array"
"{"
    "aware bhgp_sem=> [];"
    "func bhgp_sem:name_exists;"
    "func bhgp_sem:get_sem_by_name;"
"}";

bl_t bhgp_sem_body_s_name_exists( const bhgp_sem_body_s* o, tp_t name )
{
    BFOR_EACH( o, i ) if( bhgp_sem_a_get_name( o->data[ i ] ) == name ) return true;
    return false;
}

bhgp_sem* bhgp_sem_body_s_get_sem_by_name( bhgp_sem_body_s* o, tp_t name )
{
    BFOR_EACH( o, i ) if( bhgp_sem_a_get_name( o->data[ i ] ) == name ) return o->data[ i ];
    return NULL;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_sem_cell_s )
"aware bhgp_sem"
"{"
    "tp_t name;"
    "bhgp_sem_links_s encs;"
    "bhgp_sem_links_s excs;"
    "bhgp_sem_body_s => body;"
    "aware bhgp_op -> op;"
    "sz_t priority = 10;"
    "private bhgp_sem_cell_s* parent;"
    "hidden bcore_source_point_s source_point;"
    "func ^:get_name;"
    "func ^:get_arity;"
    "func ^:get_enc_by_name;"
    "func ^:get_exc_by_name;"
    "func ^:get_enc_by_open;"
    "func ^:get_enc_by_dn;"
    "func ^:get_priority;"
    "func ^:get_cell_by_name;"
"}";

tp_t bhgp_sem_cell_s_get_name( const bhgp_sem_cell_s* o )
{ return o->name; }

bhgp_sem_cell_s* bhgp_sem_cell_s_get_cell_by_name( bhgp_sem_cell_s* o, tp_t name )
{
    bhgp_sem* sem = o->body ? bhgp_sem_body_s_get_sem_by_name( o->body, name ) : NULL;
    if( sem && sem->_ == TYPEOF_bhgp_sem_cell_s ) return ( bhgp_sem_cell_s* )sem;
    if( o->parent ) return bhgp_sem_cell_s_get_cell_by_name( o->parent, name );
    return NULL;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_sem_stack_flag_s )
"aware bhgp_sem"
"{"
"}";

BCORE_DEFINE_SPECT( bhgp, bhgp_sem )
"{"
    "bcore_spect_header_s header;"
    "feature aware bhgp_sem : get_name = bhgp_sem_get_name__;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_ctr

BCORE_DEFINE_OBJECT_INST_P( bhgp_ctr_node_s )
"aware bcore_array"
"{"
    "sz_t id = -1;"
    "private bhgp_sem_cell_s -> cell;"
    "private bhgp_ctr_node_s -> parent;"
    "bhgp_ctr_node_s => [];"
"}";

BCORE_DEFINE_OBJECT_INST_P( bhgp_ctr_tree_s )
"aware bhgp_ctr"
"{"
    "sz_t id_base = 0;"
    "bhgp_ctr_node_s => root;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_net

BCORE_DEFINE_OBJECT_INST_P( bhgp_net_link_s )
"aware bhgp_net"
"{"
    "hidden vd_t node;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bhgp_net_links_s )
"aware bcore_array"
"{"
    "bhgp_net_link_s => [];"
"}";

BCORE_DEFINE_OBJECT_INST_P( bhgp_net_node_s )
"aware bhgp_net"
"{"
    "bhgp_net_links_s upls;"
    "bhgp_net_links_s dnls;"
    "sz_t id;"
    "bl_t flag = false;"
    "tp_t name;"
    "aware bhgp_op -> op;"
    "bmath_hf3_s-> h;"
    "bcore_source_point_s -> source_point;"
    "func ^:solve;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bhgp_net_nodes_s )
"aware bcore_array"
"{"
    "bhgp_net_node_s => [];"
    "func bhgp_net:get_by_id;"
"}";

bhgp_net_node_s* bhgp_net_nodes_s_get_by_id( bhgp_net_nodes_s* o, sz_t id )
{
    BFOR_EACH( o, i ) if( o->data[ i ]->id == id ) return o->data[ i ];
    return NULL;
}

BCORE_DEFINE_OBJECT_INST_P( bhgp_net_cell_s )
"aware bhgp_net"
"{"
    "sz_t max_depth = 65536;"
    "bhgp_net_nodes_s body;"
    "bhgp_net_nodes_s encs;"
    "bhgp_net_nodes_s excs;"
    "func ^:is_consistent;"
    "func ^:normalize;"
    "func ^:clear_flags;"
    "func ^:solve;"
    "func ^:clear_downlinks;"
    "func ^:set_downlinks;"
    "func bcore_inst_call:copy_x;"
    "func bcore_via_call:mutated;"
"}";

void bhgp_net_cell_s_clear_flags( bhgp_net_cell_s* o )
{
    BFOR_EACH( &o->body, i ) o->body.data[ i ]->flag = false;
}

void bhgp_net_cell_s_solve( bhgp_net_cell_s* o )
{
    BFOR_EACH( &o->excs, i ) bhgp_net_node_s_solve( o->excs.data[ i ] );
}

void bhgp_net_cell_s_clear_downlinks( bhgp_net_cell_s* o )
{
    BFOR_EACH( &o->body, i ) bhgp_net_links_s_clear( &o->body.data[ i ]->dnls );
}

//----------------------------------------------------------------------------------------------------------------------
// group: bhgp_vm

BCORE_DEFINE_OBJECT_INST_P( bhgp_vm_adaptive_s )
"aware badapt_adaptive"
"{"
    "st_s frame;"
    "st_s src;"
    "bmath_hf3_vm_frame_s vm;"
    "badapt_dynamics_std_s dynamics;"
    "sz_t in_size;"
    "sz_t out_size;"
    "sz_t in_index;"
    "sz_t out_index;"
    "func ^:get_in_size;"
    "func ^:get_out_size;"
    "func ^:get_dynamics_std;"
    "func ^:set_dynamics_std;"
    "func ^:minfer;"
    "func ^:bgrad_adapt;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bhgp_vm_builder_s )
"aware badapt_builder"
"{"
    "st_s frame = \"( y => a )\";"
    "st_s src;"
    "sz_t in_size;"
    "sz_t out_size;"
    "badapt_dynamics_std_s dynamics;"
    "func ^:get_in_size;"
    "func ^:set_in_size;"
    "func ^:get_out_size;"
    "func ^:set_out_size;"
    "func ^:build;"
"}";

/**********************************************************************************************************************/

vd_t badapt_dev_planted_signal_handler( const bcore_signal_s* o )
{
    switch( bcore_signal_s_handle_type( o, typeof( "badapt_dev_planted" ) ) )
    {
        case TYPEOF_init1:
        {
            // Comment or remove line below to rebuild this target.
            bcore_const_x_set_d( typeof( "badapt_dev_planted_hash" ), sr_tp( 324285777 ) );
            BCORE_REGISTER_FFUNC( badapt_supplier_preferred_loss, badapt_problem_recurrent_abc_s_preferred_loss );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_in_size, badapt_problem_recurrent_abc_s_get_in_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_out_size, badapt_problem_recurrent_abc_s_get_out_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_sample_tio, badapt_problem_recurrent_abc_s_fetch_sample_tio );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_sample_vio, badapt_problem_recurrent_abc_s_fetch_sample_vio );
            BCORE_REGISTER_OBJECT( badapt_problem_recurrent_abc_s );
            BCORE_REGISTER_FFUNC( badapt_supplier_preferred_loss, badapt_problem_recurrent_kjv_s_preferred_loss );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_in_size, badapt_problem_recurrent_kjv_s_get_in_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_out_size, badapt_problem_recurrent_kjv_s_get_out_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_sample_tio, badapt_problem_recurrent_kjv_s_fetch_sample_tio );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_sample_vio, badapt_problem_recurrent_kjv_s_fetch_sample_vio );
            BCORE_REGISTER_OBJECT( badapt_problem_recurrent_kjv_s );
            BCORE_REGISTER_FFUNC( badapt_supplier_preferred_loss, badapt_problem_recurrent_text_s_preferred_loss );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_in_size, badapt_problem_recurrent_text_s_get_in_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_out_size, badapt_problem_recurrent_text_s_get_out_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_sample_tio, badapt_problem_recurrent_text_s_fetch_sample_tio );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_sample_vio, badapt_problem_recurrent_text_s_fetch_sample_vio );
            BCORE_REGISTER_OBJECT( badapt_problem_recurrent_text_s );
            BCORE_REGISTER_FFUNC( badapt_guide_callback, badapt_guide_char_encode_s_callback );
            BCORE_REGISTER_OBJECT( badapt_guide_char_encode_s );
            BCORE_REGISTER_TRAIT( badapt_dev_problem_objects, bcore_inst );
            BCORE_REGISTER_TRAIT( badapt_dev_ern, bcore_inst );
            BCORE_REGISTER_NAME( link );
            BCORE_REGISTER_NAME( holor );
            BCORE_REGISTER_NAME( graph );
            BCORE_REGISTER_OBJECT( bsym_source_info_s );
            BCORE_REGISTER_TRAIT( bsym, bcore_inst );
            BCORE_REGISTER_FEATURE( bsym_op_trace_to_sink );
            BCORE_REGISTER_FFUNC( bsym_op_trace_to_sink, bsym_op_trace_to_sink__ );
            BCORE_REGISTER_FEATURE( bsym_op_get_arity );
            BCORE_REGISTER_FEATURE( bsym_op_get_priority );
            BCORE_REGISTER_FFUNC( bsym_op_get_priority, bsym_op_get_priority__ );
            BCORE_REGISTER_SPECT( bsym_op );
            BCORE_REGISTER_NAME( adaptive );
            BCORE_REGISTER_NAME( buffer );
            BCORE_REGISTER_NAME( literal );
            BCORE_REGISTER_FEATURE( bsym_op_ar0_compute_hf3 );
            BCORE_REGISTER_FEATURE( bsym_op_ar0_create_vm_operator );
            BCORE_REGISTER_FFUNC( bsym_op_ar0_create_vm_operator, bsym_op_ar0_create_vm_operator__ );
            BCORE_REGISTER_FEATURE( bsym_op_ar0_get_hf3_type );
            BCORE_REGISTER_FFUNC( bsym_op_get_arity, bsym_op_ar0_holor_s_get_arity );
            BCORE_REGISTER_FFUNC( bsym_op_trace_to_sink, bsym_op_ar0_holor_s_trace_to_sink );
            BCORE_REGISTER_FFUNC( bsym_op_ar0_compute_hf3, bsym_op_ar0_holor_s_compute_hf3 );
            BCORE_REGISTER_FFUNC( bsym_op_ar0_get_hf3_type, bsym_op_ar0_holor_s_get_hf3_type );
            BCORE_REGISTER_OBJECT( bsym_op_ar0_holor_s );
            BCORE_REGISTER_SPECT( bsym_op_ar0 );
            BCORE_REGISTER_FEATURE( bsym_op_ar1_get_symbol );
            BCORE_REGISTER_FEATURE( bsym_op_ar1_compute_hf3 );
            BCORE_REGISTER_FEATURE( bsym_op_ar1_create_vm_operator );
            BCORE_REGISTER_FFUNC( bsym_op_ar1_create_vm_operator, bsym_op_ar1_create_vm_operator__ );
            BCORE_REGISTER_FFUNC( bsym_op_get_arity, bsym_op_ar1_linear_s_get_arity );
            BCORE_REGISTER_FFUNC( bsym_op_ar1_get_symbol, bsym_op_ar1_linear_s_get_symbol );
            BCORE_REGISTER_FFUNC( bsym_op_ar1_compute_hf3, bsym_op_ar1_linear_s_compute_hf3 );
            BCORE_REGISTER_OBJECT( bsym_op_ar1_linear_s );
            BCORE_REGISTER_FFUNC( bsym_op_get_arity, bsym_op_ar1_tanh_s_get_arity );
            BCORE_REGISTER_FFUNC( bsym_op_ar1_get_symbol, bsym_op_ar1_tanh_s_get_symbol );
            BCORE_REGISTER_FFUNC( bsym_op_ar1_compute_hf3, bsym_op_ar1_tanh_s_compute_hf3 );
            BCORE_REGISTER_FFUNC( bsym_op_ar1_create_vm_operator, bsym_op_ar1_tanh_s_create_vm_operator );
            BCORE_REGISTER_OBJECT( bsym_op_ar1_tanh_s );
            BCORE_REGISTER_FFUNC( bsym_op_get_arity, bsym_op_ar1_dimof_s_get_arity );
            BCORE_REGISTER_FFUNC( bsym_op_ar1_get_symbol, bsym_op_ar1_dimof_s_get_symbol );
            BCORE_REGISTER_FFUNC( bsym_op_ar1_compute_hf3, bsym_op_ar1_dimof_s_compute_hf3 );
            BCORE_REGISTER_OBJECT( bsym_op_ar1_dimof_s );
            BCORE_REGISTER_SPECT( bsym_op_ar1 );
            bcore_inst_s_get_typed( TYPEOF_bsym_op_ar1_linear_s );
            bcore_inst_s_get_typed( TYPEOF_bsym_op_ar1_tanh_s );
            bcore_inst_s_get_typed( TYPEOF_bsym_op_ar1_dimof_s );
            BCORE_REGISTER_FEATURE( bsym_op_ar2_get_symbol );
            BCORE_REGISTER_FEATURE( bsym_op_ar2_compute_hf3 );
            BCORE_REGISTER_FEATURE( bsym_op_ar2_create_vm_operator );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_create_vm_operator, bsym_op_ar2_create_vm_operator__ );
            BCORE_REGISTER_FFUNC( bsym_op_get_arity, bsym_op_ar2_bmul_s_get_arity );
            BCORE_REGISTER_FFUNC( bsym_op_get_priority, bsym_op_ar2_bmul_s_get_priority );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_get_symbol, bsym_op_ar2_bmul_s_get_symbol );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_compute_hf3, bsym_op_ar2_bmul_s_compute_hf3 );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_create_vm_operator, bsym_op_ar2_bmul_s_create_vm_operator );
            BCORE_REGISTER_OBJECT( bsym_op_ar2_bmul_s );
            BCORE_REGISTER_FFUNC( bsym_op_get_arity, bsym_op_ar2_bmul_htp_s_get_arity );
            BCORE_REGISTER_FFUNC( bsym_op_get_priority, bsym_op_ar2_bmul_htp_s_get_priority );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_get_symbol, bsym_op_ar2_bmul_htp_s_get_symbol );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_compute_hf3, bsym_op_ar2_bmul_htp_s_compute_hf3 );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_create_vm_operator, bsym_op_ar2_bmul_htp_s_create_vm_operator );
            BCORE_REGISTER_OBJECT( bsym_op_ar2_bmul_htp_s );
            BCORE_REGISTER_FFUNC( bsym_op_get_arity, bsym_op_ar2_htp_bmul_s_get_arity );
            BCORE_REGISTER_FFUNC( bsym_op_get_priority, bsym_op_ar2_htp_bmul_s_get_priority );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_get_symbol, bsym_op_ar2_htp_bmul_s_get_symbol );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_compute_hf3, bsym_op_ar2_htp_bmul_s_compute_hf3 );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_create_vm_operator, bsym_op_ar2_htp_bmul_s_create_vm_operator );
            BCORE_REGISTER_OBJECT( bsym_op_ar2_htp_bmul_s );
            BCORE_REGISTER_FFUNC( bsym_op_get_arity, bsym_op_ar2_htp_bmul_htp_s_get_arity );
            BCORE_REGISTER_FFUNC( bsym_op_get_priority, bsym_op_ar2_htp_bmul_htp_s_get_priority );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_get_symbol, bsym_op_ar2_htp_bmul_htp_s_get_symbol );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_compute_hf3, bsym_op_ar2_htp_bmul_htp_s_compute_hf3 );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_create_vm_operator, bsym_op_ar2_htp_bmul_htp_s_create_vm_operator );
            BCORE_REGISTER_OBJECT( bsym_op_ar2_htp_bmul_htp_s );
            BCORE_REGISTER_FFUNC( bsym_op_get_arity, bsym_op_ar2_mul_s_get_arity );
            BCORE_REGISTER_FFUNC( bsym_op_get_priority, bsym_op_ar2_mul_s_get_priority );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_get_symbol, bsym_op_ar2_mul_s_get_symbol );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_compute_hf3, bsym_op_ar2_mul_s_compute_hf3 );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_create_vm_operator, bsym_op_ar2_mul_s_create_vm_operator );
            BCORE_REGISTER_OBJECT( bsym_op_ar2_mul_s );
            BCORE_REGISTER_FFUNC( bsym_op_get_arity, bsym_op_ar2_plus_s_get_arity );
            BCORE_REGISTER_FFUNC( bsym_op_get_priority, bsym_op_ar2_plus_s_get_priority );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_get_symbol, bsym_op_ar2_plus_s_get_symbol );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_compute_hf3, bsym_op_ar2_plus_s_compute_hf3 );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_create_vm_operator, bsym_op_ar2_plus_s_create_vm_operator );
            BCORE_REGISTER_OBJECT( bsym_op_ar2_plus_s );
            BCORE_REGISTER_FFUNC( bsym_op_get_arity, bsym_op_ar2_minus_s_get_arity );
            BCORE_REGISTER_FFUNC( bsym_op_get_priority, bsym_op_ar2_minus_s_get_priority );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_get_symbol, bsym_op_ar2_minus_s_get_symbol );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_compute_hf3, bsym_op_ar2_minus_s_compute_hf3 );
            BCORE_REGISTER_FFUNC( bsym_op_ar2_create_vm_operator, bsym_op_ar2_minus_s_create_vm_operator );
            BCORE_REGISTER_OBJECT( bsym_op_ar2_minus_s );
            BCORE_REGISTER_SPECT( bsym_op_ar2 );
            bcore_inst_s_get_typed( TYPEOF_bsym_op_ar2_bmul_s );
            bcore_inst_s_get_typed( TYPEOF_bsym_op_ar2_bmul_htp_s );
            bcore_inst_s_get_typed( TYPEOF_bsym_op_ar2_htp_bmul_s );
            bcore_inst_s_get_typed( TYPEOF_bsym_op_ar2_htp_bmul_htp_s );
            bcore_inst_s_get_typed( TYPEOF_bsym_op_ar2_mul_s );
            bcore_inst_s_get_typed( TYPEOF_bsym_op_ar2_plus_s );
            bcore_inst_s_get_typed( TYPEOF_bsym_op_ar2_minus_s );
            BCORE_REGISTER_OBJECT( bsym_net_hresult_s );
            BCORE_REGISTER_FEATURE( bsym_net_trace_to_sink );
            BCORE_REGISTER_FFUNC( bsym_net_trace_to_sink, bsym_net_trace_to_sink__ );
            BCORE_REGISTER_FEATURE( bsym_net_get_name );
            BCORE_REGISTER_FFUNC( bsym_net_get_name, bsym_net_get_name__ );
            BCORE_REGISTER_FEATURE( bsym_net_set_body );
            BCORE_REGISTER_FFUNC( bsym_net_set_body, bsym_net_set_body__ );
            BCORE_REGISTER_FEATURE( bsym_net_trace_get_node );
            BCORE_REGISTER_FFUNC( bsym_net_trace_get_node, bsym_net_trace_get_node__ );
            BCORE_REGISTER_FEATURE( bsym_net_trace_compute_hresult );
            BCORE_REGISTER_FFUNC( bsym_net_trace_compute_hresult, bsym_net_trace_compute_hresult__ );
            BCORE_REGISTER_FEATURE( bsym_net_trace_clear_hresult );
            BCORE_REGISTER_FFUNC( bsym_net_trace_clear_hresult, bsym_net_trace_clear_hresult__ );
            BCORE_REGISTER_FEATURE( bsym_net_trace_build_vm_proc );
            BCORE_REGISTER_FFUNC( bsym_net_trace_build_vm_proc, bsym_net_trace_build_vm_proc__ );
            BCORE_REGISTER_FFUNC( bcore_inst_call_copy_x, bsym_net_body_s_copy_x );
            BCORE_REGISTER_OBJECT( bsym_net_body_s );
            BCORE_REGISTER_FFUNC( bsym_net_trace_get_node, bsym_net_address_s_trace_get_node );
            BCORE_REGISTER_FFUNC( bsym_net_trace_to_sink, bsym_net_address_s_trace_to_sink );
            BCORE_REGISTER_FFUNC( bsym_net_trace_compute_hresult, bsym_net_address_s_trace_compute_hresult );
            BCORE_REGISTER_FFUNC( bsym_net_trace_clear_hresult, bsym_net_address_s_trace_clear_hresult );
            BCORE_REGISTER_FFUNC( bsym_net_trace_build_vm_proc, bsym_net_address_s_trace_build_vm_proc );
            BCORE_REGISTER_FFUNC( bsym_net_get_net, bsym_net_address_s_get_net );
            BCORE_REGISTER_OBJECT( bsym_net_address_s );
            BCORE_REGISTER_FFUNC( bsym_net_get_name, bsym_net_link_s_get_name );
            BCORE_REGISTER_FFUNC( bsym_net_set_body, bsym_net_link_s_set_body );
            BCORE_REGISTER_FFUNC( bsym_net_trace_get_node, bsym_net_link_s_trace_get_node );
            BCORE_REGISTER_FFUNC( bsym_net_trace_to_sink, bsym_net_link_s_trace_to_sink );
            BCORE_REGISTER_FFUNC( bsym_net_trace_compute_hresult, bsym_net_link_s_trace_compute_hresult );
            BCORE_REGISTER_FFUNC( bsym_net_trace_clear_hresult, bsym_net_link_s_trace_clear_hresult );
            BCORE_REGISTER_FFUNC( bsym_net_trace_build_vm_proc, bsym_net_link_s_trace_build_vm_proc );
            BCORE_REGISTER_OBJECT( bsym_net_link_s );
            BCORE_REGISTER_NAME( infer );
            BCORE_REGISTER_FFUNC( bsym_net_get_name, bsym_net_node_s_get_name );
            BCORE_REGISTER_FFUNC( bsym_net_set_body, bsym_net_node_s_set_body );
            BCORE_REGISTER_FFUNC( bsym_net_trace_get_node, bsym_net_node_s_trace_get_node );
            BCORE_REGISTER_FFUNC( bsym_net_trace_to_sink, bsym_net_node_s_trace_to_sink );
            BCORE_REGISTER_FFUNC( bsym_net_trace_compute_hresult, bsym_net_node_s_trace_compute_hresult );
            BCORE_REGISTER_FFUNC( bsym_net_trace_clear_hresult, bsym_net_node_s_trace_clear_hresult );
            BCORE_REGISTER_FFUNC( bsym_net_trace_build_vm_proc, bsym_net_node_s_trace_build_vm_proc );
            BCORE_REGISTER_OBJECT( bsym_net_node_s );
            BCORE_REGISTER_SPECT( bsym_net );
            BCORE_REGISTER_OBJECT( bsym_sem_graph_s );
            BCORE_REGISTER_OBJECT( bsym_sem_graph_base_s );
            BCORE_REGISTER_OBJECT( bsym_sem_stack_flag_s );
            BCORE_REGISTER_TRAIT( bsym_sem, bsym );
            BCORE_REGISTER_FFUNC( badapt_adaptive_get_in_size, bsym_vm_adaptive_s_get_in_size );
            BCORE_REGISTER_FFUNC( badapt_adaptive_get_out_size, bsym_vm_adaptive_s_get_out_size );
            BCORE_REGISTER_FFUNC( badapt_adaptive_get_dynamics_std, bsym_vm_adaptive_s_get_dynamics_std );
            BCORE_REGISTER_FFUNC( badapt_adaptive_set_dynamics_std, bsym_vm_adaptive_s_set_dynamics_std );
            BCORE_REGISTER_FFUNC( badapt_adaptive_minfer, bsym_vm_adaptive_s_minfer );
            BCORE_REGISTER_FFUNC( badapt_adaptive_bgrad_adapt, bsym_vm_adaptive_s_bgrad_adapt );
            BCORE_REGISTER_OBJECT( bsym_vm_adaptive_s );
            BCORE_REGISTER_FFUNC( badapt_builder_get_in_size, bsym_vm_builder_s_get_in_size );
            BCORE_REGISTER_FFUNC( badapt_builder_set_in_size, bsym_vm_builder_s_set_in_size );
            BCORE_REGISTER_FFUNC( badapt_builder_get_out_size, bsym_vm_builder_s_get_out_size );
            BCORE_REGISTER_FFUNC( badapt_builder_set_out_size, bsym_vm_builder_s_set_out_size );
            BCORE_REGISTER_FFUNC( badapt_builder_build, bsym_vm_builder_s_build );
            BCORE_REGISTER_OBJECT( bsym_vm_builder_s );
            BCORE_REGISTER_TRAIT( bsym_vm, bsym );
            BCORE_REGISTER_NAME( cell );
            BCORE_REGISTER_NAME( if );
            BCORE_REGISTER_NAME( then );
            BCORE_REGISTER_NAME( else );
            BCORE_REGISTER_OBJECT( bhgp_context_s );
            BCORE_REGISTER_TRAIT( bhgp, bcore_inst );
            BCORE_REGISTER_FEATURE( bhgp_op_get_arity );
            BCORE_REGISTER_FEATURE( bhgp_op_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_get_priority__ );
            BCORE_REGISTER_FEATURE( bhgp_op_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_get_symbol__ );
            BCORE_REGISTER_FEATURE( bhgp_op_solve );
            BCORE_REGISTER_FEATURE( bhgp_op_create_final );
            BCORE_REGISTER_FFUNC( bhgp_op_create_final, bhgp_op_create_final__ );
            BCORE_REGISTER_SPECT( bhgp_op );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar0_holor_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar0_holor_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar0_holor_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar0_input_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar0_input_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar0_input_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar0_adapt_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar0_adapt_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar0_adapt_s );
            BCORE_REGISTER_TRAIT( bhgp_op_ar0, bhgp_op );
            BCORE_REGISTER_FEATURE( bhgp_op_ar1_create_vm_op );
            BCORE_REGISTER_FFUNC( bhgp_op_ar1_create_vm_op, bhgp_op_ar1_create_vm_op__ );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar1_linear_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar1_linear_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar1_linear_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar1_linear_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar1_linear_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar1_floor_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar1_floor_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar1_floor_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_ar1_create_vm_op, bhgp_op_ar1_floor_s_create_vm_op );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar1_floor_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar1_floor_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar1_ceil_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar1_ceil_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar1_ceil_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_ar1_create_vm_op, bhgp_op_ar1_ceil_s_create_vm_op );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar1_ceil_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar1_ceil_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar1_tanh_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar1_tanh_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar1_tanh_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_ar1_create_vm_op, bhgp_op_ar1_tanh_s_create_vm_op );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar1_tanh_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar1_tanh_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar1_exp_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar1_exp_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar1_exp_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_ar1_create_vm_op, bhgp_op_ar1_exp_s_create_vm_op );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar1_exp_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar1_exp_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar1_relu_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar1_relu_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar1_relu_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar1_relu_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar1_relu_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar1_lrelu_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar1_lrelu_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar1_lrelu_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar1_lrelu_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar1_lrelu_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar1_adapt_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar1_adapt_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar1_adapt_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar1_adapt_s_solve );
            BCORE_REGISTER_FFUNC( bhgp_op_create_final, bhgp_op_ar1_adapt_s_create_final );
            BCORE_REGISTER_OBJECT( bhgp_op_ar1_adapt_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar1_identity_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar1_identity_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar1_identity_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar1_output_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar1_output_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar1_output_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar1_dimof_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar1_dimof_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar1_dimof_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar1_dimof_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar1_dimof_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar1_rand_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar1_rand_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar1_rand_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar1_rand_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar1_rand_s );
            BCORE_REGISTER_SPECT( bhgp_op_ar1 );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar1_linear_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar1_floor_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar1_ceil_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar1_tanh_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar1_exp_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar1_relu_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar1_lrelu_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar1_adapt_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar1_identity_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar1_output_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar1_dimof_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar1_rand_s );
            BCORE_REGISTER_FEATURE( bhgp_op_ar2_create_vm_op );
            BCORE_REGISTER_FFUNC( bhgp_op_ar2_create_vm_op, bhgp_op_ar2_create_vm_op__ );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar2_bmul_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar2_bmul_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar2_bmul_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar2_bmul_s_solve );
            BCORE_REGISTER_FFUNC( bhgp_op_ar2_create_vm_op, bhgp_op_ar2_bmul_s_create_vm_op );
            BCORE_REGISTER_OBJECT( bhgp_op_ar2_bmul_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar2_bmul_htp_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar2_bmul_htp_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar2_bmul_htp_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar2_bmul_htp_s_solve );
            BCORE_REGISTER_FFUNC( bhgp_op_ar2_create_vm_op, bhgp_op_ar2_bmul_htp_s_create_vm_op );
            BCORE_REGISTER_OBJECT( bhgp_op_ar2_bmul_htp_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar2_htp_bmul_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar2_htp_bmul_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar2_htp_bmul_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar2_htp_bmul_s_solve );
            BCORE_REGISTER_FFUNC( bhgp_op_ar2_create_vm_op, bhgp_op_ar2_htp_bmul_s_create_vm_op );
            BCORE_REGISTER_OBJECT( bhgp_op_ar2_htp_bmul_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar2_htp_bmul_htp_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar2_htp_bmul_htp_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar2_htp_bmul_htp_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar2_htp_bmul_htp_s_solve );
            BCORE_REGISTER_FFUNC( bhgp_op_ar2_create_vm_op, bhgp_op_ar2_htp_bmul_htp_s_create_vm_op );
            BCORE_REGISTER_OBJECT( bhgp_op_ar2_htp_bmul_htp_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar2_mul_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar2_mul_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar2_mul_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar2_mul_s_solve );
            BCORE_REGISTER_FFUNC( bhgp_op_ar2_create_vm_op, bhgp_op_ar2_mul_s_create_vm_op );
            BCORE_REGISTER_OBJECT( bhgp_op_ar2_mul_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar2_plus_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar2_plus_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar2_plus_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar2_plus_s_solve );
            BCORE_REGISTER_FFUNC( bhgp_op_ar2_create_vm_op, bhgp_op_ar2_plus_s_create_vm_op );
            BCORE_REGISTER_OBJECT( bhgp_op_ar2_plus_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar2_minus_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar2_minus_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar2_minus_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar2_minus_s_solve );
            BCORE_REGISTER_FFUNC( bhgp_op_ar2_create_vm_op, bhgp_op_ar2_minus_s_create_vm_op );
            BCORE_REGISTER_OBJECT( bhgp_op_ar2_minus_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar2_equal_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar2_equal_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar2_equal_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar2_equal_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar2_equal_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar2_larger_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar2_larger_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar2_larger_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar2_larger_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar2_larger_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar2_smaller_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar2_smaller_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar2_smaller_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar2_smaller_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar2_smaller_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar2_larger_equal_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar2_larger_equal_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar2_larger_equal_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar2_larger_equal_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar2_larger_equal_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar2_smaller_equal_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar2_smaller_equal_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar2_smaller_equal_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar2_smaller_equal_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar2_smaller_equal_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar2_logic_and_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar2_logic_and_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar2_logic_and_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar2_logic_and_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar2_logic_and_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_symbol, bhgp_op_ar2_logic_or_s_get_symbol );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar2_logic_or_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar2_logic_or_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar2_logic_or_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar2_logic_or_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar2_index_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar2_index_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar2_index_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar2_index_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar2_inc_order_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar2_inc_order_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar2_inc_order_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar2_inc_order_s );
            BCORE_REGISTER_SPECT( bhgp_op_ar2 );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar2_bmul_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar2_bmul_htp_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar2_htp_bmul_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar2_htp_bmul_htp_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar2_mul_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar2_plus_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar2_minus_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar2_equal_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar2_larger_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar2_smaller_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar2_larger_equal_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar2_smaller_equal_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar2_logic_and_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar2_logic_or_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar2_index_s );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar2_inc_order_s );
            BCORE_REGISTER_FFUNC( bhgp_op_get_arity, bhgp_op_ar3_branch_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_op_get_priority, bhgp_op_ar3_branch_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_op_solve, bhgp_op_ar3_branch_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_op_ar3_branch_s );
            BCORE_REGISTER_TRAIT( bhgp_op_ar3, bhgp_op );
            bcore_inst_s_get_typed( TYPEOF_bhgp_op_ar3_branch_s );
            BCORE_REGISTER_FEATURE( bhgp_sem_get_name );
            BCORE_REGISTER_FFUNC( bhgp_sem_get_name, bhgp_sem_get_name__ );
            BCORE_REGISTER_FFUNC( bhgp_sem_get_name, bhgp_sem_link_s_get_name );
            BCORE_REGISTER_OBJECT( bhgp_sem_link_s );
            BCORE_REGISTER_FFUNC( bhgp_sem_get_link_by_name, bhgp_sem_links_s_get_link_by_name );
            BCORE_REGISTER_FFUNC( bhgp_sem_name_exists, bhgp_sem_links_s_name_exists );
            BCORE_REGISTER_FFUNC( bhgp_sem_get_link_by_up, bhgp_sem_links_s_get_link_by_up );
            BCORE_REGISTER_FFUNC( bhgp_sem_get_link_by_dn, bhgp_sem_links_s_get_link_by_dn );
            BCORE_REGISTER_FFUNC( bhgp_sem_get_index_by_link, bhgp_sem_links_s_get_index_by_link );
            BCORE_REGISTER_FFUNC( bhgp_sem_count_open, bhgp_sem_links_s_count_open );
            BCORE_REGISTER_OBJECT( bhgp_sem_links_s );
            BCORE_REGISTER_FFUNC( bhgp_sem_name_exists, bhgp_sem_body_s_name_exists );
            BCORE_REGISTER_FFUNC( bhgp_sem_get_sem_by_name, bhgp_sem_body_s_get_sem_by_name );
            BCORE_REGISTER_OBJECT( bhgp_sem_body_s );
            BCORE_REGISTER_FFUNC( bhgp_sem_get_name, bhgp_sem_cell_s_get_name );
            BCORE_REGISTER_FFUNC( bhgp_sem_get_arity, bhgp_sem_cell_s_get_arity );
            BCORE_REGISTER_FFUNC( bhgp_sem_get_enc_by_name, bhgp_sem_cell_s_get_enc_by_name );
            BCORE_REGISTER_FFUNC( bhgp_sem_get_exc_by_name, bhgp_sem_cell_s_get_exc_by_name );
            BCORE_REGISTER_FFUNC( bhgp_sem_get_enc_by_open, bhgp_sem_cell_s_get_enc_by_open );
            BCORE_REGISTER_FFUNC( bhgp_sem_get_enc_by_dn, bhgp_sem_cell_s_get_enc_by_dn );
            BCORE_REGISTER_FFUNC( bhgp_sem_get_priority, bhgp_sem_cell_s_get_priority );
            BCORE_REGISTER_FFUNC( bhgp_sem_get_cell_by_name, bhgp_sem_cell_s_get_cell_by_name );
            BCORE_REGISTER_OBJECT( bhgp_sem_cell_s );
            BCORE_REGISTER_OBJECT( bhgp_sem_stack_flag_s );
            BCORE_REGISTER_SPECT( bhgp_sem );
            BCORE_REGISTER_OBJECT( bhgp_ctr_node_s );
            BCORE_REGISTER_OBJECT( bhgp_ctr_tree_s );
            BCORE_REGISTER_TRAIT( bhgp_ctr, bhgp );
            BCORE_REGISTER_OBJECT( bhgp_net_link_s );
            BCORE_REGISTER_OBJECT( bhgp_net_links_s );
            BCORE_REGISTER_FFUNC( bhgp_net_solve, bhgp_net_node_s_solve );
            BCORE_REGISTER_OBJECT( bhgp_net_node_s );
            BCORE_REGISTER_FFUNC( bhgp_net_get_by_id, bhgp_net_nodes_s_get_by_id );
            BCORE_REGISTER_OBJECT( bhgp_net_nodes_s );
            BCORE_REGISTER_FFUNC( bhgp_net_is_consistent, bhgp_net_cell_s_is_consistent );
            BCORE_REGISTER_FFUNC( bhgp_net_normalize, bhgp_net_cell_s_normalize );
            BCORE_REGISTER_FFUNC( bhgp_net_clear_flags, bhgp_net_cell_s_clear_flags );
            BCORE_REGISTER_FFUNC( bhgp_net_solve, bhgp_net_cell_s_solve );
            BCORE_REGISTER_FFUNC( bhgp_net_clear_downlinks, bhgp_net_cell_s_clear_downlinks );
            BCORE_REGISTER_FFUNC( bhgp_net_set_downlinks, bhgp_net_cell_s_set_downlinks );
            BCORE_REGISTER_FFUNC( bcore_inst_call_copy_x, bhgp_net_cell_s_copy_x );
            BCORE_REGISTER_FFUNC( bcore_via_call_mutated, bhgp_net_cell_s_mutated );
            BCORE_REGISTER_OBJECT( bhgp_net_cell_s );
            BCORE_REGISTER_TRAIT( bhgp_net, bhgp );
            BCORE_REGISTER_FFUNC( badapt_adaptive_get_in_size, bhgp_vm_adaptive_s_get_in_size );
            BCORE_REGISTER_FFUNC( badapt_adaptive_get_out_size, bhgp_vm_adaptive_s_get_out_size );
            BCORE_REGISTER_FFUNC( badapt_adaptive_get_dynamics_std, bhgp_vm_adaptive_s_get_dynamics_std );
            BCORE_REGISTER_FFUNC( badapt_adaptive_set_dynamics_std, bhgp_vm_adaptive_s_set_dynamics_std );
            BCORE_REGISTER_FFUNC( badapt_adaptive_minfer, bhgp_vm_adaptive_s_minfer );
            BCORE_REGISTER_FFUNC( badapt_adaptive_bgrad_adapt, bhgp_vm_adaptive_s_bgrad_adapt );
            BCORE_REGISTER_OBJECT( bhgp_vm_adaptive_s );
            BCORE_REGISTER_FFUNC( badapt_builder_get_in_size, bhgp_vm_builder_s_get_in_size );
            BCORE_REGISTER_FFUNC( badapt_builder_set_in_size, bhgp_vm_builder_s_set_in_size );
            BCORE_REGISTER_FFUNC( badapt_builder_get_out_size, bhgp_vm_builder_s_get_out_size );
            BCORE_REGISTER_FFUNC( badapt_builder_set_out_size, bhgp_vm_builder_s_set_out_size );
            BCORE_REGISTER_FFUNC( badapt_builder_build, bhgp_vm_builder_s_build );
            BCORE_REGISTER_OBJECT( bhgp_vm_builder_s );
            BCORE_REGISTER_TRAIT( bhgp_vm, bhgp );
        }
        break;
        default: break;
    }
    return NULL;
}
