/** This file was generated by the beth-precode-compiler. Not suitable for manual editing.
 *
 *  Copyright and License:
 *    If a specification exists for the repository or folder in which the file is located,
 *    that specification shall apply. Otherwise, the Copyright and License of the associated
 *    source code files containing beth-precode shall apply.
 */

#ifndef BADAPT_PRECODED_H
#define BADAPT_PRECODED_H

#include "bcore_control.h"


/**********************************************************************************************************************/
// source: badapt_dev_problem

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_dev_problem_objects

#define TYPEOF_badapt_dev_problem_objects 483428364
  #define TYPEOF_badapt_dev_problem_recurrent_kjv_s 585086898
  #define BETH_EXPAND_ITEM_badapt_dev_problem_recurrent_kjv_s \
    BCORE_DECLARE_OBJECT( badapt_dev_problem_recurrent_kjv_s ) \
      {aware_t _;sz_t input_size;u2_t rval;f3_t pos_tgt;f3_t neg_tgt;badapt_loss* preferred_loss;}; \
    const badapt_loss* badapt_dev_problem_recurrent_kjv_s_preferred_loss( const badapt_dev_problem_recurrent_kjv_s* o ); \
    sz_t badapt_dev_problem_recurrent_kjv_s_get_in_size( const badapt_dev_problem_recurrent_kjv_s* o ); \
    sz_t badapt_dev_problem_recurrent_kjv_s_get_out_size( const badapt_dev_problem_recurrent_kjv_s* o ); \
    void badapt_dev_problem_recurrent_kjv_s_fetch_sample_tio( badapt_dev_problem_recurrent_kjv_s* o, bmath_vf3_s* in, bmath_vf3_s* out ); \
    void badapt_dev_problem_recurrent_kjv_s_fetch_sample_vio( badapt_dev_problem_recurrent_kjv_s* o, bmath_vf3_s* in, bmath_vf3_s* out );
#define BETH_EXPAND_GROUP_badapt_dev_problem_objects \
  BETH_EXPAND_ITEM_badapt_dev_problem_recurrent_kjv_s

/**********************************************************************************************************************/

vd_t badapt_precoded_signal_handler( const bcore_signal_s* o );

#endif // BADAPT_PRECODED_H
