/** This file was generated by the beth-precode-compiler. Not suitable for manual editing.
 *
 *  Copyright and License:
 *    If a specification exists for the repository or folder in which the file is located,
 *    that specification shall apply. Otherwise, the Copyright and License of the associated
 *    source code files containing beth-precode shall apply.
 */

#include "badapt_precoded.h"
#include "bcore_spect.h"
#include "bcore_spect_inst.h"
#include "bcore_sr.h"
#include "bcore_const_manager.h"


/**********************************************************************************************************************/
// source: badapt_features
#include "badapt_features.h"

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_loss

BCORE_DEFINE_SPECT( bcore_inst, badapt_loss )
"{"
    "bcore_spect_header_s header;"
    "feature strict aware badapt_loss : loss;"
    "feature strict aware badapt_loss : loss_f3;"
    "feature strict aware badapt_loss : bgrad;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_activation

BCORE_DEFINE_SPECT( bcore_inst, badapt_activation )
"{"
    "bcore_spect_header_s header;"
    "feature strict aware badapt_activation : fx;"
    "feature strict aware badapt_activation : dy;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_activator

BCORE_DEFINE_SPECT( bcore_inst, badapt_activator )
"{"
    "bcore_spect_header_s header;"
    "feature strict aware badapt_activator : reset;"
    "feature strict aware badapt_activator : setup;"
    "feature aware badapt_activator : get_size;"
    "feature aware badapt_activator : set_size;"
    "feature aware badapt_activator : get_activation;"
    "feature aware badapt_activator : set_activation;"
    "feature strict aware badapt_activator : infer;"
    "feature strict aware badapt_activator : bgrad;"
    "feature strict aware badapt_activator : adapt;"
"}";

/**********************************************************************************************************************/
// source: badapt_adaptive
#include "badapt_adaptive.h"

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_adaptive_objects

BCORE_DEFINE_OBJECT_INST( bcore_inst, badapt_dynamics_s )
"{"
    "aware_t _;"
    "f3_t epsilon;"
    "f3_t lambda_l1;"
    "f3_t lambda_l2;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_adaptive

BCORE_DEFINE_SPECT( bcore_inst, badapt_adaptive )
"{"
    "bcore_spect_header_s header;"
    "feature strict aware badapt_adaptive : get_in_size;"
    "feature strict aware badapt_adaptive : get_out_size;"
    "feature strict aware badapt_adaptive : infer;"
    "feature strict aware badapt_adaptive : minfer;"
    "feature strict aware badapt_adaptive : bgrad;"
    "feature strict aware badapt_adaptive : bgrad_adapt;"
    "feature aware badapt_adaptive : get_dynamics;"
    "feature aware badapt_adaptive : set_dynamics;"
    "feature aware badapt_adaptive : arc_to_sink = badapt_adaptive_arc_to_sink_fallback;"
    "feature aware badapt_adaptive : infer_f3 = badapt_adaptive_infer_f3_fallback;"
    "feature aware badapt_adaptive : adapt_loss = badapt_adaptive_adapt_loss_fallback;"
    "feature aware badapt_adaptive : adapt_loss_f3 = badapt_adaptive_adapt_loss_f3_fallback;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_builder

BCORE_DEFINE_SPECT( bcore_inst, badapt_builder )
"{"
    "bcore_spect_header_s header;"
    "feature strict aware badapt_builder : get_in_size;"
    "feature strict aware badapt_builder : set_in_size;"
    "feature strict aware badapt_builder : get_out_size;"
    "feature strict aware badapt_builder : set_out_size;"
    "feature strict aware badapt_builder : build;"
"}";

/**********************************************************************************************************************/
// source: badapt_problem
#include "badapt_problem.h"

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_problem_objects

BCORE_DEFINE_OBJECT_INST( badapt_supplier, badapt_problem_sine_random_s )
"{"
    "aware_t _;"
    "sz_t input_size = 32;"
    "u2_t rval = 1234;"
    "f3_t pos_tgt = 0.9;"
    "f3_t neg_tgt = -0.9;"
    "aware badapt_loss* preferred_loss = badapt_loss_l2_s;"
    "func badapt_supplier : preferred_loss;"
    "func badapt_supplier : get_in_size;"
    "func badapt_supplier : get_out_size;"
    "func badapt_supplier : fetch_batch_sample;"
    "func badapt_supplier : fetch_valid_sample;"
"}";

BCORE_DEFINE_OBJECT_INST( badapt_supplier, badapt_problem_polynom_s )
"{"
    "aware_t _;"
    "sz_t input_size = 32;"
    "sz_t output_size = 3;"
    "f3_t range = 1.0;"
    "u2_t rval = 1234;"
    "f3_t noise_level = 0;"
    "aware badapt_loss* preferred_loss = badapt_loss_l2_s;"
    "func badapt_supplier : preferred_loss;"
    "func badapt_supplier : get_in_size;"
    "func badapt_supplier : get_out_size;"
    "func badapt_supplier : fetch_batch_sample;"
    "func badapt_supplier : fetch_valid_sample;"
"}";

BCORE_DEFINE_OBJECT_INST( badapt_supplier, badapt_problem_binary_add_s )
"{"
    "aware_t _;"
    "sz_t bits = 4;"
    "u2_t rval = 1234;"
    "f3_t val_h = 0.9;"
    "f3_t val_l = -0.9;"
    "aware badapt_loss* preferred_loss = badapt_loss_l2_s;"
    "func badapt_supplier : preferred_loss;"
    "func badapt_supplier : get_in_size;"
    "func badapt_supplier : get_out_size;"
    "func badapt_supplier : fetch_batch_sample;"
    "func badapt_supplier : fetch_valid_sample;"
"}";

BCORE_DEFINE_OBJECT_INST( badapt_supplier, badapt_problem_binary_mul_s )
"{"
    "aware_t _;"
    "sz_t bits = 4;"
    "u2_t rval = 1234;"
    "f3_t val_h = 0.9;"
    "f3_t val_l = -0.9;"
    "aware badapt_loss* preferred_loss = badapt_loss_l2_s;"
    "func badapt_supplier : preferred_loss;"
    "func badapt_supplier : get_in_size;"
    "func badapt_supplier : get_out_size;"
    "func badapt_supplier : fetch_batch_sample;"
    "func badapt_supplier : fetch_valid_sample;"
"}";

BCORE_DEFINE_OBJECT_INST( badapt_supplier, badapt_problem_binary_xsg3_s )
"{"
    "aware_t _;"
    "sz_t bits = 4;"
    "u2_t rval = 1234;"
    "f3_t val_h = 0.9;"
    "f3_t val_l = -0.9;"
    "aware badapt_loss* preferred_loss = badapt_loss_l2_s;"
    "func badapt_supplier : preferred_loss;"
    "func badapt_supplier : get_in_size;"
    "func badapt_supplier : get_out_size;"
    "func badapt_supplier : fetch_batch_sample;"
    "func badapt_supplier : fetch_valid_sample;"
"}";

BCORE_DEFINE_OBJECT_INST( badapt_supplier, badapt_problem_binary_hash_s )
"{"
    "aware_t _;"
    "sz_t bits = 4;"
    "u2_t rval = 1234;"
    "f3_t val_h = 0.9;"
    "f3_t val_l = -0.9;"
    "bl_t reverse = false;"
    "aware badapt_loss* preferred_loss = badapt_loss_l2_s;"
    "func badapt_supplier : preferred_loss;"
    "func badapt_supplier : get_in_size;"
    "func badapt_supplier : get_out_size;"
    "func badapt_supplier : fetch_batch_sample;"
    "func badapt_supplier : fetch_valid_sample;"
"}";

/**********************************************************************************************************************/
// source: badapt_activator
#include "badapt_activator.h"

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_activation_objects

BCORE_DEFINE_OBJECT_INST( badapt_activation, badapt_activation_tanh_s )
"{"
    "aware_t _;"
    "func badapt_activation : fx;"
    "func badapt_activation : dy;"
"}";

BCORE_DEFINE_OBJECT_INST( badapt_activation, badapt_activation_relu_s )
"{"
    "aware_t _;"
    "func badapt_activation : fx;"
    "func badapt_activation : dy;"
"}";

BCORE_DEFINE_OBJECT_INST( badapt_activation, badapt_activation_leaky_relu_s )
"{"
    "aware_t _;"
    "func badapt_activation : fx;"
    "func badapt_activation : dy;"
"}";

BCORE_DEFINE_OBJECT_INST( badapt_activation, badapt_activation_softplus_s )
"{"
    "aware_t _;"
    "func badapt_activation : fx;"
    "func badapt_activation : dy;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_activator_objects

BCORE_DEFINE_OBJECT_INST( bcore_inst, badapt_layer_activator_s )
"{"
    "aware_t _;"
    "sz_t layer;"
    "aware badapt_activator => activator;"
"}";

BCORE_DEFINE_OBJECT_INST( bcore_array, badapt_arr_activator_s )
"{"
    "aware_t _;"
    "aware badapt_activator => [] arr;"
"}";

BCORE_DEFINE_OBJECT_INST( bcore_array, badapt_arr_layer_activator_s )
"{"
    "aware_t _;"
    "badapt_layer_activator_s [] arr;"
"}";

BCORE_DEFINE_OBJECT_INST( badapt_activator, badapt_activator_plain_s )
"{"
    "aware_t _;"
    "aware badapt_activation => activation;"
    "func badapt_activator : setup;"
    "func badapt_activator : reset;"
    "func badapt_activator : infer;"
    "func badapt_activator : bgrad;"
    "func badapt_activator : adapt;"
    "func badapt_activator : set_activation;"
    "func badapt_activator : get_activation;"
"}";

BCORE_DEFINE_OBJECT_INST( badapt_activator, badapt_activator_bias_s )
"{"
    "aware_t _;"
    "aware badapt_activation => activation;"
    "f3_t [] arr_bias;"
    "func badapt_activator : setup;"
    "func badapt_activator : reset;"
    "func badapt_activator : infer;"
    "func badapt_activator : bgrad;"
    "func badapt_activator : adapt;"
    "func badapt_activator : set_activation;"
    "func badapt_activator : get_activation;"
"}";

/**********************************************************************************************************************/
// source: badapt_loss
#include "badapt_loss.h"

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_loss_objects

BCORE_DEFINE_OBJECT_INST( badapt_loss, badapt_loss_l2_s )
"{"
    "aware_t _;"
    "func badapt_loss : loss;"
    "func badapt_loss : loss_f3;"
    "func badapt_loss : bgrad;"
"}";

/**********************************************************************************************************************/
// source: badapt_mlp
#include "badapt_mlp.h"

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_mlp

BCORE_DEFINE_OBJECT_INST( bcore_inst, badapt_mlp_layer_s )
"{"
    "aware_t _;"
    "sz_t input_size;"
    "sz_t kernels;"
    "bmath_mf3_s wgt;"
    "aware badapt_activator => act;"
    "hidden bmath_vf3_s out;"
"}";

BCORE_DEFINE_OBJECT_INST( bcore_array, badapt_mlp_arr_layer_s )
"{"
    "aware_t _;"
    "badapt_mlp_layer_s [] arr;"
"}";

BCORE_DEFINE_OBJECT_INST( badapt_adaptive, badapt_mlp_s )
"{"
    "aware_t _;"
    "badapt_dynamics_s dynamics;"
    "badapt_mlp_arr_layer_s arr_layer;"
    "hidden sz_t max_buffer_size;"
    "hidden bmath_vf3_s in;"
    "func badapt_adaptive : get_in_size;"
    "func badapt_adaptive : get_out_size;"
    "func badapt_adaptive : get_dynamics;"
    "func badapt_adaptive : set_dynamics;"
    "func badapt_adaptive : arc_to_sink;"
    "func badapt_adaptive : infer;"
    "func badapt_adaptive : minfer;"
    "func badapt_adaptive : bgrad;"
    "func badapt_adaptive : bgrad_adapt;"
"}";

BCORE_DEFINE_OBJECT_INST( badapt_builder, badapt_builder_mlp_funnel_s )
"{"
    "aware_t _;"
    "sz_t input_size;"
    "sz_t input_kernels = 8;"
    "sz_t output_kernels = 1;"
    "sz_t layers = 2;"
    "f3_t kernels_rate = 0;"
    "u2_t random_seed = 1234;"
    "badapt_dynamics_s dynamics;"
    "badapt_arr_layer_activator_s arr_layer_activator;"
    "func badapt_builder : get_in_size;"
    "func badapt_builder : set_in_size;"
    "func badapt_builder : get_out_size;"
    "func badapt_builder : set_out_size;"
    "func badapt_builder : build;"
"}";

/**********************************************************************************************************************/
// source: badapt_training
#include "badapt_training.h"

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_training_data

BCORE_DEFINE_OBJECT_INST( bcore_inst, badapt_sample_s )
"{"
    "bmath_vf3_s in;"
    "bmath_vf3_s out;"
"}";

BCORE_DEFINE_OBJECT_INST( bcore_array, badapt_arr_sample_s )
"{"
    "aware_t _;"
    "badapt_sample_s [] arr;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_supplier

BCORE_DEFINE_SPECT( bcore_inst, badapt_supplier )
"{"
    "bcore_spect_header_s header;"
    "feature strict aware badapt_supplier : get_in_size;"
    "feature strict aware badapt_supplier : get_out_size;"
    "feature strict aware badapt_supplier : fetch_batch_sample;"
    "feature strict aware badapt_supplier : fetch_valid_sample;"
    "feature aware badapt_supplier : fetch_batch_data = badapt_supplier_fetch_batch_data_default;"
    "feature aware badapt_supplier : fetch_valid_data = badapt_supplier_fetch_valid_data_default;"
    "feature aware badapt_supplier : preferred_loss;"
    "feature aware badapt_supplier : setup_builder = badapt_supplier_setup_builder_default;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_training_objects

BCORE_DEFINE_OBJECT_INST( bcore_inst, badapt_trainer_s )
"{"
    "aware_t _;"
    "aware badapt_loss => loss;"
    "sz_t batch_size = 10000;"
    "sz_t batch_cycles_per_fetch = 1;"
    "sz_t fetch_cycles_per_iteration = 4;"
    "sz_t valid_size = 10000;"
    "sz_t max_iterations = 10;"
"}";

BCORE_DEFINE_OBJECT_INST( bcore_inst, badapt_trainer_state_s )
"{"
    "aware_t _;"
    "sz_t iteration = 0;"
    "f3_t error = 0;"
    "f3_t progress = 0;"
    "f3_t bias = 0;"
    "aware badapt_adaptive => adaptive;"
    "aware badapt_supplier => supplier;"
    "aware badapt_training_guide => guide = badapt_training_guide_std_s;"
    "hidden aware bcore_sink -> log;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_training_guide

BCORE_DEFINE_SPECT( bcore_inst, badapt_training_guide )
"{"
    "bcore_spect_header_s header;"
    "feature strict aware badapt_training_guide : callback;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_training_objects_2

BCORE_DEFINE_OBJECT_INST( badapt_training_guide, badapt_training_guide_std_s )
"{"
    "aware_t _;"
    "f3_t annealing_factor = 0.99;"
    "func badapt_training_guide : callback;"
"}";

/**********************************************************************************************************************/

vd_t badapt_precoded_signal_handler( const bcore_signal_s* o )
{
    switch( bcore_signal_s_handle_type( o, typeof( "badapt_precoded" ) ) )
    {
        case TYPEOF_init1:
        {
            // Comment or remove line below to rebuild this target.
            bcore_const_x_set_d( typeof( "badapt_precoded_hash" ), sr_tp( 3710386839 ) );
            BCORE_REGISTER_FEATURE( badapt_loss_loss );
            BCORE_REGISTER_FEATURE( badapt_loss_loss_f3 );
            BCORE_REGISTER_FEATURE( badapt_loss_bgrad );
            BCORE_REGISTER_SPECT( badapt_loss );
            BCORE_REGISTER_FEATURE( badapt_activation_fx );
            BCORE_REGISTER_FEATURE( badapt_activation_dy );
            BCORE_REGISTER_SPECT( badapt_activation );
            BCORE_REGISTER_FEATURE( badapt_activator_reset );
            BCORE_REGISTER_FEATURE( badapt_activator_setup );
            BCORE_REGISTER_FEATURE( badapt_activator_get_size );
            BCORE_REGISTER_FEATURE( badapt_activator_set_size );
            BCORE_REGISTER_FEATURE( badapt_activator_get_activation );
            BCORE_REGISTER_FEATURE( badapt_activator_set_activation );
            BCORE_REGISTER_FEATURE( badapt_activator_infer );
            BCORE_REGISTER_FEATURE( badapt_activator_bgrad );
            BCORE_REGISTER_FEATURE( badapt_activator_adapt );
            BCORE_REGISTER_SPECT( badapt_activator );
            BCORE_REGISTER_OBJECT( badapt_dynamics_s );
            BCORE_REGISTER_FEATURE( badapt_adaptive_get_in_size );
            BCORE_REGISTER_FEATURE( badapt_adaptive_get_out_size );
            BCORE_REGISTER_FEATURE( badapt_adaptive_infer );
            BCORE_REGISTER_FEATURE( badapt_adaptive_minfer );
            BCORE_REGISTER_FEATURE( badapt_adaptive_bgrad );
            BCORE_REGISTER_FEATURE( badapt_adaptive_bgrad_adapt );
            BCORE_REGISTER_FEATURE( badapt_adaptive_get_dynamics );
            BCORE_REGISTER_FEATURE( badapt_adaptive_set_dynamics );
            BCORE_REGISTER_FEATURE( badapt_adaptive_arc_to_sink );
            BCORE_REGISTER_FEATURE( badapt_adaptive_infer_f3 );
            BCORE_REGISTER_FEATURE( badapt_adaptive_adapt_loss );
            BCORE_REGISTER_FEATURE( badapt_adaptive_adapt_loss_f3 );
            BCORE_REGISTER_FFUNC( badapt_adaptive_arc_to_sink, badapt_adaptive_arc_to_sink_fallback );
            BCORE_REGISTER_FFUNC( badapt_adaptive_infer_f3, badapt_adaptive_infer_f3_fallback );
            BCORE_REGISTER_FFUNC( badapt_adaptive_adapt_loss, badapt_adaptive_adapt_loss_fallback );
            BCORE_REGISTER_FFUNC( badapt_adaptive_adapt_loss_f3, badapt_adaptive_adapt_loss_f3_fallback );
            BCORE_REGISTER_SPECT( badapt_adaptive );
            BCORE_REGISTER_FEATURE( badapt_builder_get_in_size );
            BCORE_REGISTER_FEATURE( badapt_builder_set_in_size );
            BCORE_REGISTER_FEATURE( badapt_builder_get_out_size );
            BCORE_REGISTER_FEATURE( badapt_builder_set_out_size );
            BCORE_REGISTER_FEATURE( badapt_builder_build );
            BCORE_REGISTER_SPECT( badapt_builder );
            BCORE_REGISTER_FFUNC( badapt_supplier_preferred_loss, badapt_problem_sine_random_s_preferred_loss );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_in_size, badapt_problem_sine_random_s_get_in_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_out_size, badapt_problem_sine_random_s_get_out_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_batch_sample, badapt_problem_sine_random_s_fetch_batch_sample );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_valid_sample, badapt_problem_sine_random_s_fetch_valid_sample );
            BCORE_REGISTER_OBJECT( badapt_problem_sine_random_s );
            BCORE_REGISTER_FFUNC( badapt_supplier_preferred_loss, badapt_problem_polynom_s_preferred_loss );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_in_size, badapt_problem_polynom_s_get_in_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_out_size, badapt_problem_polynom_s_get_out_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_batch_sample, badapt_problem_polynom_s_fetch_batch_sample );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_valid_sample, badapt_problem_polynom_s_fetch_valid_sample );
            BCORE_REGISTER_OBJECT( badapt_problem_polynom_s );
            BCORE_REGISTER_FFUNC( badapt_supplier_preferred_loss, badapt_problem_binary_add_s_preferred_loss );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_in_size, badapt_problem_binary_add_s_get_in_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_out_size, badapt_problem_binary_add_s_get_out_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_batch_sample, badapt_problem_binary_add_s_fetch_batch_sample );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_valid_sample, badapt_problem_binary_add_s_fetch_valid_sample );
            BCORE_REGISTER_OBJECT( badapt_problem_binary_add_s );
            BCORE_REGISTER_FFUNC( badapt_supplier_preferred_loss, badapt_problem_binary_mul_s_preferred_loss );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_in_size, badapt_problem_binary_mul_s_get_in_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_out_size, badapt_problem_binary_mul_s_get_out_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_batch_sample, badapt_problem_binary_mul_s_fetch_batch_sample );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_valid_sample, badapt_problem_binary_mul_s_fetch_valid_sample );
            BCORE_REGISTER_OBJECT( badapt_problem_binary_mul_s );
            BCORE_REGISTER_FFUNC( badapt_supplier_preferred_loss, badapt_problem_binary_xsg3_s_preferred_loss );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_in_size, badapt_problem_binary_xsg3_s_get_in_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_out_size, badapt_problem_binary_xsg3_s_get_out_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_batch_sample, badapt_problem_binary_xsg3_s_fetch_batch_sample );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_valid_sample, badapt_problem_binary_xsg3_s_fetch_valid_sample );
            BCORE_REGISTER_OBJECT( badapt_problem_binary_xsg3_s );
            BCORE_REGISTER_FFUNC( badapt_supplier_preferred_loss, badapt_problem_binary_hash_s_preferred_loss );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_in_size, badapt_problem_binary_hash_s_get_in_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_out_size, badapt_problem_binary_hash_s_get_out_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_batch_sample, badapt_problem_binary_hash_s_fetch_batch_sample );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_valid_sample, badapt_problem_binary_hash_s_fetch_valid_sample );
            BCORE_REGISTER_OBJECT( badapt_problem_binary_hash_s );
            BCORE_REGISTER_FFUNC( badapt_activation_fx, badapt_activation_tanh_s_fx );
            BCORE_REGISTER_FFUNC( badapt_activation_dy, badapt_activation_tanh_s_dy );
            BCORE_REGISTER_OBJECT( badapt_activation_tanh_s );
            BCORE_REGISTER_FFUNC( badapt_activation_fx, badapt_activation_relu_s_fx );
            BCORE_REGISTER_FFUNC( badapt_activation_dy, badapt_activation_relu_s_dy );
            BCORE_REGISTER_OBJECT( badapt_activation_relu_s );
            BCORE_REGISTER_FFUNC( badapt_activation_fx, badapt_activation_leaky_relu_s_fx );
            BCORE_REGISTER_FFUNC( badapt_activation_dy, badapt_activation_leaky_relu_s_dy );
            BCORE_REGISTER_OBJECT( badapt_activation_leaky_relu_s );
            BCORE_REGISTER_FFUNC( badapt_activation_fx, badapt_activation_softplus_s_fx );
            BCORE_REGISTER_FFUNC( badapt_activation_dy, badapt_activation_softplus_s_dy );
            BCORE_REGISTER_OBJECT( badapt_activation_softplus_s );
            BCORE_REGISTER_OBJECT( badapt_layer_activator_s );
            BCORE_REGISTER_OBJECT( badapt_arr_activator_s );
            BCORE_REGISTER_OBJECT( badapt_arr_layer_activator_s );
            BCORE_REGISTER_FFUNC( badapt_activator_setup, badapt_activator_plain_s_setup );
            BCORE_REGISTER_FFUNC( badapt_activator_reset, badapt_activator_plain_s_reset );
            BCORE_REGISTER_FFUNC( badapt_activator_infer, badapt_activator_plain_s_infer );
            BCORE_REGISTER_FFUNC( badapt_activator_bgrad, badapt_activator_plain_s_bgrad );
            BCORE_REGISTER_FFUNC( badapt_activator_adapt, badapt_activator_plain_s_adapt );
            BCORE_REGISTER_FFUNC( badapt_activator_set_activation, badapt_activator_plain_s_set_activation );
            BCORE_REGISTER_FFUNC( badapt_activator_get_activation, badapt_activator_plain_s_get_activation );
            BCORE_REGISTER_OBJECT( badapt_activator_plain_s );
            BCORE_REGISTER_FFUNC( badapt_activator_setup, badapt_activator_bias_s_setup );
            BCORE_REGISTER_FFUNC( badapt_activator_reset, badapt_activator_bias_s_reset );
            BCORE_REGISTER_FFUNC( badapt_activator_infer, badapt_activator_bias_s_infer );
            BCORE_REGISTER_FFUNC( badapt_activator_bgrad, badapt_activator_bias_s_bgrad );
            BCORE_REGISTER_FFUNC( badapt_activator_adapt, badapt_activator_bias_s_adapt );
            BCORE_REGISTER_FFUNC( badapt_activator_set_activation, badapt_activator_bias_s_set_activation );
            BCORE_REGISTER_FFUNC( badapt_activator_get_activation, badapt_activator_bias_s_get_activation );
            BCORE_REGISTER_OBJECT( badapt_activator_bias_s );
            BCORE_REGISTER_FFUNC( badapt_loss_loss, badapt_loss_l2_s_loss );
            BCORE_REGISTER_FFUNC( badapt_loss_loss_f3, badapt_loss_l2_s_loss_f3 );
            BCORE_REGISTER_FFUNC( badapt_loss_bgrad, badapt_loss_l2_s_bgrad );
            BCORE_REGISTER_OBJECT( badapt_loss_l2_s );
            BCORE_REGISTER_OBJECT( badapt_mlp_layer_s );
            BCORE_REGISTER_OBJECT( badapt_mlp_arr_layer_s );
            BCORE_REGISTER_FFUNC( badapt_adaptive_get_in_size, badapt_mlp_s_get_in_size );
            BCORE_REGISTER_FFUNC( badapt_adaptive_get_out_size, badapt_mlp_s_get_out_size );
            BCORE_REGISTER_FFUNC( badapt_adaptive_get_dynamics, badapt_mlp_s_get_dynamics );
            BCORE_REGISTER_FFUNC( badapt_adaptive_set_dynamics, badapt_mlp_s_set_dynamics );
            BCORE_REGISTER_FFUNC( badapt_adaptive_arc_to_sink, badapt_mlp_s_arc_to_sink );
            BCORE_REGISTER_FFUNC( badapt_adaptive_infer, badapt_mlp_s_infer );
            BCORE_REGISTER_FFUNC( badapt_adaptive_minfer, badapt_mlp_s_minfer );
            BCORE_REGISTER_FFUNC( badapt_adaptive_bgrad, badapt_mlp_s_bgrad );
            BCORE_REGISTER_FFUNC( badapt_adaptive_bgrad_adapt, badapt_mlp_s_bgrad_adapt );
            BCORE_REGISTER_OBJECT( badapt_mlp_s );
            BCORE_REGISTER_FFUNC( badapt_builder_get_in_size, badapt_builder_mlp_funnel_s_get_in_size );
            BCORE_REGISTER_FFUNC( badapt_builder_set_in_size, badapt_builder_mlp_funnel_s_set_in_size );
            BCORE_REGISTER_FFUNC( badapt_builder_get_out_size, badapt_builder_mlp_funnel_s_get_out_size );
            BCORE_REGISTER_FFUNC( badapt_builder_set_out_size, badapt_builder_mlp_funnel_s_set_out_size );
            BCORE_REGISTER_FFUNC( badapt_builder_build, badapt_builder_mlp_funnel_s_build );
            BCORE_REGISTER_OBJECT( badapt_builder_mlp_funnel_s );
            BCORE_REGISTER_OBJECT( badapt_sample_s );
            BCORE_REGISTER_OBJECT( badapt_arr_sample_s );
            BCORE_REGISTER_FEATURE( badapt_supplier_get_in_size );
            BCORE_REGISTER_FEATURE( badapt_supplier_get_out_size );
            BCORE_REGISTER_FEATURE( badapt_supplier_fetch_batch_sample );
            BCORE_REGISTER_FEATURE( badapt_supplier_fetch_valid_sample );
            BCORE_REGISTER_FEATURE( badapt_supplier_fetch_batch_data );
            BCORE_REGISTER_FEATURE( badapt_supplier_fetch_valid_data );
            BCORE_REGISTER_FEATURE( badapt_supplier_preferred_loss );
            BCORE_REGISTER_FEATURE( badapt_supplier_setup_builder );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_batch_data, badapt_supplier_fetch_batch_data_default );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_valid_data, badapt_supplier_fetch_valid_data_default );
            BCORE_REGISTER_FFUNC( badapt_supplier_setup_builder, badapt_supplier_setup_builder_default );
            BCORE_REGISTER_SPECT( badapt_supplier );
            BCORE_REGISTER_OBJECT( badapt_trainer_s );
            BCORE_REGISTER_OBJECT( badapt_trainer_state_s );
            BCORE_REGISTER_FEATURE( badapt_training_guide_callback );
            BCORE_REGISTER_SPECT( badapt_training_guide );
            BCORE_REGISTER_FFUNC( badapt_training_guide_callback, badapt_training_guide_std_s_callback );
            BCORE_REGISTER_OBJECT( badapt_training_guide_std_s );
        }
        break;
        default: break;
    }
    return NULL;
}
