/** This file was generated by the beth-precode-compiler. Not suitable for manual editing.
 *
 *  Copyright and License:
 *    If a specification exists for the repository or folder in which the file is located,
 *    that specification shall apply. Otherwise, the Copyright and License of the associated
 *    source code files containing beth-precode shall apply.
 */

#include "badapt_precoded.h"
#include "bcore_spect.h"
#include "bcore_spect_inst.h"
#include "bcore_sr.h"
#include "bcore_const_manager.h"


/**********************************************************************************************************************/
// source: badapt_dev_problem
#include "badapt_dev_problem.h"

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_dev_problem_objects

BCORE_DEFINE_OBJECT_INST( badapt_supplier, badapt_dev_problem_recurrent_kjv_s )
"{"
    "aware_t _;"
    "sz_t input_size = 32;"
    "u2_t rval = 1234;"
    "f3_t pos_tgt = 0.9;"
    "f3_t neg_tgt = -0.9;"
    "aware badapt_loss* preferred_loss = badapt_loss_l2_s;"
    "func badapt_supplier : preferred_loss;"
    "func badapt_supplier : get_in_size;"
    "func badapt_supplier : get_out_size;"
    "func badapt_supplier : fetch_sample_tio;"
    "func badapt_supplier : fetch_sample_vio;"
"}";

/**********************************************************************************************************************/

vd_t badapt_precoded_signal_handler( const bcore_signal_s* o )
{
    switch( bcore_signal_s_handle_type( o, typeof( "badapt_precoded" ) ) )
    {
        case TYPEOF_init1:
        {
            // Comment or remove line below to rebuild this target.
            bcore_const_x_set_d( typeof( "badapt_precoded_hash" ), sr_tp( 4091075963 ) );
            BCORE_REGISTER_FFUNC( badapt_supplier_preferred_loss, badapt_dev_problem_recurrent_kjv_s_preferred_loss );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_in_size, badapt_dev_problem_recurrent_kjv_s_get_in_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_get_out_size, badapt_dev_problem_recurrent_kjv_s_get_out_size );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_sample_tio, badapt_dev_problem_recurrent_kjv_s_fetch_sample_tio );
            BCORE_REGISTER_FFUNC( badapt_supplier_fetch_sample_vio, badapt_dev_problem_recurrent_kjv_s_fetch_sample_vio );
            BCORE_REGISTER_OBJECT( badapt_dev_problem_recurrent_kjv_s );
        }
        break;
        default: break;
    }
    return NULL;
}
