/** This file was generated by the beth-precode-compiler. Not suitable for manual editing.
 *
 *  Copyright and License:
 *    If a specification exists for the repository or folder in which the file is located,
 *    that specification shall apply. Otherwise, the Copyright and License of the associated
 *    source code files containing beth-precode shall apply.
 */

#include "badapt_precoded.h"
#include "bcore_spect.h"
#include "bcore_spect_inst.h"
#include "bcore_sr.h"
#include "bcore_const_manager.h"


/**********************************************************************************************************************/
// source: badapt_features
#include "badapt_features.h"

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_adaptive

BCORE_DEFINE_SPECT( bcore_inst, badapt_adaptive )
"{"
    "bcore_spect_header_s header;"
    "feature strict badapt_adaptive : reset;"
    "feature strict badapt_adaptive : setup;"
    "feature strict badapt_adaptive : get_in_size;"
    "feature strict badapt_adaptive : set_in_size;"
    "feature strict badapt_adaptive : get_out_size;"
    "feature strict badapt_adaptive : set_out_size;"
    "feature strict badapt_adaptive : infer;"
    "feature strict badapt_adaptive : minfer;"
    "feature strict badapt_adaptive : bgrad;"
    "feature strict badapt_adaptive : bgrad_adapt;"
    "feature badapt_adaptive : get_step;"
    "feature badapt_adaptive : set_step;"
    "feature badapt_adaptive : get_regularization;"
    "feature badapt_adaptive : set_regularization;"
    "feature badapt_adaptive : arc_to_sink = badapt_adaptive_arc_to_sink_fallback;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_activation

BCORE_DEFINE_SPECT( bcore_inst, badapt_activation )
"{"
    "bcore_spect_header_s header;"
    "feature strict badapt_activation : fx;"
    "feature strict badapt_activation : dy;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_activator

BCORE_DEFINE_SPECT( bcore_inst, badapt_activator )
"{"
    "bcore_spect_header_s header;"
    "feature strict badapt_activator : reset;"
    "feature strict badapt_activator : setup;"
    "feature badapt_activator : get_size;"
    "feature badapt_activator : set_size;"
    "feature strict badapt_activator : infer;"
    "feature strict badapt_activator : bgrad;"
    "feature strict badapt_activator : adapt;"
"}";

/**********************************************************************************************************************/
// source: badapt_activator
#include "badapt_activator.h"

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_activation_objects

BCORE_DEFINE_OBJECT_INST( badapt_activation, badapt_activation_tanh_s )
"{"
    "aware_t _;"
    "func badapt_activation : fx;"
    "func badapt_activation : dy;"
"}";

BCORE_DEFINE_OBJECT_INST( badapt_activation, badapt_activation_relu_s )
"{"
    "aware_t _;"
    "func badapt_activation : fx;"
    "func badapt_activation : dy;"
"}";

BCORE_DEFINE_OBJECT_INST( badapt_activation, badapt_activation_leaky_relu_s )
"{"
    "aware_t _;"
    "func badapt_activation : fx;"
    "func badapt_activation : dy;"
"}";

BCORE_DEFINE_OBJECT_INST( badapt_activation, badapt_activation_softplus_s )
"{"
    "aware_t _;"
    "func badapt_activation : fx;"
    "func badapt_activation : dy;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: badapt_activator_objects

BCORE_DEFINE_OBJECT_INST( badapt_activator, badapt_activator_plain_s )
"{"
    "sr_s activation;"
    "func badapt_activator : setup;"
    "func badapt_activator : reset;"
    "func badapt_activator : infer;"
    "func badapt_activator : bgrad;"
    "func badapt_activator : adapt;"
"}";

/**********************************************************************************************************************/

vd_t badapt_precoded_signal_handler( const bcore_signal_s* o )
{
    switch( bcore_signal_s_handle_type( o, typeof( "badapt_precoded" ) ) )
    {
        case TYPEOF_init1:
        {
            // Comment or remove line below to rebuild this target.
            bcore_const_x_set_d( typeof( "badapt_precoded_hash" ), sr_tp( 363207283 ) );
            BCORE_REGISTER_FEATURE( badapt_adaptive_reset );
            BCORE_REGISTER_FEATURE( badapt_adaptive_setup );
            BCORE_REGISTER_FEATURE( badapt_adaptive_get_in_size );
            BCORE_REGISTER_FEATURE( badapt_adaptive_set_in_size );
            BCORE_REGISTER_FEATURE( badapt_adaptive_get_out_size );
            BCORE_REGISTER_FEATURE( badapt_adaptive_set_out_size );
            BCORE_REGISTER_FEATURE( badapt_adaptive_infer );
            BCORE_REGISTER_FEATURE( badapt_adaptive_minfer );
            BCORE_REGISTER_FEATURE( badapt_adaptive_bgrad );
            BCORE_REGISTER_FEATURE( badapt_adaptive_bgrad_adapt );
            BCORE_REGISTER_FEATURE( badapt_adaptive_get_step );
            BCORE_REGISTER_FEATURE( badapt_adaptive_set_step );
            BCORE_REGISTER_FEATURE( badapt_adaptive_get_regularization );
            BCORE_REGISTER_FEATURE( badapt_adaptive_set_regularization );
            BCORE_REGISTER_FEATURE( badapt_adaptive_arc_to_sink );
            BCORE_REGISTER_FFUNC( badapt_adaptive_arc_to_sink, badapt_adaptive_arc_to_sink_fallback );
            BCORE_REGISTER_SPECT( badapt_adaptive );
            BCORE_REGISTER_FEATURE( badapt_activation_fx );
            BCORE_REGISTER_FEATURE( badapt_activation_dy );
            BCORE_REGISTER_SPECT( badapt_activation );
            BCORE_REGISTER_FEATURE( badapt_activator_reset );
            BCORE_REGISTER_FEATURE( badapt_activator_setup );
            BCORE_REGISTER_FEATURE( badapt_activator_get_size );
            BCORE_REGISTER_FEATURE( badapt_activator_set_size );
            BCORE_REGISTER_FEATURE( badapt_activator_infer );
            BCORE_REGISTER_FEATURE( badapt_activator_bgrad );
            BCORE_REGISTER_FEATURE( badapt_activator_adapt );
            BCORE_REGISTER_SPECT( badapt_activator );
            BCORE_REGISTER_FFUNC( badapt_activation_fx, badapt_activation_tanh_s_fx );
            BCORE_REGISTER_FFUNC( badapt_activation_dy, badapt_activation_tanh_s_dy );
            BCORE_REGISTER_OBJECT( badapt_activation_tanh_s );
            BCORE_REGISTER_FFUNC( badapt_activation_fx, badapt_activation_relu_s_fx );
            BCORE_REGISTER_FFUNC( badapt_activation_dy, badapt_activation_relu_s_dy );
            BCORE_REGISTER_OBJECT( badapt_activation_relu_s );
            BCORE_REGISTER_FFUNC( badapt_activation_fx, badapt_activation_leaky_relu_s_fx );
            BCORE_REGISTER_FFUNC( badapt_activation_dy, badapt_activation_leaky_relu_s_dy );
            BCORE_REGISTER_OBJECT( badapt_activation_leaky_relu_s );
            BCORE_REGISTER_FFUNC( badapt_activation_fx, badapt_activation_softplus_s_fx );
            BCORE_REGISTER_FFUNC( badapt_activation_dy, badapt_activation_softplus_s_dy );
            BCORE_REGISTER_OBJECT( badapt_activation_softplus_s );
            BCORE_REGISTER_FFUNC( badapt_activator_setup, badapt_activator_plain_s_setup );
            BCORE_REGISTER_FFUNC( badapt_activator_reset, badapt_activator_plain_s_reset );
            BCORE_REGISTER_FFUNC( badapt_activator_infer, badapt_activator_plain_s_infer );
            BCORE_REGISTER_FFUNC( badapt_activator_bgrad, badapt_activator_plain_s_bgrad );
            BCORE_REGISTER_FFUNC( badapt_activator_adapt, badapt_activator_plain_s_adapt );
            BCORE_REGISTER_OBJECT( badapt_activator_plain_s );
        }
        break;
        default: break;
    }
    return NULL;
}
